### ISSUE TITLE
Lowercase proportions /b /d /p /q /g /thorn

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#100]
As the Cyrillic block is borrowing some glyphs from the Latin one, I am really struggling to understand some strange anomalies of glyph widths. For instance the group /b /p /q /d appears too broad compared to /o in all but the :Cond masters - where they look as expected and also fit numerically into my understanding of how they should look. Also I have already reported that /v was too narrow and bit too pointy - as I see it got fixed. 

For me there are two solutions:
- either you finalize the Latin lowercase so I can accommodate to these proportions - as i cannot make a Cyrillic that is incompatible with lets say /p /e /c /o... etc and as you are aware the proportions are kind of connected to my work - for instance with that width of /p I should make a  /uni0432 (Ve) far wider then needed just so it does not look like midget...
- or I make my own clones of the glyphs needed and adapt them to be usable for the Cyrillic block in case you feel your design was final. I did that with /P (tagged with #67 noauto) and I feel pressed to do that in the lowercase Cyr. Actually the both blocks are separate writing systems, so theoretically they do not need to be identical....

**Comment by kateliev** [comment]
Thin - proportions are way off?
![image](https://user-images.githubusercontent.com/10247582/64178199-b2e8cd00-ce69-11e9-8fa2-ea94a1c85719.png)
Medium - better but still too wide for /b /p in comparison to /o /n
![image](https://user-images.githubusercontent.com/10247582/64178270-d6137c80-ce69-11e9-925c-865c23352776.png)
Cnd - imho very good!
![image](https://user-images.githubusercontent.com/10247582/64179862-7f5b7200-ce6c-11e9-96e5-088baa3fd1e2.png)

**Comment by kateliev** [comment]
:Lt Current
![image](https://user-images.githubusercontent.com/10247582/64180063-d103fc80-ce6c-11e9-9806-73040fdec95f.png)
![image](https://user-images.githubusercontent.com/10247582/64180071-d6614700-ce6c-11e9-8386-bc56f1353619.png)

With -10u less then the counter of /o
![image](https://user-images.githubusercontent.com/10247582/64180140-f6910600-ce6c-11e9-8f68-39e028451d3b.png)
![image](https://user-images.githubusercontent.com/10247582/64180152-fbee5080-ce6c-11e9-9434-34a412b92a38.png)

**Comment by tphinney** [comment]
As a general rule, if you see something inconsistent or otherwise bad in the Latin, we should fix it! Especially, but not only, if it also affects the Cyrillic.

I am curious to hear other opinions on these particular suggestions.

**Comment by servantb** [comment]
@kateliev I think you're right about the width of the /b /d /p /q counters. They should be a bit narrower than the /o.

Also, the counters in the /b /d /p /q in all of the :Blk masters need to be adjusted vertically so they are closer (if not equivalent) to the height of the /o. Right now they are too tall in the :Blk and :BlkExp, and too short in the :BlkCnd.

**Comment by tphinney** [comment]
I'm fine with the width change.

I agree that the :Blk :BlkCnd :BlkExp ) horizontal thicknesses (= counters as well) need adjusting. The question is, are the bdpq (and /thorn) versions right, or is the /o the better model?

**Comment by IgorFreiberger** [comment]
> I'm fine with the width change.
Agreed.

**Comment by servantb** [comment]
> I agree that the :Blk :BlkCnd :BlkExp ) horizontal thicknesses (= counters as well) need adjusting. The question is, are the bdpq (and /thorn) versions right, or is the /o the better model?

I think the /o should be the model, given the color of the /a, /e, and /s. Those glyphs can't e made lighter, so the :Blk weights should stay consistently darker. Right now our key glyphs, /o and /n, match that color, so the /b, /d, /p, /q, and /thorn should follow suit.

**Comment by tphinney** [comment]
Is it possible the horizontals of the :Blk /o are too heavy and should be lightened?
I have been wondering this for a while.

**Comment by tphinney** [comment]
Did some final tweaks on this yesterday to :BlkCnd , as we discussed by voice. Feel free to review, but I think it is good enough now.

**Comment by servantb** [comment]
Reviewed. I think it looks good.
