### ISSUE TITLE
Lowercase overshoots

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#101]
Here are some :Lt Cnd lowercase glyphs with upper ocershoot U+4 and lower overshoot B-4?
![image](https://user-images.githubusercontent.com/10247582/64185857-825b6000-ce76-11e9-84a8-4f94d55704e4.png)
...and here :Lt has no overshoots at all
![image](https://user-images.githubusercontent.com/10247582/64185939-a9b22d00-ce76-11e9-9ec2-c462e39bae9e.png)
:Lt Ctr has also no overshoots, but :Lt Cnd Ctr has U+4 B-4
I presume this was done intentionally...

**Comment by kateliev** [comment]
Never-mind figured it out

**Comment by tphinney** [comment]
The last part was on purpose.

BUT, the -4 vs -3 thing... that is a bug.
