### ISSUE TITLE
Cyrillic gone again....

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#102]
After my latest push to the repo - the work I've done yesterday is gone....
![image](https://user-images.githubusercontent.com/10247582/64240478-9a7cbf00-cf0a-11e9-86d0-139454ebfdab.png)

The state of Cyr block is like before the weekend....

**Comment by kateliev** [comment]
Before the weekend:
![image](https://user-images.githubusercontent.com/10247582/64240605-d44dc580-cf0a-11e9-9d3c-e2612e0392b7.png)
Should be:
![image](https://user-images.githubusercontent.com/10247582/64240727-1414ad00-cf0b-11e9-86a7-a29d7828d314.png)

As stated before, I will manually merge - deleting old Cyrillic and Appending the new...

**Comment by IgorFreiberger** [comment]
I downloaded the whole repo, got the last VFJ and then pasted what I did. What I can see here:

Repo backup from 2019.09.02:
![SG backup 190902](https://user-images.githubusercontent.com/27840848/64242088-4a3a3880-cedb-11e9-8549-6fb5c931104a.jpg)

Repo backup from 2019.09.03:
![SG backup 190903](https://user-images.githubusercontent.com/27840848/64242124-57572780-cedb-11e9-9f6c-cba03d5045fb.jpg)

File uploaded by Thomas in 2019.09.03, noon:
![SG 20190903 Thomas](https://user-images.githubusercontent.com/27840848/64242162-6b028e00-cedb-11e9-8bfe-c672edd3e900.jpg)

File uploaded by me in 2019.09.03, night:
![SG 20190903 Igor](https://user-images.githubusercontent.com/27840848/64242192-7a81d700-cedb-11e9-852c-90723812ba89.jpg)

**Comment by kateliev** [comment]
@IgorFreiberger I am not accusing anybody... This is all I know...
![image](https://user-images.githubusercontent.com/10247582/64259265-708ac300-cf31-11e9-869d-17069cbae0a8.png)

As said again, discussing some other issue: I have no problem with my work missing, as I keep extensive backups of all I do. Also I work on some small, but very concentrated, portion of the font, so I can easily spot problems as soon as they arise and fix them. 

This issue is here to warn us all, that stuff can disappear and we are kind of loosing focus on what goes where...

**Comment by IgorFreiberger** [comment]
No, no, I did not imply you were accusing someone. I was gathering as much information as possible to help. But happily you have all work available in your side.

**Comment by tphinney** [comment]
Igor, can you do that same comparison, but showing everything in Glyph ID order? That might make things more apparent. It seems like something got lost between the first two "backups": your second backup has fewer glyphs than the first. But the glyph order is also different in each of these, making it hard to tell which glyphs were added and which are missing/deleted.

I am not too interested in blame, but I do want to sort out which among us is dropping glyphs by not working from the last check-in. Heck, it could even be more than one of us. Whoever it is, just needs to review procedures and be more careful, is all!

**Comment by tphinney** [comment]
We have not had any troubles in many weeks now, after those of us still on the project went over procedures for merging data. I think we are safe as we move into the endgame.
