### ISSUE TITLE
Curved bows in :Lt masters

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#103]
I kindly wander why the approach was not utilized. To me this is a totally adequate solution that removes the "squareness" so "eye-picking" in :Lt masters
![image](https://user-images.githubusercontent.com/10247582/64251879-3239d780-cf22-11e9-973e-41262ca9449c.png)

It interpolates rather nice:
![image](https://user-images.githubusercontent.com/10247582/64251912-41b92080-cf22-11e9-86d2-d1468b795a29.png)

Also same approach could be used everywhere in the font, where more softer look is desirable.

I have created a dummy glyh /b.alt for you to examine. 
_Note: Because there is also a third solution in the .mask.Laters there are two more nodes (besides the two added - totally +2+2=+4),_

**Comment by tphinney** [comment]
I tried this early on and didn't make it work. I think Brandon may remember this attempt, it was right around the time he got involved, perhaps? But maybe I just didn’t do it correctly.  :)

We see the same difference in Benton’s original Bank Gothic, between the lighter weight and the medium.

@kateliev Can you fix b.alt so it actually interpolates between all the masters? Currently in the font I just sync'd from the repo, there are two incompatible versions among the 18 masters. If it can be made to work well (including the :Ctr axis, which I think caused the trouble before) then we can consider how much we like it and how much work it would be to retrofit the font.

I am sure it would delay the project, but it might be worth it. But first let's make sure it can work!

**Comment by servantb** [comment]
The problem here is with the /o. I think we can all agree that one of the defining features of Bank Gothic is the rectangular counters. The /D is already an outlier in this design, and the /B, /P, and /R somewhat as well. However, /C, /G, /J, /Q, /S, and /U all follow the pattern of square counters inside rounded forms.

So if we go the route of having rounded counters inside weights lighter than :Med, would we do that to the /o? Or the other rounded letters? Or the uppercase rounded letters? And would those forms be true to the spirit of the original?

I agree that /b.alt.1 looks amazing. I think it's a gorgeous, elegant solution. However, I wonder if the pandora's box that solution opens is worth it. It would bring a lot of design decision questions into play, and I'm not sure that our timeline with the scope of the project as it is will allow for that.

**Comment by IgorFreiberger** [comment]
Although I am not assigned for this topic, I completely agree with Brandon.

**Comment by servantb** [comment]
And, yeah, the original Bank Gothic Light dropped the square counters and had rounded ones. So that answers the question, "Would it be true to the spirit of the original?" Yes.

Which then answers the question, "Would we have to do it to all the rounded forms?" Yes.

So then the only question left is, "Is it worth it to add all that work?"

**Comment by kateliev** [comment]
> The problem here is with the /o. I think we can all agree that one of the defining features of Bank Gothic is the rectangular counters...

Of course I agree with that, but to be honest I never looked at SG as being BG with different name, nor even a revival. It is a totally different face the moment we added ultra lights, contrast, italics and of course lowercase... Or if we agree that it is BG inspired, why try making it the same - why not better...
Yes! rectangular counters* - sharp to soft contrast is the essence of the typeface, but for me this does not quite work in the :Lights, for the face becomes so "squarish" that it becomes some other font...

> So if we go the route of having rounded counters inside weights lighter than :Med...

Yes I would change the /O /o in the :Lights, as long as it looks good!

> I wonder if the pandora's box that solution opens is worth it. It would bring a lot of design decision questions into play, and I'm not sure that our timeline with the scope of the project as it is will allow for that.

Yes I know, I am also afraid of that this change would bring a lot new pieces in the game. What I like about the current situation is the *clear vision* - design is good, conscious and well executed. But for me the :Lights really bring questions of style and readability... Then again If we "blur" this vision I am not quite sure where we will end...

> So then the only question left is, "Is it worth it to add all that work?"

For me as a designer - clearly Yes! For a project such as this - a display typeface - I would sacrifice practicality for expression, thus I would always prefer better looking, better designed, attractive glyphs before... most features, extensive diacritics or even pro kerning.

_* rectangular counters: we could try minimizing the transitional effect of soft to sharp in the passage :Lt to :Med by introducing some Glyph :masters and setting them early on the Axis as exceptions so the designs swap as soon the outside curves have sufficient radius... To be honest i do not know if they yet work, or are usable in VF production. Maybe @IgorFreiberger knows, how we could implement such trick..._

**Comment by kateliev** [comment]
To conclude... I strongly support the idea that you and @tphinney are the fathers of this font/design and you are the only ones that should pick up the course we are all heading. I do not intend to mess with the design decision you already made - I just felt compelled to ask the question, as I see it as an opportunity lost...

**Comment by kateliev** [comment]
... here is a crazy idea if you opt-out of the proposed design for any number of reasons - for SG v2 add it on a **Style Axis** - would be beyond cool :)

**Comment by tphinney** [comment]
So, I am convinced this is better.

I think either choice is OK. I like #2 slightly more, but it is also more work. I gather Vassil feels the same. Any other thoughts?

**Comment by servantb** [comment]
I like the proposed solutions as well. After reading, I agree with @kateliev's philosophy.
My preference is for alt no. 1, as I really enjoy the abrupt joints with the stem.

Also, I don't think we'll have to do any glyph by glyph transitional masters. (This is my suspicion, but we'll see.)

Okay. Are we doing this, then?

**Comment by kateliev** [comment]
2 is really better, but will complicate a lot if designs for instance we will be forced to look for new solutions in the /n group. I am ok with 1. I could try TR-igging the replacement in some way. I had a in place contour replacer/injector in FL5, maybe i can adapt it superficially in FL6... Will meditate on this over the weekend.

**Comment by tphinney** [comment]
I vote we wait and see if @kateliev can (partially) automate the work, if he is so inclined.

**Comment by tphinney** [comment]
But assuming he can do so: yes, we are doing this.

**Comment by kateliev** [comment]
Done processing: /C, /G, /J, /O, /Q, /S, /U, /a, /b, /c, /d, /e, /g, /h, /uni0237, /m, /n, /o, /p, /q, /r, /s, /t, /u, /zero, /two, /three, /Euro, /cent, /Thorn, /uni018F, /eth, /oslash, /uni0404, /uni0411, /uni0417, /uni0420, /uni0423, /uni0424, /uni0427, /uni042A, /uni042B, /uni042C, /uni042E, /uni042F, /uni0437, /uni0444, /uni0447, /uni044A, /uni044B, /uni044C, /uni0454, /zero.zero, /uni040A, /uni044E, 

Edited glyphs are marked in **magenta**
![image](https://user-images.githubusercontent.com/10247582/64533444-2aac7100-d31c-11e9-9336-8e6d3376ce44.png)

I am pretty happy about the result.

**Comment by kateliev** [comment]
In the scripts folder there is a little tool called **SG-Glyph-CornerTool.py** that will allow you to make these transformation using predefined presets for _Uppercase_ and _Lowercase_.

Usage is very simple:
![image](https://user-images.githubusercontent.com/10247582/64533905-22086a80-d31d-11e9-93c6-2eb1fa9345ca.png)

Corner swapping is mainly due the different lengths of handles - so it swaps the tension.

Also there is a two-node corner button for cases where the corner already has two nodes as shown below :
![image](https://user-images.githubusercontent.com/10247582/64534123-86c3c500-d31d-11e9-93cc-e6b6d520ce18.png)

Also have in mind that in situations where the start point is part of the angle to be modified, the operation will result an error - so to avoid complex algorithms and too much tinkering - i have just added a Set Start point button, for you to relocate the start, chasing it away from the corner edited.
![image](https://user-images.githubusercontent.com/10247582/64534358-fafe6880-d31d-11e9-81c0-3f71f9072ab6.png)

And finally, if you ever find the tool useful, or want to change something in future. You could draw yourself the perfect corners and in case you want to duplicate them among other designs, you could select the finished designs, inner and outer, and pick them up with **Get Inner** and **Get outer** buttons. Then your design will be available under the **User setting**
![image](https://user-images.githubusercontent.com/10247582/64534722-a0b1d780-d31e-11e9-8e96-32619d9e2e57.png)
Also you could observe your design numerically using **Measure corner**.. Pressing it will printout the design parameters for masters to be edited.... and finally if you find yourself even more adventurous, you could SHIFT+Click the **Measure corner** - this will spill out a Python dictionary object, that you might want to hard code into the tool, by copy/pasting it under some text editor, to the presets...
![image](https://user-images.githubusercontent.com/10247582/64534893-fb4b3380-d31e-11e9-99fa-6446b5a52f64.png)

**Comment by kateliev** [comment]
Note: you will be probably wanting to upgrade TR to the latest version...

**Comment by tphinney** [comment]
I have been playing with this for quite a while today.

FREAKIN’ AWESOME. I love the softer look in the Light  and Light-ish weights. Where before they were the most angular, they are now intriguing in new ways.

Thanks to @kateliev both for the initial suggestion, and scripting the changeover to make it easier for us!

I see a couple of issues:
1) tail of /j and /g definitely need the :Lt curving.
2) /m is having problems at inside top right. It may just be a misplaced start point in some masters. I'll try fixing that right now.

**Comment by tphinney** [comment]
Seeing it in full context, finally, after more consideration, besides a couple of omissions/bugs, is the curvature maybe just a little too much, in the caps in particular? Perhaps it should be about 75–85% as much of the height/width? Leaving lowercase as-is.

This would be just the :Lt and :LtExp masters, I think? The :LtCnd has a bit less curve already. I will check and confirm.

(That would be entirely my fault, as it is modeled on what I did manually for the /O.)

This is not a STRONG thought on my part, the further tweak. Perhaps just a reaction to how radical a change it is! 🤔🤯 Generally, it is a great thing.

**Comment by tphinney** [comment]
After discussion in group chat, I am OK with the new curvature as is (as I set it in the first place). @servantb  in particular was influential in halting my further second-guessing myself.

**Comment by kateliev** [comment]
Ok, I consider this done, after everybody is satisfied with the new curvature.
