### ISSUE TITLE
Increase ascenders in Black weight masters by 24u

### ISSUE THREAD

**Issue by servantb** [tphinney/science-gothic#105]
Increase height of lowercase ascenders by 24u to match relative length of descenders given the increased x-height in the Blk weights. (See issue #40.)

Raise ascender guide/zone height for Blk masters by 24u.

Raise top anchors of affected glyphs by 24u.

**Comment by tphinney** [comment]
Largely done. Leaving to @servantb to determine what to do with dots on /i and /j. I suggest that *some* (and maybe all?) of the increase be used to increase distance of dot from stem. Could split it up and also use some of the space to increase the vertical thickness of the dots.

I will decide what impact to have on the /eth — probably will raise the ascender stroke to the new overshoot height.

**Comment by tphinney** [comment]
See #110 for remaining bit.
