### ISSUE TITLE
Change code and name of 'CNTR' (Contrast) axis to 'YOPQ' (Y Opaque)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#111]
(UPDATE: Mostly done, except some question about the friendly long text name "Y Opaque")

See: https://variationsguide.typenetwork.com/proposal/

This will be relatively transparent in the font, BUT it may affect scripts as well.

@kateliev will you need to revise scripts as part of this change?

**Comment by kateliev** [comment]
Yes the scripts will need re-coding - i will do it as soon as you execute the change...

...but... I understand that this is the proper name for the axis, but so not see any significant improvement for us changing the names of the masters - this _yopq_ tag is ridiculous...

**Comment by tphinney** [comment]
I totally agree that it has zero, near-term, practical helpful impact.

But, some day, there may be more fonts out there with a contrast axis coded as 'yopq' (per David Berlow’s approach and proposal). In such a universe, we might be able to have some degree of interoperability between fonts-with-contrast by using the same tag.

It also affects the axis _range_—what numeric user values we set as the highest and lowest representations. Basically we can use the range for the thickness of the caps, in 1/1000ths of an em. So, since the thin cap horizontals are 36/2000, the minimum will be 18. 

Max would be... variable depending on the weight. 
- :Lt = 18
- :Medium = 122
- :Blk = 242. 

Not sure what that means for the axis values—obviously need to use either the :Medium or the :Blk, as otherwise there is no variation.

**Comment by tphinney** [comment]
This is mine to sort out until I determine what values to use on the revised axis. Then it will be work for both me and @kateliev

**Comment by dberlow** [comment]
Hey Thomas,

The y stem value, yopq, is the one major value the font format didn’t have before, and in general is one of the two values involved in stem contrast among horizontal, vertical and diagonal stems, which then relate somehow to the round y and x stems. So yopq and xopq are sample values from whatever detailed a framework of stem weights a font has, and you’ve harnessed to vars.

As a single slider to the user, the expectation is that change in one direction makes a group of stems heavier, and in the other direction lighter. With this, the user can “fish” about for a contrast other than the default. 

If you are not planning on having an xopq axis, then I think the best values for this, in consideration of the implantation that only allows one set of values, are -1,0,1. That has the user doing any calculations they need on 100-400-900 wght, and -1,0,1 for contrast change. And that’s a consistent UI over the whole design space, regardless of how much change or none at all is going on.

A step up in programmability, would be to use the per mill of the default and its min and max as the values for yopq, add xopq in per mill and and those values can be programmed against each other, to the 1/1000th, and to graphics or any other dimension on the page, especially in print.

This value system is obviously a little fuzzy now, as the ot1.8 implementation is rather un-typographic on values, but it can be .js assisted now, avar2 will fix it, and contrast of x and y, diagonals, rounds and etc. to the upm is something the type designer tracks thoroughly in a variable font anyway.

One can add xopq without much work, by copying and renaming the weight axis to xopq, changing the values from os/2 to per mill, and presto. It’s not strictly an xopq, but for development and possible blending, it would be good to know the main stem weight, per mill.

For use in envisioning and/or making an optical size axis, a square sans typically only needs ytlc, xopq, yopq and xtra, I believe. So whether you go to more axes or not, the more information and variation you have given the user in those 4 axes, the better, imho.

Cheers, David

**Comment by tphinney** [comment]
Hey @dberlow, thanks for dropping by and commenting!

So, in this case, if we want the default and "normal" to be the low-contrast version, do we make that 0, and the high-contrast -1 because less thickness is "negative" and zero should be the default?

**Comment by dberlow** [comment]
The default has to be zero, or  once the user fiddles with it, they for get what it was?Yes, the direction of the value, and the word for what happens, are opposite.

On Oct 4, 2019, at 6:12 PM, Thomas Phinney <notifications@github.com> wrote:

Hey @dberlow, thanks for dropping by and commenting!

So, in this case, if we want the default and "normal" to be the low-contrast version, do we make that 0, and the high-contrast -1 because less thickness is "negative" and zero should be the default?

**Comment by tphinney** [comment]
OK, so now I know that the axis range will be 0 (zero) to -1, with zero being "normal" and -1 being the thin horizontals.

And the four-letter axis tag is 'YOPQ' (caps as it is not yet an official OpenType registered tag).

BUT, I still need the official/exact wording for the "long" axis label, including capitalization. Is it "Y Opaque" or "Y opaque" or something else?

**Comment by tphinney** [comment]
@davelab6 ?

**Comment by tphinney** [comment]
@kateliev Your scripts don't depend on the long, friendly name, anyway, correct? So if that changes at some later date, it won’t break anything. If that’s right, please prepare an update to our internal scripts that assumes the new axis tag and range.

In parallel, I will do a test build that uses the new axis config.

**Comment by tphinney** [comment]
I have changed the long name to "Y Opaque" and the code to "YOPQ"

I have not yet changed the scale, because FontLab doesn’t like a user scale with an end point below 100 (!). I can make the design scale go from 0 to -1 no problem. But not the user scale.

It occurs to me that there is a potential issue with having the _end-user_ scale be 0 to -1. Some user interfaces might only allow whole numbers for axis settings. Or even, only positive numbers. Or heaven help us, only positive integers. That would be a spot of bother for a scale running from 0 to -1. So I am inclined to go with @dberlow 's alternative suggestion of using the actual per mille values from the :Medium (default master).

**Comment by tphinney** [comment]
Yeah, I did that. Besides that I can make it work now, and it allays my concerns about app support, it just “feels better” than an axis going from 0 to -1.

36 to 244 it is! With 244 as the default.

**Comment by tphinney** [comment]
Erm, 18 to 122, like I said.  ;P
(Caught my mistake just before I pushed to the repo.)

**Comment by tphinney** [comment]
This is done, EXCEPT we still do not have any confirmation on the "long name"
Currently, it is "Y Opaque"
However, it can be easily changed at any time, and won’t "break" many (if any?) things to change it.
