### ISSUE TITLE
Define web site needs

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#116]

**Comment by servantb** [comment]
Some ideas:

1. Define the brief (briefly) including historic reference, glyph set, intended use, axes, and other definitions of scope (OpenType features? ligatures?)
2. Show off extremes (either static or animated)
3. Playground space to test current build?
4. Proposed release date
5. Team bios

**Comment by tphinney** [comment]
PURPOSE: The purpose of the site is primarily to promote the typeface and its utility as a Google font (so: web focus), both in general and as a variable font. Say/show what kinds of uses it has. A slider interface to play with it (think: a “light” version of Axis Praxis) would be good.

SCOPE: Mostly a single page web site. A couple of small side pages (About the team, Bank Gothic and Science Gothic history) would be good.

STAGES: A first stage (version 1) of the web site is already funded. Funding for a second stage (version 2) seems likely, but not guaranteed.

TIMELINE: November for version 1. Perhaps December or January completion for version 2.

**Comment by tphinney** [comment]
Started drafting some content for the web site, here: https://docs.google.com/document/d/1VvwjRzsXsW2tOclSGwJPZ5ty93-qxCe0Bk0P_I60P-U/edit?usp=sharing

**Comment by tphinney** [comment]
UPDATE! I have drafted a job description that I would like to make public no later than Monday.
https://docs.google.com/document/d/1vV0J4J8PP_YksWE99hbyTEKJAUf2x6v1iYlBo9w0aHs/edit?usp=sharing
