### ISSUE TITLE
Lost Font metrics

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#118]
Font has lost per master font metrics. This is a typical FL bug since the dawn of time.
Now x_height is equal in all masters (1000u)
![image](https://user-images.githubusercontent.com/10247582/64691080-88ff5e00-d49a-11e9-965b-6dd0a6277841.png)

**Comment by kateliev** [comment]
I have fixed it now, but @tphinney re-review the settings.

For your information, there are several ways to fix the bug using TypeRig, the quickest being Metrics Panel > Font: Set Font Metrics. Select a node that should reside on the x_height and press "Selection" and "x height" this will align the x height per master on the selected node Y coordinate (per master)
![image](https://user-images.githubusercontent.com/10247582/64691514-7d606700-d49b-11e9-8719-dea4bc46cafa.png)

**Comment by kateliev** [comment]
The other way is using TR Manager > Metrics Panel. It allows storing the font metrics, zones and etc to external files and restoring them if needed.
![image](https://user-images.githubusercontent.com/10247582/64691660-e9db6600-d49b-11e9-96f3-918f415934b7.png)

Losing Font metrics and Font zones are ancient bugs... but they still manifest

**Comment by tphinney** [comment]
I imagine you have gone to bed! Otherwise I'd ask you to do that restoration, this time.

**Comment by tphinney** [comment]
Vassil caught the :Blk masters x-height change, but need to check the :Blk masters ascenders are still 1472

**Comment by tphinney** [comment]
They were and are.
