### ISSUE TITLE
/B, /P, /R Curves and redesign

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#119]
I have fixed the following on /B, /P, /R

- **New curves (as requested)**: /B, /P, /R, plus fixing where necessary for /B

- **Widths**: /B - some layers especially :Black, :Expanded were significantly wider then they needed to be
- **Stroke thickness**: /B, /P, /R / - the curved bow part was thinner in than the straight in all :Black layers
- **Optical compensation**: /R and in some minor places /B (but kept Igor's original bottom blacker design)
- **Bow height and leg weight**: /R

This all lead to fix-ups in /uni0411, /uni042A, /uni042B, /uni042C, /uni042F, /uni0420

Please review the new designs and tweak them further if needed..

**Comment by servantb** [comment]
These look good. Thanks, @kateliev
