### ISSUE TITLE
variations problems in browser (but not FontLab)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#120]
We are seeing some problems with a built variable font in Chrome Mac on the Axis-Praxis site, but not present in FontLab. This was done with Brandon’s submission of last night, and building a variable font from it:

Font File:
[https://app.zenhub.com/files/196286415/ccb6dd78-6d02-4c40-ba5f-03673512b63f/download](https://app.zenhub.com/files/196286415/ccb6dd78-6d02-4c40-ba5f-03673512b63f/download)

- /R diagonal detaches (I think it was in the :Lt weight along the width axis)
- /N diagonals disappear on :Lt weight with no contrast along the width axis
- ? Other diagonals problematic in interpolation in the :Lt along width axis

**Comment by servantb** [comment]
If possible, it may be even worse in Adobe Illustrator:
https://recordit.co/lUkEcHZEYJ

**Comment by tphinney** [comment]
Ah, but luckily, that particular glitching is not our problem! At least, 90% of it is definitely the Adobe variations-support bug at work:
https://github.com/tphinney/science-gothic/issues/107

Of course, it is irksome, because it is hard to tell how much is Adobe, vs actual font bugs. Sigh.

**Comment by tphinney** [comment]
As discussed in chat, I discovered that these and other problems were due to a misconfiguration of the design vs user coordinates axis map for weight. As constructed in FontLab, it became orthogonal to the user space pretty early on, and it turns out this caused all sorts of strange trouble.
