### ISSUE TITLE
/uni20AD kip currency needs work

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#122]
Not working well, especially in the bolder weights. Could stop the crossbar weight at the weight in the :Medium — use the same weight for the (non-contrast) :Blk styles.

**Comment by tphinney** [comment]
Fixes made

**Comment by servantb** [comment]
Might need to edit this based on issue #191

**Comment by tphinney** [comment]
Definitely. Also, the kip still has overlapping paths! Will review after the /K is finished.

**Comment by tphinney** [comment]
/K is done, so this is unblocked.

**Comment by tphinney** [comment]
Wow. Making this work without overlap would take some MAJOR redesign. It is _possible_, but the :CtrEtc masters would become pretty weird.

**Comment by tphinney** [comment]
I'm going to leave in the overlap. It's the best option available.
