### ISSUE TITLE
/oslash is missing slash in two masters

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#123]

**Comment by servantb** [comment]
Some notes:
- :LtCtr has no master
- :Blk slash is too thin
- :BlkCnd slash is too thick
- :BlkCtr has offset /o element
- :Ctr, :BlkCtr, :CndCtr, and :BlkCndCtr need optical compensation (like offset for /x)
- :LtExp, :LtExpCtr and :ExpCtr have a different terminal on the slash that shouldn't be there
- :ExpCtr slash is shifted up vertically

I can work on these today. This booger was originally mine and I dropped the ball on it.
