### ISSUE TITLE
/p /b /d /q /g /thorn group - stroke thickness & design

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#124]
The /p /b /d /q /g group has abnormal stroke with in the :Blk Exp master. As all other masters have the same stroke width on bow and stem, only :Blk Exp has less thickness (-100u) in the bow.

**Correct** :Blk (524/524):
![image](https://user-images.githubusercontent.com/10247582/64767288-1d77c800-d550-11e9-8271-e84ccf8f23cc.png)

**Incorrect** :Blk Exp (424/524):
![image](https://user-images.githubusercontent.com/10247582/64767426-5dd74600-d550-11e9-9006-21b179bd813f.png)

Also i am bit worried about the construction of /g. In :Blacks the aperture below the bow is too narrow for my taste. The bow could go a bit higher, as by definition on most faces it is allowed for the bow to not sit on the baseline if there is not enough room below.

I would lift up the part shown in green in all :Blk masters
![image](https://user-images.githubusercontent.com/10247582/64767675-c0c8dd00-d550-11e9-9505-54a9ec314356.png)

**Comment by tphinney** [comment]
Remaining question: the descender vs bowl of /g
Although I am concerned about a possible “slightly off” appearance in the interpolation between :Medium and :BlkEtc, it is easy enough to just try it, and reverse the change if it is problematic. So, I will do that.

**Comment by tphinney** [comment]
I fixed the widths, and the bowl of /g
BUT, I did not yet address the question of horizontal stroke weight.

**Comment by servantb** [comment]
Horizontals on /g look good. See issue #100 
I'm calling this one. Well done, folks.
