### ISSUE TITLE
Finish lowercase /w

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#126]
If Igor doesn't get to this very soon, I will do it.
previously part of #55

**Comment by tphinney** [comment]
Went ahead and started to finish the /w that Igor had started.

**Comment by servantb** [comment]
The :Blk and :BlkCnd still aren't my favorite, but I can't see a better way around, and I think they work for our purposes without spending unnecessary amounts of time on them at this point.
I'm calling this done. Thanks, @tphinney.
