### ISSUE TITLE
Tighten the spacing!

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#127]
At least in substantial parts of the design space, the current spacing is too loose. The black condensed might be a tad tight, and some other Cnd styles may be ok, but the other masters... mostly WAY too loose.

This will have global impact, so best done on a weekend or at times when others are not editing.

**Comment by tphinney** [comment]
OK, here's the summary of what changed, per master (also in commit notes):

:Lt much tighter (H=250, -35)
:Medium tighter (H=180, -20)
:Blk slightly tighter (H=170, -10)
:LtCnd looser (H=120, +25)
:Cnd very slightly looser (H=80, +8)
:BlkCnd slightly looser (H=90, +10)
:LtExp tighter (H=330, -20)
:Exp tighter (H=300, -20)
:BlkExp much tighter (H=320, -40)
:LtCtr much tighter (H=250, -35)
:Ctr slightly tighter (H=210, -10)
:BlkCtr slightly tighter (H=185, -15)
:LtCndCtr looser (H=120, +25)
:CndCtr slightly tighter (H=112, -12)
:BlkCndCtr slightly looser (H=110, +22)
:LtExpCtr tighter (H=330, -20)
:ExpCtr much tighter (H=340, -60)
:BlkExpCtr much tighter (H=350, -50)

**Comment by servantb** [comment]
Perhaps this is a side note, as it's a glyph edit and not exactly spacing, but I noticed the /space glyph in :LtCnd, :LtExp, :LtCtr, :LtCndCtr, and :LtExpCtr is too thin.

**Comment by tphinney** [comment]
/space lots looser (+30) in :LtCnd :LtExp :LtExpCtr ; (+40) LtCtr ; (+50) LtCndCtr
/space slightly tighter (-5) in /Medium

**Comment by tphinney** [comment]
BTW, across all masters, the average change in glyph spacing (before additional changes to the /space character above) was about -15 tighter.

**Comment by tphinney** [comment]
I'm finding some of the Extended styles still a bit loose.  :/

**Comment by tphinney** [comment]
Remaining problems covered in #141
