### ISSUE TITLE
/eng uni014B missing

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#129]
/eng (uni014B) is missing from SG encoding

**Comment by tphinney** [comment]
I don’t think it was missing, just not actually part of the needed character set for Latin.
If we did include Latin eng (uni014B), we would probably need the cap as well (uni014A Eng).

Among the more clearly defined (compared to Google’s) Latin character sets I am familiar with, eng/Eng is not included in Adobe Latin 4 (~620 glyphs, without small caps). It is included in Adobe Latin 5 (~1122 glyphs, without small caps). So, it is not surprising to me that it was not covered.
