### ISSUE TITLE
Write/update/record "master guidelines"

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#13]
We need to record relationships between the masters and write up some guidelines/explanations
At least some of this will benefit from being in a spreadsheet
https://docs.google.com/document/d/10PCpLwAJARauD_fLfSsdtAwzNGjijtJvYqTRA1-8x6g/edit?usp=sharing

**Comment by servantb** [comment]
Finished writing this up as a Google Doc, and shared it with the team. Thomas can edit.

Tried to keep it clear, concise, and simple. No need to go granular if we don't have to. If you want a spreadsheet with my data, I can get that to you.

Contains relevant relationships between masters: weight and width proportions, where to add weight, and corner proportions.

**Comment by kateliev** [comment]
You can examine some relationships between masters easily using TypeRig Statistics panel.

**Comment by servantb** [comment]
Addressed some of Thomas' comments in the document.
Added visuals for clarification.

**Comment by tphinney** [comment]
Aha! Funny, your use of "%" was not even one of the ways I was thinking of.  :P 
Thanks, this is clear and very good.  :)
