### ISSUE TITLE
/uni0409

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#130]
Please take your time to review the construction of /uni0409. 
As the /AE glyph is not still finished, I did nod found a suitable solution to follow....

I consider the matter important because I believe that /uni0409, /AE, /uni04D4 as well as the respected .smcp versions (plus /uni0459) are all connected and should share the same structural solution.

So here are two possible solutions that I have added to the font:
This solution is the simplest one and more in tune with the overall glyph design in SG, but has the drawback of being unbalanced and has a big white "gap" in front.

Original :Lt, :Medium, :Blk
![image](https://user-images.githubusercontent.com/10247582/65014329-04dc2900-d927-11e9-83e3-e7b8a37e8007.png)

Original :LtCtr, :MediumCtr, :BlkCtr
![image](https://user-images.githubusercontent.com/10247582/65014391-410f8980-d927-11e9-9027-33f3fcfdb642.png)

This is a solution I have seen used a lot and also used by the Cyrillic of Bank Gothic by Paratype.
Alternates :Lt, :Medium, :Blk
![image](https://user-images.githubusercontent.com/10247582/65014210-897a7780-d926-11e9-93ff-a3483d62b71b.png)

Alternates :LtCtr, :MediumCtr, :BlkCtr
![image](https://user-images.githubusercontent.com/10247582/65014233-a6af4600-d926-11e9-8128-3d58aef9e929.png)

**Comment by tphinney** [comment]
Doesn't the second approach also imply a non-triangular shape for “el” and “de” and other related shapes? Л л Д д and so on

**Comment by tphinney** [comment]
Or did you just mean that for the alternate for other languages

**Comment by kateliev** [comment]
No this is not an alternate! I have just submitted it as an alternate variant in the font to choose from.
Here is the Paratype triad:
![image](https://user-images.githubusercontent.com/10247582/65015238-99478b00-d929-11e9-832f-75fabbc4ffbf.png)

**Comment by kateliev** [comment]
Here is the Adobe triad:
![image](https://user-images.githubusercontent.com/10247582/65015322-e1ff4400-d929-11e9-99b5-9233aa223855.png)

**Comment by kateliev** [comment]
> Doesn't the second approach also imply a non-triangular shape for “el” and “de” and other related shapes? Л л Д д and so on

Non triangular solution is out of the question for me for this project. It will be way more easier for me to make the Cyrillic, but I consider it is so out-of-style for this particular project.

**Comment by tphinney** [comment]
I just figured out my misunderstanding. No worries.

So, the ParaType approach goes from the "box el" to the "triangular el" (part of the glyph) in the same typeface, as weight increases, in the non-Contrast masters. Hmmm. That's pretty clever. And I see why you think it might affect the /AE

**Comment by tphinney** [comment]
/AE was something Igor was working on, so adding him.

**Comment by tphinney** [comment]
Just to be clear, I am fine with the proposed solution. That's what's currently in the font, right? So can we close this?

**Comment by kateliev** [comment]
Yes!
