### ISSUE TITLE
/Y off-center

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#132]
The cup of /Y is wildly off-center, please revisit the design. I have dropped a guideline showing the BBoX Center, please see how it compares to the vertical stem, that should be in the center of the composition - this indicates for me that the diagonals of the cup are protruding from the center of the stem with different values.
![image](https://user-images.githubusercontent.com/10247582/65410196-681bfe80-ddf2-11e9-863f-be63dd9caec4.png)
![image](https://user-images.githubusercontent.com/10247582/65410210-6f430c80-ddf2-11e9-83ff-1165b52af2f3.png)
![image](https://user-images.githubusercontent.com/10247582/65410230-79fda180-ddf2-11e9-9a52-acda0fc5eb98.png)
![image](https://user-images.githubusercontent.com/10247582/65410266-8eda3500-ddf2-11e9-83d5-ac3ff73afc3d.png)

While this can be optically plausible, numerically the sides of the Y should be equal.

**Comment by kateliev** [comment]
Also at /Y :Blk the diagonals need a bit of touch-up so they do not appear widening at the bottom
![image](https://user-images.githubusercontent.com/10247582/65410414-f7c1ad00-ddf2-11e9-87bd-4519d2bc94c3.png)
![image](https://user-images.githubusercontent.com/10247582/65410446-0d36d700-ddf3-11e9-9c1b-bcf762515fff.png)

**Comment by tphinney** [comment]
Agreed on all of these errors/glitches. I will tackle these fixes. Thank you!

**Comment by tphinney** [comment]
Well... the thin masters were easy to adjust. The heavier and especially the high-contrast weights are more problematic.

If the two diagonals have different weights, and sidebearings are equal on both sides, then one (or more) of the following MUST be true about the left and right diagonals, relative to each other:
1) They will meet the center stem at very different heights
2) They will be at very different angles
3) The visual center of the glyph will be noticeably off from half the advance width

I am willing to compromise a little bit on 1. A *very* little bit on 2. But past that, for me, (3) has to give.

Anyway, I have done a first pass, which I will submit tonight. I am not sure it addresses all of @kateliev 's concerns. Vassil, can you take a look?

Afterwards, perhaps @servantb can then take a look at it next and decide what more to do, if anything

**Comment by kateliev** [comment]
This is not good....
![image](https://user-images.githubusercontent.com/10247582/65664036-1321f780-e041-11e9-8e1e-2d3e9db8ddfe.png)

**Comment by servantb** [comment]
The /Y stem would be off center because of the difference in stroke widths, so that is as it should be.

However, You're right about the :Ctr — that needs work. I'll get on it.
Thanks.

**Comment by kateliev** [comment]
The off-center is kind of acceptable within 5 units of difference on a 1000 upm font, lets make it a "generous" 10u in our case (not advisable but tolerable). But i cannot agree on more than that, or the fact of having different whitespaces left or right of the glyph - having different LSB RSB on a "symmetrical" glyph is too much for my poor brain....

**Comment by kateliev** [comment]
@servantb and @tphinney I have uploaded a new "centered" design of /Y - called /Y.new. Please review it! I have also lifted the waist a bit in /CndCtr masters.

**Comment by servantb** [comment]
So I think the problem with this approach is that it doesn't take into consideration the optical balance. The thin stroke on the right leaves so much white space around it compared to the thick stroke on the left, that when it's mathematically centered it ends up looking like it's too far to the left (too much white space on the right).

The top rows of each phrase or set of letters use the current /Y, the bottom rows use /Y.new:

![image](https://user-images.githubusercontent.com/50463501/68411439-580c7400-013f-11ea-8f9e-d6e9f9078e3d.png)
![image](https://user-images.githubusercontent.com/50463501/68411464-5fcc1880-013f-11ea-81dd-bd9d563d7652.png)
![image](https://user-images.githubusercontent.com/50463501/68411496-6e1a3480-013f-11ea-8b47-bc800c1044d7.png)
![image](https://user-images.githubusercontent.com/50463501/68411521-72dee880-013f-11ea-95ba-e0d3efba9c59.png)


However, I think what you've done with the :CndCtrEtc masters, increasing the waist, works brilliantly. I'll incorporate those masters into the /Y and /y.smcp – Thank you!

![image](https://user-images.githubusercontent.com/50463501/68411615-9e61d300-013f-11ea-89e4-541e78ade402.png)
![image](https://user-images.githubusercontent.com/50463501/68411621-a28df080-013f-11ea-99bb-f2b87b73559b.png)

**Comment by tphinney** [comment]
Agreed that the join on the :CtrEtc masters was WAY too low! It could arguably even be a little higher still, but in any case, this is a major improvement.

On the other: being mathematically centered and having precisely equal angles are NOT design objectives for the /Y; it just is not how this letter works. Master type designers do not do it, and their typefaces look pretty good. They also have contrast in stroke thickness even in "no contrast" designs.

See this thread, starting Nov. 5, where Nick Shinn comments not only that he has observed this in his own work, but found it pretty consistently in the work of others: https://typedrawers.com/discussion/2998/typedesign-and-science-or-look-at-what-i-made/p3

And look at Acumin, a recent “no contrast” neo-grotesque typeface from Robert Slimbach:
<img width="669" alt="Acumin Y" src="https://user-images.githubusercontent.com/6548266/68419964-1fc16180-0150-11ea-89ae-f0893e37400a.png">

Or Lucida by Bigelow & Holmes:
<img width="652" alt="Lucida Grande Y" src="https://user-images.githubusercontent.com/6548266/68419965-1fc16180-0150-11ea-9472-b92af0cd6fe9.png">

**Comment by kateliev** [comment]
Ok... point taken! It seems that I am clearly missing something here!

> So I think the problem with this approach is that it doesn't take into consideration the optical balance. The thin stroke on the right leaves so much white space around it compared to the thick stroke on the left, that when it's mathematically centered it ends up looking like it's too far to the left (too much white space on the right).

Yes, @tphinney and @servantb , I really get your point of view, but do you mine? So to explain further I will share with you my thoughts on why this is problematic, excluding the subjective idea that "it does not look good enough for me". As I tend to be more "practical" then "artistic" :
- it is unpractical to have geometrically unbalanced shape that should "work" with the other shapes in a typeface. As a rule of the thumb the "beauty" of the individual glyph is of no importance compared to the fact that all shapes in a typeface should "work" together nicely. 
- rhythm is more important than individual geometry so everything that disturbs the rhythmic stem flow of the typeface is major issue (at least for me). You have one big heavy stem supporting two others, but the white space left is so big that it is very noticeable when the big central pillar is off to the left or right. So for the overall rythm, the "arms" are no that much of importance compared to the central beam supporting them.
- to compensate the above one has to have different metrics to the left and right  _(very unpractical)_
- to compensate interactions with other glyphs one might be forced to kern differently to the left and right _(also very unpractical)_
- to make the above work, one might be forced to have different kern classes - for a "theoretically symmetrical" glyph that has no design exceptions (to clarify exceptions: you might have A_left A_right just because /AE, although /A is "symmetrical" ...) _(also very unpractical)_

... i hope you see where this is going - to "save" a particular design decision - one has to sacrifice a lot more to just make it work - then one should ask himself - is it really worth it - well you know my opinion... complicating things that should be "simple" usually leads to errors....

> On the other: being mathematically centered and having precisely equal angles are NOT design objectives for the /Y; it just is not how this letter works. Master type designers do not do it, and their typefaces look pretty good. They also have contrast in stroke thickness even in "no contrast" designs.

I always loved good examples, so I have learned something new today - I should really look at the works of others more often and try to accumulate as much knowledge as I can! So i decided to make a little experiment and just collect different /Y shapes superficially scanning my Adobe library (as there are more master type designers represented).

![image](https://user-images.githubusercontent.com/10247582/68463525-83629200-0217-11ea-8f7c-e3c86f2dd3c9.png)

The premise is simple - there is a guide 50% of the BBox and a node 50% of the stem width...
![image](https://user-images.githubusercontent.com/10247582/68463754-0a176f00-0218-11ea-8b5f-a90f2846f931.png)

I am uploading the file to share the knowledge:
[TheYfont.zip](https://github.com/tphinney/science-gothic/files/3823760/TheYfont.zip)

So my finds were surprising and lead to the following conclusions:
1. most typefaces are not compensated for the optical balance @servantb is talking about.
2. those that are compensated are usually off by maximum 5u on 1000 UPM
3. those that are compensated have different metrics left and right of the shape
4. most compensations occur left of the geometrical center towards the heavier stem 

... and questions:
- on (1): for me this is clear indicator that my line of thought makes more sense - practical is best?
- on (2): lets assume we keep the idea of compensation - why do we compensate by up to 50u on :CtrEtc masters
- on(3): lets assume the "masters" know what they are doing and having different metrics reflecting the compensation is the norm - why don't we?
- on(4): This is pretty normal for me, as I would aesthetically and mathematically compensate in that direction as the center of gravity/mass resides there (center of gravity/mass is different then the geometric center and very close to the optical one). So why do we compensate in the other direction? 

I will close the issue as I have wasted enough time on that... it is up to you both :)

PS: you both make "mathematical" sound somewhat dirty...
