### ISSUE TITLE
/guilsinglleft & other guillemots look awful in :Ctr masters

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#133]
In the high-contrast masters, the guillemots look awful. I made them, but I think they suck. I should revisit these, unless somebody else wants to.

These are needed for French, and sometimes German.

I have started some experiments. Nothing too exciting so far, although I think at least one and possibly both are improvements.

**Comment by tphinney** [comment]
I changed this to not do anything for the high-contrast versions. It may not be ideal, but it is certainly better.

**Comment by servantb** [comment]
Not seeing any contrast in the guillemots in the :CtrEtc masters in the file that was in the repo today (Oct 1, 2019).

**Comment by tphinney** [comment]
Right—that's what I was saying above. But as we discussed in chat this morning, I think there are some other possibilities. I'm focused on small caps now, but I will get back to this.

**Comment by tphinney** [comment]
I have made a first pass at revising the guillemets, based on an earlier experiment. The shape is much improved in the contrast masters, I think.
