### ISSUE TITLE
Lowercase /a stem values

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#134]
I might be missing something, but lowercase /a stems very with no apparent logic. I presume it might be compensated, but nevertheless..
:Blk Cnd Ctr
![image](https://user-images.githubusercontent.com/10247582/65690743-5b104100-e078-11e9-96ab-d16be8a59f01.png)
:Cnd Ctr
![image](https://user-images.githubusercontent.com/10247582/65690785-71b69800-e078-11e9-948e-0a9702bcae61.png)
:Blk Ctr
![image](https://user-images.githubusercontent.com/10247582/65690811-7bd89680-e078-11e9-9bd7-e4ad1ea3b73c.png)
:Blk Cnd (for reference)
![image](https://user-images.githubusercontent.com/10247582/65690896-9b6fbf00-e078-11e9-9c95-a5030af3eafb.png)
:Cnd
![image](https://user-images.githubusercontent.com/10247582/65690930-a9254480-e078-11e9-99b6-15b98309bf5d.png)
:Cnd Ctr
![image](https://user-images.githubusercontent.com/10247582/65691018-d245d500-e078-11e9-860a-8bffa563889c.png)
... and so on

**Comment by tphinney** [comment]
Fixed for tonight’s check-in.
