### ISSUE TITLE
Small-caps

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#138]
As I am starting to work on the small-caps, I place here some notes values and etc. stuff for keeping....

**Initial guidelines for our first pass** by @servantb 

**Height**
Height: x-height +5%, or 1060 in typical masters with 1000 x-height (1086 in 6 /Blk masters that have 1024 x-height)

**Stem weight**
Stem weight should be that of lowercase + 15% of the difference between lowercase and caps.

**Width**
Small caps are a bit wider than caps. See difference between cap and lowercase for /O, /U, /C. For the Medium /O, it looks like it needs to be about 5% wider, for example. And/or: Try to maintain the same counter width, or 1-2% more?

**Comment by kateliev** [comment]
**Stems as measured**
**UC** _/H (Vertical)_
`'Blk Cnd Ctr': 572.0
'Blk Cnd': 572.0
'Blk Ctr': 572.0
'Blk Exp Ctr': 572.0
'Blk Exp': 572.0
'Cnd Ctr': 264.0
'Cnd': 264.0
'Ctr': 264.0
'Exp Ctr': 264.0
'Exp': 264.0
'Lt Cnd Ctr': 40.0
'Lt Cnd': 40.0
'Lt Ctr': 40.0
'Lt Exp Ctr': 40.0
'Lt Exp': 40.0
'Lt': 40.0
'Medium': 264.0
'Blk': 572.0`

**UC** _/n (vertical)_
`'Blk Cnd Ctr': 524.0
'Blk Cnd': 524.0
'Blk Ctr': 524.0
'Blk Exp Ctr': 524.0
'Blk Exp': 524.0
'Blk': 524.0
'Cnd Ctr': 248.0
'Cnd': 248.0
'Ctr': 248.0
'Exp Ctr': 248.0
'Exp': 248.0
'Lt Cnd Ctr': 36.0
'Lt Cnd': 36.0
'Lt Ctr': 36.0
'Lt Exp Ctr': 36.0
'Lt Exp': 36.0
'Lt': 36.0
'Medium': 248.0`

According to stated above:
**lc + (uc-lc)*0.15**
`'Blk Cnd Ctr': 531.2
'Blk Cnd': 531.2
'Blk Ctr': 531.2
'Blk Exp Ctr': 531.2
'Blk Exp': 531.2
'Blk': 531.2
'Cnd Ctr': 250.4
'Cnd': 250.4
'Ctr': 250.4
'Exp Ctr': 250.4
'Exp': 250.4
'Lt Cnd Ctr': 36.6
'Lt Cnd': 36.6
'Lt Ctr': 36.6
'Lt Exp Ctr': 36.6
'Lt Exp': 36.6
'Lt': 36.6
'Medium': 250.4`

**Comment by kateliev** [comment]
> Width
> Small caps are a bit wider than caps. See difference between cap and lowercase for /O, /U, /C. For the Medium /O, it looks like it needs to be about 5% wider, for example. And/or: Try to maintain the same counter width, or 1-2% more?

Correct me if I am wrong, but I presume that here is an error of expression her... as small-caps cannot be wider than the Upper-case... The original Bank Gothic has small-caps on the lowercase that are definitely not wider than the caps... so I presume this should be read as wider than the lowercase, which is to be expected.

**Comment by kateliev** [comment]
@tphinney , @servantb the initial pass of Lat SMCP is ready. I am leaving the raw output for you to see and to asses the work needed and the problems encountered. Also please review the stroke weights as well as overall width. 

Each resulting glyph is with 80% of its original width. I have put that value blindly trusting on my experience (and in accordance with the following). 

The resulting glyph height is:
- for target height 1060 is 75.71%
- for target height 1086 is 77.57%

**Comment by kateliev** [comment]
@tphinney i have not added any additional zones/guides as this is a _global change_. Please prepare the font or authorize me to do so :)

**Comment by tphinney** [comment]
> > Width
> > Small caps are a bit wider than caps. See difference between cap and lowercase for /O, /U, /C. For the Medium /O, it looks like it needs to be about 5% wider, for example. And/or: Try to maintain the same counter width, or 1-2% more?
> 
> Correct me if I am wrong, but I presume that here is an error of expression here... as small-caps cannot be wider than the Upper-case... The original Bank Gothic has small-caps on the lowercase that are definitely not wider than the caps... so I presume this should be read as wider than the lowercase, which is to be expected.

I think there are two plausible interpretations of what @servantb meant, let’s get his take: 
1) 5% wider than the initial, scaled-down caps
2) 5% wider than the equivalent lowercase (where there is one)

I assume (1), as that is plausible across all cases, and reasonably subject to generalization. (2) is not always applicable, although it could still provide guidance. But also, in interpretation (2) one could also say that the scaled caps are already that wide, or wider....

**Comment by tphinney** [comment]
My main thought: Let's just tweak the first-gen auto small caps, see how wide actually looks right, and then use that....

**Comment by kateliev** [comment]
So 75% height scale +5% gives us 80% width - what i have already presumed

**Comment by tphinney** [comment]
This looks really good! Nice job from both @kateliev and @servantb — Brandon for coming up with the inputs (with some tweaks from me) and Vassil for building them.

Two main thoughts: 

1) *Might* we want to tweak the height _just a little_. Maybe up another 10 units?

2) The other has to do with whether we want to change the degree of condensing (and maybe weight?) for the :BlkCnd and perhaps :BlkCndEtc, because its counters are just too small.

**Comment by servantb** [comment]
I agree it looks really good, @kateliev!

I think the height works well, and I'd leave it as is.

I wonder if perhaps we don't need to do 80% width, but just scale it 75% all around. The addition of weight will add to the width, giving the additional width in comparison with the lowercase.

I think decreasing the weight a bit will be our best bet with the issue in the :BlkCnd and :BlkCndCtr. I expect we'll have to do some serious manual edits in those masters anyway.

**Comment by servantb** [comment]
The 80% width is still a good idea in the :CndEtc masters.

**Comment by kateliev** [comment]
@tphinney @servantb @IgorFreiberger I an sharing this here as an issue related to the latest SmallCaps run. There seems to be a little problem with horizontal stems weights in the :Ctr masters. They have interpolated as being 27u (28 sometimes due rounding issues), but should be 33u. Please pay extra attention while working... The :Lt Cnd masters have some strong interpolation anomalies and problems but that is easily fixed with Copy-Layer script.

![image](https://user-images.githubusercontent.com/10247582/66047779-103b7100-e531-11e9-9f6f-7bc43933621a.png)

**Comment by kateliev** [comment]
Also I have made additional tweaks to /B.smcp /H.smcp /O.smcp and etc.. touched glyphs marked in green.

**Comment by servantb** [comment]
Notes (not extensive, just things I noticed while doing other things):
/b.smcp, /e.smcp, /f.smcp too heavy in horizontals in :Med
/a.smcp too heavy in :Med
/c.smcp :BlkExp counter needs opening up (52u taller)
/n.smcp diagonal too thick in :Cnd master
/b.smcp :Exp to heavy

**Comment by servantb** [comment]
@kateliev Is it possible to run the smcp generation script again for just the /v.smcp?
We made significant changes to the /V and would rather not have to do all the same fixes for /v.smcp if it can be helped.

**Comment by tphinney** [comment]
We could combine it with a small set of other characters needing small caps:
/germandbls.smcp
/ae.smcp
/oe.smcp
/exclam.smcp
/question.smcp

But also, should wait until we review my question about :BlkExp horizontal thicknesses. I made and uploaded a test font, but did not file an issue. I will do so.

**Comment by servantb** [comment]
Yeah. Also doing a more thorough look, the /b.smcp, /e.smcp, /f.smcp, /p.smcp, /r.smcp, /s.smcp, and /t.smcp all have horizontals that are too thick in the :Med and :Exp, and to a lesser extent (because of proportion) the :Cnd.

**Comment by kateliev** [comment]
Numerically as well as logically the discussed /b.smcp /t.smcp and etc are in every way perfect!?
Meaning that if the UC has the following drawing logic for example:
_if /O = 264/244 (V/H stem) and /B = 264/244 (V/H stem)
so /o.smcp = 250/227 and /b.smcp = 250/227 and etc._ 

I further tweaked the designs by hand following the above rules. So as far as logical consistency goes I am totally OK with their current look... but as far as aesthetics... yes they look a bit blacker but I am not worried... 
...so my advice. Make me a /o.smcp /h.smcp /b.smcp and /e.smcp up top your taste and I will propagate the changes in my designs and you in yours (_again by hand_) as there is no use starting from ground zero. And then I will take the new stem values for future Delta Machine processing as there are glyphs waiting on the queue.
