### ISSUE TITLE
Add blue zones for descender overshoot

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#14]
Brandon has kindly implemented overshoot, but the blue zones need to be added in the font to reflect it.

EDIT: Done, except descenders need it too.

**Comment by servantb** [comment]
We'll call this good. We're not actually using descender overshoots, so I think this is fine.
I'm okay to close this if you are.

**Comment by tphinney** [comment]
Right. These probably won’t get used, but I am glad we have them just in case.
