### ISSUE TITLE
Comma needs to be more distinct in :LtEtc styles

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#142]
I am finding that the comma is not distinct from the period, in lighter weights. I think it needs a bigger “flick” or descender element.

This screen shot shows the lack of differentiation at 40 retina px.

![Screen Shot 2019-10-04 at 8.14.36 AM.png](https://images.zenhubusercontent.com/55f8a29e4f7a08fbb7f4ebd1/30832370-2247-4eec-a31d-c28b1dbeef2d)

**Comment by servantb** [comment]
I already did this, but it looks like we lost my edits.
The comma is measuring 74u wide, and should be 94u wide. Likewise, i dramatically increased the tail length in the :LtEtc.
I'll see if I can find the edited version and restore it.

**Comment by tphinney** [comment]
This was done. Much improved, thanks!
