### ISSUE TITLE
Figures review

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#144]
Starting this issue as discussed with @tphinney .

Here are my notes concerning the figures and my suggestions for fix-ups as well as alternate designs. Except the noted below i find the others perfectly fine:

**/two**:  Has several problems that I would like to address and before that I want to clarify that I am perfectly aware that the design is based on Bank Gothic (BG) as well as the :Medium weight is faithful representation of the original. As well as BG is considered a work of a true master, this does not render it immune to problems - for me /two suffers from some poor design decisions that I would love to see fixed.

![image](https://user-images.githubusercontent.com/10247582/66301282-7f351300-e8ff-11e9-959e-312bb1d72789.png)

- _softening of the tail_ - I find this a particularly bad decision - it enforces a "weak" posture as it creates visual instability, like the /two is going to "tumble backwards". I would solve it the same way as in /seven. Besides solving the above problem, this will create a reference to the way /seven is formed thus enforcing visual unity. _Here is a something to think about -  why the "unity design problem" was not solved the other way around - having a /seven with soft angle there as in /three and /two. It would have created a stronger bond, but have made a "weaker" seven so why leave the /two in such condition_

![image](https://user-images.githubusercontent.com/10247582/66301897-ae984f80-e900-11e9-9e21-acc2fcfbd3b6.png)

- _tail too short_ - I would move the tail a bit backwards just enough to create more stability and a bit bigger aperture below the spine as i find the current solution unbalanced. The problem is especially prominent in the :Blacks.
![image](https://user-images.githubusercontent.com/10247582/66302328-6b8aac00-e901-11e9-969e-88982ff405cf.png)

![image](https://user-images.githubusercontent.com/10247582/66302582-dc31c880-e901-11e9-8b5e-31f21cf557b5.png)
- _gain in the baseline_ - This is on us, nothing to do with BG. It seems that all :Black masters are having the flat bottom part of /two unnecessarily compensated - it is flat = it should sit on the baseline - the same way as /one /four /seven. The top might be compensated (as it is the current design)... but why is it not compensated in /three like in /eight /zero who share similar construction?
![image](https://user-images.githubusercontent.com/10247582/66302845-5d895b00-e902-11e9-9f0f-01f051b9e22f.png)

**Comment by kateliev** [comment]
**/three**:
- _overshoots_: are missing, like stated above

![image](https://user-images.githubusercontent.com/10247582/66303564-f371b580-e903-11e9-975b-3fbaf107d12c.png)
- _incision_: I think the place where the curves meet is too far to the inside and showing contrast disturbances that we do not have anywhere else in the font. I would pull it a bit outward and would thicken it a bit

![image](https://user-images.githubusercontent.com/10247582/66303667-33d13380-e904-11e9-8ea0-b4d5eb51c640.png)
- _curvature_: for me /three is way to "squarish" than its counterparts. I presume this is due to us "forgetting" to update the curves after we decided to "curvy" on most glyphs. I presume fixing this will fix the above issue also.

![image](https://user-images.githubusercontent.com/10247582/66303913-c40f7880-e904-11e9-9f51-9797c512b98e.png)
- _middle horizontal_: I find the middle in :Blk Cnd Ctr too short - would extend it further between the serifs. Also in :Blk Exp Ctr i find the upper-lobe to lower-lobe way too "shifted" as illustrated i woudl try muting that effect a bit:
![image](https://user-images.githubusercontent.com/10247582/66304063-13ee3f80-e905-11e9-8d37-c6dfb79d724a.png)

**Comment by kateliev** [comment]
**/seven** has mostly width and balance related problems - most ow which are not big deal at all
![image](https://user-images.githubusercontent.com/10247582/66304706-857abd80-e906-11e9-9c61-2f141b96da62.png)

On :Black Contrast masters i would personally go more triangular on the stem!

**Comment by kateliev** [comment]
As much as I love **/six** and **/nine** - IMHO /nine need to look and feel more stable. In some masters it just about to fall in it back.
![image](https://user-images.githubusercontent.com/10247582/66305131-557fea00-e907-11e9-9e71-48649d4d8924.png)
![image](https://user-images.githubusercontent.com/10247582/66305160-66306000-e907-11e9-85a8-b76d71a60c3c.png)
![image](https://user-images.githubusercontent.com/10247582/66305188-73e5e580-e907-11e9-9534-94a612600d21.png)

**Comment by kateliev** [comment]
I will try to make .salt version on issues i find troublesome and push them to the repo till the end of the day.

**Comment by kateliev** [comment]
Pushed:
/zero.salt - fixed width inconsistency
/two.salt - fixed design issues
/three.salt - redesigned with new curves
/four.salt - redesign on the :Ctr masters
/seven.salt - tweaks on angle, width, stroke
/eight.salt - redesign with curves similar to those found in /three
/nine.salt - minor tweak to lower the back curve

**Comment by servantb** [comment]
@kateliev thanks for all this. Here are my thoughts:

/zero.salt – /zero needed those fixes. Thanks for catching that.

/two.salt – I don't think this particular solution works. I agree that there is imbalance built into Benton's design, but the solution I don't think is to bring the tail down and back. Rather, I think the solution is to bring the bottom of the diagonal up a bit, and the upper terminal left a bit. I've added /two.salt.1 to the file with my proposed solution in the :Med master (I still need to flesh out the others).

/three.salt – I appreciate what you've done with the curves and the position of the upper lobe in the :LtEtc and :CtrEtc masters. Those work great. I don't agree with the increased width, nor the tie (middle horizontal stroke). As weird as the shorter (original) tie may seem, it actually works much better. It's also in line with how the figure is written, so the form is more natural.
Also, the upper lobe doesn't need to (and shouldn't) change position in the non-contrast masters (at least not so much).
I think tighter curves on the inside of the :MedCtrEtc masters work better. See my notes on /eight.salt.

/four.salt – This looks great. Love it.

/seven.salt – These edits look good, with only two exceptions. The :CndCtr and :BlkCndCtr don't quite work. There's too much space in the upper counter, and the taper in the stem is too pronounced.

/eight.salt – The edit to the :BlkEtc doesn't work. It needs the wider counter on the bottom. However, the increased white space in the joins at the waist work well—they're more in line with the 3.
The :LtCnd  and :Cnd edits are too square.
The increased curvature on the inside corners of the :MedCtrEtc masters are too great. In fact, the more I look at it, the more I'm convinced tighter curves on the inside of the :MedCtrEtc masters (like the current /eight has) would help the /B, /P, and /R in their :Ctr master. Weirdly, the greater curvature on the inside curve of the :BlkCtrEtc masters I think works much better. That is, I like your edits in the :BlkCtrEtc masters.
The narrower counters in your :BlkCndCtr work much better too, thank you.

/nine.salt – This works. Thank you.

**Comment by kateliev** [comment]
I am OK with what @servantb observed!

> bring the bottom of the diagonal up a bit

This is excellent!!! I love it, but still I am entitled to my opinion about /two's tail being all flat on the baseline...

**Comment by tphinney** [comment]
I am afraid I agree with Brandon that the /two looks better with the curve, rather than a corner, at the bottom right.

That said, perhaps that tail might need to extend a bit more right, in some of the :Cnd masters. Some of them feel a bit unbalanced. Or the right side could come in. Or a bit of each.
