### ISSUE TITLE
Small Numbers (denominators, numerators, superscript, subscript and fractions: dnom numr sups subs frac)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#145]
Denominators will be first. They will also be used, with different vertical shifts, as numerators, superscripts and subscripts.

Doing more work on /three.sups prototype, trying to craft initial guidelines for the full set. Intent to use the handmade /three.sups itself a sort of model for the automation, but ultimately replace it with a glyph from the automation

Height: Full size numerals are cap height (1400 units). The initial /three.sups prototype was 812 units. In testing, this seems to work decently for dnom/numr fractions. Definitely not more! _Could_ try slightly less, in the 780–800 range.

Weight:
:LtEtc was looking a bit too light at 28 horiz / 32 vert. Lowercase is 32/36. Now trying 30/34 (if that is still too light, will go to 32/36)
:Medium is looking pretty good.
:Blk is ok-ish. Trying making the /three.sups interior counters slightly less tall, widening the center stroke (+8 top, -10 bottom, shrinking both counters just a little to 82u and 90u).

Width:
:Cnd made narrower in Medium and Blk

**Comment by tphinney** [comment]
OK, submitted a test font that has a silly "three thirds" glyph. But it uses a /three.dnom /three.numr constructed to the size specs above. This should be good enough to tell if the vertical size is right, or perhaps should be slightly smaller. Let me know what you think @kateliev and @servantb

**Comment by kateliev** [comment]
Ok @tphinney , I have made you a set of "small figures" based on your initial design parameters. It is called _.dnom.1_. Feel free to explore :)

**Comment by tphinney** [comment]
So, I have been experimenting with the new small numbers.
http://g.recordit.co/83XZkyYVcM.gif

I think they are generally working pretty well. But I probably asked for them a bit larger than ideal. Not by a lot, though. @kateliev could we try 30/2000 units shorter (and proportionately narrower)?

**Comment by tphinney** [comment]
Video showing the "old" vs "new" fractions using the test glyphs.
https://recordit.co/77IgKFG1Xk
Watch and decide which set you prefer (top or bottom of each pairing) before reading on.
...

The difference is subtle. There is also a weight difference (real, not just apparent). I think either set would be OK, but I think the new one is better. I think the increased weight is probably a bigger factor than the decreased size, but both are good.

**Comment by tphinney** [comment]
Brandon also (unprompted) prefers the "new" version, so I am going with that.

**Comment by tphinney** [comment]
This is partly done, and working, with all the different sets. Still to be done:
- finish clean-up on individual glyphs (which are automatically reflected in the auto glyphs based on them). Only finished 3 out of 10 so far.
- feature code for 'frac' 'numr' 'dnom' 'supr' 'subs' (although currently Google does not support this, so not required for Google Fonts release—could make separate task for later)

**Comment by tphinney** [comment]
@kateliev latest commit was to address some odd inconsistencies in height in the small numerals, which we discussed in chat. That worked well; this is looking pretty darn good! 

I notice that the :LtEtc masters are 32 h x 34 v, where they need to be 30 h x 34 v ; the lower contrast makes it look like reversed stress, almost. I am inclined to just fix this manually, though, and say “close enough” as far as the automation goes.

**Comment by kateliev** [comment]
These look done.
