### ISSUE TITLE
/i and /j dot probably needs expanding in :Medium

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#146]
The /i and /j were widened by 4 units in :MediumEtc masters (incl contrast masters) today, as they were wrong.

For those masters, the dot size needs to be checked and possibly enlarged to match. (It is a separate component glyph all to itself, not the dot accent.)

**Comment by tphinney** [comment]
Just did this, AND ...  am also adjusting the :LtEtc dot weight. On macOS, at double-res, in the browser, the i dot is either actually invisible or nearly so, even up to 72+ px. That is not OK.

**Comment by tphinney** [comment]
Currently increasing :LtEtc from 52x52 to 56x56. TBD if that is enough.

**Comment by tphinney** [comment]
Nope. After some experiments, I settled on 75x76. This is _much_ larger than it was, but still considerably smaller than the period in the :LtEtc styles, which is 92x92 in the :Lt.
So, the revised i-j-dot is about 2/3 of the area of the period.

(Will be in my next submit.)

**Comment by servantb** [comment]
This sounds just fine. I was actually about to suggest bumping up to 70, so I think this will work. Thanks!
