### ISSUE TITLE
Check spacing and vertical alignment on quote marks (esp in :ExpEtc)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#149]

**Comment by tphinney** [comment]
I suspect the spacing is fine, but some of these seem Really Very High.

**Comment by tphinney** [comment]
@servantb is away this weekend, but was OK with me taking a swing at them. Working on them now; I think I have the :MediumEtc and :BlkEtc masters in good shape, but not so sure about the :LtEtc.

**Comment by tphinney** [comment]
I think the :LtEtc are also good, now. @servantb can review

**Comment by servantb** [comment]
Looks great. Thanks!
