### ISSUE TITLE
/four needs review

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#150]
I'm open to doing this, but since you folks have been doing most of the numbers, I thought I would give you first crack at it.

One of us should do some examination and tweaks on /four

I noticed that the /four has some oddities with the :Blk masters. It has some thinning in the horizontal, after it crosses the stem. This is not entirely unreasonable (although unexpected to me). But what is odd is that the thinning is 20 units in the :Blk but only 10 in the :BlkCnd — I would have expected :BlkCnd to need more, not less.

(Noticed while I was working on the small numbers for fractions/superscript/etc.)

**Comment by kateliev** [comment]
This one is on me - I usually try to compensate anywhere where the eye can be fooled enough so things look straight, but aren't so white-space could be gained. The 10 u is mistake, made it 20 u as the :Blk
