### ISSUE TITLE
Check glyph widths

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#151]
Please take your time and review the glyph widths in all your glyphs. There is a script in the repo called _Font: Check widths_ (image below)
![image](https://user-images.githubusercontent.com/10247582/66570199-cb898880-eb75-11e9-8747-e103ceb31950.png)
It will give you by what amount the :Regulars differ from :Contrasts (meaning anything that is not Ctr compared to what is Ctr). 

There are glyphs that will/must of course have differences, but then again there is a big bunch of glyphs that have to be exactly the same.

Just a simple check of very basic Latin reveals the following picture:

> [SG] Font Check WIDTH inconsistancies 0.01
> ------------------------------
> WARN:	 Glyph: A;	 BBOX width: Blk : Blk Ctr : 178.0 | Blk Cnd : Blk Cnd Ctr : 217.0 | Exp : Exp Ctr : 54.0 | Blk Exp : Blk Exp Ctr : 252.0
> WARN:	 Glyph: B;	 BBOX width: Blk Cnd : Blk Cnd Ctr : 21.0 | Blk Exp : Blk Exp Ctr : 143.0
> WARN:	 Glyph: G;	 BBOX width: Cnd : Cnd Ctr : 40.0
> WARN:	 Glyph: J;	 BBOX width: Exp : Exp Ctr : -192.0
> WARN:	 Glyph: K;	 BBOX width: Blk : Blk Ctr : -27.0
> WARN:	 Glyph: M;	 BBOX width: Blk Cnd : Blk Cnd Ctr : 198.0 | Exp : Exp Ctr : 116.0 | Blk Exp : Blk Exp Ctr : 324.0
> WARN:	 Glyph: N;	 BBOX width: Blk : Blk Ctr : 300.0 | Cnd : Cnd Ctr : 192.0 | Blk Cnd : Blk Cnd Ctr : 326.0 | Exp : Exp Ctr : -24.0 | Blk Exp : Blk Exp Ctr : 234.0
> WARN:	 Glyph: P;	 BBOX width: Blk Exp : Blk Exp Ctr : 80.0
> WARN:	 Glyph: R;	 BBOX width: Cnd : Cnd Ctr : -52.0 | Blk Exp : Blk Exp Ctr : 46.0
> WARN:	 Glyph: V;	 BBOX width: Blk : Blk Ctr : 174.0 | Blk Cnd : Blk Cnd Ctr : 216.0 | Blk Exp : Blk Exp Ctr : 288.0
> WARN:	 Glyph: W;	 BBOX width: Blk : Blk Ctr : -152.0 | Cnd : Cnd Ctr : -23.0 | Blk Cnd : Blk Cnd Ctr : 81.0 | Exp : Exp Ctr : 24.0 | Blk Exp : Blk Exp Ctr : -56.0
> WARN:	 Glyph: X;	 BBOX width: Blk : Blk Ctr : 100.0 | Exp : Exp Ctr : 75.0
> WARN:	 Glyph: Y;	 BBOX width: Blk Cnd : Blk Cnd Ctr : 72.0 | Exp : Exp Ctr : 185.0 | Blk Exp : Blk Exp Ctr : 169.0

_The string shows which Contrast masters BBox is how much different compared to the one that is not Ctr._

Here is a quick run with figures:

> [SG] Font Check WIDTH inconsistancies 0.01
> ------------------------------
> WARN:	 Glyph: two;	 BBOX width: Blk : Blk Ctr : 36.0 | Exp : Exp Ctr : 64.0 | Blk Exp : Blk Exp Ctr : 30.0
> WARN:	 Glyph: five;	 BBOX width: Blk Cnd : Blk Cnd Ctr : 56.0
> WARN:	 Glyph: four;	 BBOX width: Exp : Exp Ctr : 39.0

Here is a run on lowercase:

> [SG] Font Check WIDTH inconsistancies 0.01
> ------------------------------
> WARN:	 Glyph: b;	 BBOX width: Lt Exp : Lt Exp Ctr : -30.0
> WARN:	 Glyph: d;	 BBOX width: Lt Exp : Lt Exp Ctr : -26.0
> WARN:	 Glyph: f;	 BBOX width: Cnd : Cnd Ctr : 21.0 | Blk Cnd : Blk Cnd Ctr : 145.0 | Blk Exp : Blk Exp Ctr : 25.0
> WARN:	 Glyph: h;	 BBOX width: Blk : Blk Ctr : -90.0
> WARN:	 Glyph: i;	 BBOX width: Lt Exp : Lt Exp Ctr : -164.0
> WARN:	 Glyph: k;	 BBOX width: Blk Cnd : Blk Cnd Ctr : -27.0 | Exp : Exp Ctr : 80.0
> WARN:	 Glyph: m;	 BBOX width: Blk : Blk Ctr : -300.0 | Cnd : Cnd Ctr : -32.0 | Exp : Exp Ctr : -600.0 | Blk Exp : Blk Exp Ctr : -481.0
> WARN:	 Glyph: n;	 BBOX width: Blk : Blk Ctr : -90.0
> WARN:	 Glyph: p;	 BBOX width: Lt Exp : Lt Exp Ctr : -26.0
> WARN:	 Glyph: q;	 BBOX width: Lt Exp : Lt Exp Ctr : -26.0
> WARN:	 Glyph: r;	 BBOX width: Lt : Lt Ctr : -50.0 | Blk : Blk Ctr : -90.0
> WARN:	 Glyph: t;	 BBOX width: Blk Cnd : Blk Cnd Ctr : 120.0
> WARN:	 Glyph: v;	 BBOX width: Blk : Blk Ctr : 293.0 | Cnd : Cnd Ctr : 91.0 | Blk Cnd : Blk Cnd Ctr : 185.0 | Exp : Exp Ctr : 83.0 | Blk Exp : Blk Exp Ctr : 222.0
> WARN:	 Glyph: w;	 BBOX width: Blk : Blk Ctr : 151.0 | Cnd : Cnd Ctr : 99.0 | Blk Cnd : Blk Cnd Ctr : 160.0 | Exp : Exp Ctr : -97.0 | Blk Exp : Blk Exp Ctr : 79.0
> WARN:	 Glyph: x;	 BBOX width: Blk : Blk Ctr : 145.0 | Cnd : Cnd Ctr : 23.0 | Blk Cnd : Blk Cnd Ctr : 145.0 | Exp : Exp Ctr : 53.9999771118 | Blk Exp : Blk Exp Ctr : 70.5999984741
> WARN:	 Glyph: y;	 BBOX width: Blk : Blk Ctr : 192.270017624 | Cnd : Cnd Ctr : 95.0 | Blk Cnd : Blk Cnd Ctr : 180.910003662 | Exp : Exp Ctr : 99.7999839783 | Blk Exp : Blk Exp Ctr : 224.539928436

It is obvious that we have problems. Also there is the root of the **width error** we encountered in SMCP, that I have fixed last Friday!

I have started fixing the Cyrillic as it is obvious that it followed in Latins footsteps. What gets fixed and what not is up to you and common sense = not everything needs to be fixed.

I have provided a crude tool that will aid you in your struggles. It is called _Glyph: Fix width_ (image below)
![image](https://user-images.githubusercontent.com/10247582/66570957-528b3080-eb77-11e9-9c89-2c4e7ef70778.png)

It will move the nodes selected in such a manner that the overall BBox width is perfectly matched with the non Ctr masters. You could select nodes on any master - the changes will be made only on the :Contrast masters. It is obvious that this works perfectly on "two stem" glyphs /H /B /P and etc but not on /W /Y /X and etc. I presume you get the idea. **ALWAYS select the nodes furthest from origin** - meaning right most nodes as the script is not smart enough - it will only add or subtract the difference in BBox widths.

**Comment by kateliev** [comment]
One final interesting detail. The reporting tool is set to tolerate differences up to 20u which I consider normal, so what you are getting is not false-positive result - the situation is just that bad :).

**Comment by tphinney** [comment]
So, to sum up from the reports above, the differences I would expect are likely meaningful and need correction:
/B /G /J /P /R
/two (and maybe /four)
/b /d /f /h /i /m /n /p /q /r /t

**Comment by tphinney** [comment]
I fixed all the glyphs specifically listed above.
However, checks need to be made on many others.

**Comment by kateliev** [comment]
Fixed all Cyrillic: /ae, /uni0259.smcp, /uni0409, /uni040A, /uni0424, /uni0431.smcp, /uni0444.smcp, /uni0446.smcp, /uni0446.smcp, /uni0448, /uni0448.smcp, /uni0449.smcp, /uni0449.smcp, /uni044B, /uni044B.smcp, /uni044F.smcp, /uni0454.smcp, /uni0454.smcp, /uni0459, /uni0459, /uni0459.smcp, /uni045A, /uni045A, /uni045A.smcp, /uni0493.smcp, /uni04D8, /uni04D9.smcp, /uni04F2,
