### ISSUE TITLE
Consider new contrast treatment for /acute /grave /circumflex etc.

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#155]
The latest :CtrEtc versions of /guilsinglleft and related seem to work well

Perhaps this treatment could also be used for /circumflex /acute /grave and related glyphs — the high-contrast version of /circumflex would look (broadly) like a rotated version of the guillemot. Currently, the high-contrast /grave gets thin, and the high-contrast /acute does not change; in the new version, they would both become triangular (well, wedge-shaped) instead. 

I'd make the actual changes, but I would be curious to hear what others think of the proposal.

**Comment by servantb** [comment]
I think using the same treatment as the guillemot on the acute and grave makes sense and will work well. I'm not so sure about the circumflex and caron. The way they are written, it makes sense to have the same structure as the /V and /A. The guillemot is the way it is because it's sideways.

I can see, however, that the two approaches might not look right together. I'd like to see it though. It may actually work.

**Comment by tphinney** [comment]
So, I will do this in steps. First, the alternative contrast on the /acute and /grave.  Maybe versions both with and without the top angled, for comparison.

Part of the reason for the alternative contrast is that I feel like having opposite contrast schemes for acute and grave in the same line—potentially even in the same word—just looks weird, or even plain wrong. Either one would be ~ OK by itself (although the plain skinny line is pretty weak), but when I see them both in the same font style ... ugh.

**Comment by tphinney** [comment]
I've run a combined experiment for this and #157.
https://recordit.co/mU1czaLjJo
https://recordit.co/5zE1fqYpP4

Broadly: I am liking both these related changes a lot better than the status quo, so far.

**Comment by tphinney** [comment]
I've been reviewing. I am going to proceed with the change for the high-contrast styles for acute, grave, circumflex and caron. I may trim the top of the circumflex / bottom of the caron, that's another question.

**Comment by tphinney** [comment]
More review: doing this but NOT #157 
First, will do acute, grave, hungarumalut and their .case alternates etc.

Then will decide whether to apply to circumflex, or keep current circumflex; separate testing/decision.
