### ISSUE TITLE
/s may need more work in Medium & heavier weights, esp :Ctr

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#158]

**Comment by servantb** [comment]
Adjusted roundness of curves in /s (a little further from the /o curvature and a little closer to the /e curvature) in the :BlkEtc masters. Adjusted upper counter width (no change to stroke width) in the aforementioned masters as well as :Cnd and :CndCtr. Adjusted spacing as well.

**Comment by servantb** [comment]
Added a bit of weight in the :BlkCtr and :BlkExpCtr.

**Comment by tphinney** [comment]
Looks good!
