### ISSUE TITLE
less < and greater > suck in :Ctr styles

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#159]
Note to self: ok, so yes, this wedge-triangular style for the high-contrast variants worked great for the guillemots. But that’s because it is a traditional thing to do in a serifed font, so it doesn’t seem too far out of place. But wow, it is a total failure for the less (<) and greater (>) signs. It stinks. Looks even worse when part of ≤ or ≥ with the thin horizontal line. Need to consider how else to handle contrast on these, including how it looks/interacts next to numerals and other math symbols.

**Comment by tphinney** [comment]
So, for the time being, I have removed the contrast entirely—a side effect of fixing #165, and not wanting to do a bunch of further work to put back in the contrast that was no good anyway. BUT that leaves open the question of what to do for YOPQ axis in these glyphs.  :(

Not looking for anybody else to do the work, but if you have any ideas about an approach to use, I welcome thoughts! @kateliev or @servantb ?

**Comment by servantb** [comment]
Math glyphs, while appropriate to flex with weight and width, should not have contrast. I would say keep them the thickness of their non-contrast counterparts.

**Comment by tphinney** [comment]
I've made this a bigger issue: #166

**Comment by kateliev** [comment]
Commented on #166. Lets bring the conversation there!
