### ISSUE TITLE
Create kerning classes

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#160]
Need to create kerning classes

**Comment by tphinney** [comment]
I'm up to 21 classes now. Lots more to go.
For now I am creating them only in the :Medium master. Will spread them over all masters later.

**Comment by tphinney** [comment]
26

**Comment by kateliev** [comment]
Done making all the classes from scratch. 99 new classes + integrated some of @tphinney  = 101 so far. This encompasses all the alphabetic glyphs + some punctuation.

**Comment by kateliev** [comment]
PS: Some classes could be merged, but that might reduce the overall count -10 (max). So no big deal.

**Comment by kateliev** [comment]
Closed by mistake :)

**Comment by kateliev** [comment]
New classes created and copied across masters. 

The modified classes are based on @tphinney preference for keeping diacritic and regular glyphs separate.
