### ISSUE TITLE
germandoubless.alt.smcp

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#162]
As the lowercase eszett does not belong to the smcp set, we have a scaled down capital eszett. So the picture is clearly wrong - I wold suggest making a SS "ligature" instead. What is you opinion about this glyph?

![image](https://user-images.githubusercontent.com/10247582/66839318-e6da0680-ef6e-11e9-826e-bb064e9cb223.png)

**Comment by tphinney** [comment]
Well, we definitely need the small cap shape based on the scaled-down cap eszett. If a user invokes the c2sc feature, and the input is the cap eszett, they should definitely get the small cap form.

BUT, what should happen with 'smcp' applied to the lowercase /germandbls ? As I was reminded on Twitter (https://twitter.com/ThomasPhinney/status/1184146367024812032), many text engines special-case this, but not all do. So the best option is to do a one-to-many substitution for 'smcp': 
`sub germandbls by s.smcp s.smcp ;`

**Comment by tphinney** [comment]
I have also made a glyph for it.

**Comment by tphinney** [comment]
done!
(note: glyph name for the small cap version of the cap eszett is different than what is currently in the .enc file: now /uni1E9E.c2sc ; it will appear at the end of the glyph ordering until next update of .enc file
