### ISSUE TITLE
Increase overshoot of :LtCndEtc in uppercase from 4 to 8 units.

### ISSUE THREAD

**Issue by servantb** [tphinney/science-gothic#164]
We forgot to take overshoot into account after changing the curvature in the light masters. Additional overshoot is needed for the :LtCnd and :LtCndYopq. Overshoot should be increased from 4 units to 8 units.

I can do the Latin, @kateliev the Cyrillic, and @tphinney the symbols perhaps?

**Comment by kateliev** [comment]
@tphinney and @servantb if you come to agreement where glyphs should land in the zones, as there are glyphs landing on -4, others -8 and some -14 and the zone is 14 u wide and provide me with clear algorithm* how did you choose those values i can build us a tool to check and fix such problems.

*By algorithm i mean:
/O /C /G : Lt masters = 0
/O /C /G : LtCnd masters = -4
....
and so on

**Comment by servantb** [comment]
Oops. That's probably my bad. I'll fix it.

As far as the numbers go, the overshoot values are in the SG Measurements google doc.

**Comment by servantb** [comment]
Done in Latin.
