### ISSUE TITLE
Glyphs not fitting in zones

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#167]
There are apparently ghlyphs that do not fit into the designated zones. To me this is a bug - @tphinney , @servantb any ideas? As i have those in Cyr also the qestion here is - we made a mistake and duplicated it across the face, or the zone got shorter?

![image](https://user-images.githubusercontent.com/10247582/67083002-fb9ee000-f1a2-11e9-9843-ffb77cb4567a.png)
![image](https://user-images.githubusercontent.com/10247582/67083032-0fe2dd00-f1a3-11e9-804b-6a7ec789c6b9.png)

**Comment by servantb** [comment]
Not sure what's up with blue zones, but everything is where it should be as far as overshoot.

If you want the overshoot values, they are listed by layer for both upper- and lowercase in the SG measurements google doc.

**Comment by kateliev** [comment]
Then it is the zone that is buggy as overshoot sould not exceed the zones. We should fix that as the blues are important!

**Comment by tphinney** [comment]
Yes, seems like a zone bug in the :BlkCnd master. I don't see an issue in :BlkCndCtr :Blk or :BlkExp, so I am going to assume it is only in the one master.

Seeing as I am the only one working on the font right now, I just went and fixed it. It will be in my check-in tonight. Maybe keep your eyes peeled for any more such issues, though!

**Comment by kateliev** [comment]
@tphinney - nope it is still not fixed...
![image](https://user-images.githubusercontent.com/10247582/67270165-c9ea8980-f4c0-11e9-8fe5-c548dcad203c.png)
![image](https://user-images.githubusercontent.com/10247582/67269958-5a749a00-f4c0-11e9-81b1-c2530b759f64.png)
So I guess the honor is mine. Will use the largest values from the measurements doc that @servantb prepared for us:
![image](https://user-images.githubusercontent.com/10247582/67270092-99a2eb00-f4c0-11e9-934c-63479b07ade5.png)

**Comment by kateliev** [comment]
OK fixed! 
![image](https://user-images.githubusercontent.com/10247582/67272044-6d896900-f4c4-11e9-99cf-6d966852b0bd.png)

Also I am sharing with you my font metric backups that you can use to restore the metric data using TR Manager:
![image](https://user-images.githubusercontent.com/10247582/67272206-c822c500-f4c4-11e9-83ea-1a2fd4c90a48.png)
