### ISSUE TITLE
/uni2215 (fraction clone) is shifted ~ +376 vertically (should be zero)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#169]

**Comment by tphinney** [comment]
Probably ought to just rebuild it with a user-defined Glyph Construction formula, rather than relying on whatever FontLab is doing (which has messed up).

**Comment by kateliev** [comment]
Some strange deltas here and a "space"...?! Though the recipe shows only "fraction"
![image](https://user-images.githubusercontent.com/10247582/67272774-d9200600-f4c5-11e9-8c00-14aac5fab3ae.png)

**Comment by kateliev** [comment]
To me this is definitely a FL bug, but funny enough writing the formula the wrong way...
 **/fraction + /space**
... produces the desired result! As the solution does no harm i propose we keep it :)

![image](https://user-images.githubusercontent.com/10247582/67273755-c0b0eb00-f4c7-11e9-80a4-f1395262170c.png)
