### ISSUE TITLE
/e.smcp is too light in :BlkEtc weights

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#173]
Currently, seems too light in :BlkEtc

**Comment by kateliev** [comment]
Made it even blacker with horizontal stroke:
 (<f.smcp> + <b.smcp>)/2 = (368  + 312)/2 =  340 u 

![image](https://user-images.githubusercontent.com/10247582/68486246-5f1fa900-0249-11ea-95bd-090d1050dbf6.png)

...which is 92% of the blackness of the stroke of /f.smcp almost close to the 95% difference between /E and /F

Hope you like it - if not - we can always revert it :)

**Comment by servantb** [comment]
Beautiful. 👌
