### ISSUE TITLE
/zero.zero fix

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#177]
Just noticed that the slashed zero (/zero.zero) has a weird leftover from early in development: the zero portion of the glyph is built from FOUR separate contours! That’s not even counting the slash. Weird, right? So:

1) It needs to be replaced with a normal zero outline, at least.

Also, to evaluate and do if appropriate:
2) whether some optical compensations are needed so the slash doesn't appear to visually “jump” when crossing the zero.
3) whether the glyph can have overlap completely removed (after 1 and 2 above)

**Comment by kateliev** [comment]
Done! All of the above!
