### ISSUE TITLE
Handle remaining /periodcentered for .smcp and Catalan smcp

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#178]
sort out any issues for positioning of the stand-alone /periodcentered variants for Ldot/ldot and small cap

/periodcentered.smcp (easy)
/periodcentered.loclCAT.smcp
/periodcentered.loclCAT.case
/periodcentered.loclCAT   < not sure this is in the charset! But of course it ought to be.

**Comment by tphinney** [comment]
Done for:
/periodcentered.loclCAT.case
/periodcentered.loclCAT

I could improve things by doing a designspace alternate for the lowercase dot in certain bold condensed ranges, where it gives up on maintaining the lowercase el-to-el spacing and gives itself a bit more width and whitespace between the letters.

Otherwise, need to wait to finish the /periodcentered.loclCAT.smcp until I have the small cap spacing worked out. I can't position the glyph until that is done. (Although I have a spreadsheet set up, so as soon as I make sidebearing changes, I can enter the new sidebearings, and I will know the correct offsets.)

It will be the size of the lowercase version, but spaced/positioned for small cap L (l.smcp)

**Comment by tphinney** [comment]
Still needed:
/periodcentered.smcp (easy)
/periodcentered.loclCAT.smcp
/periodcentered.smcp (easy)
/periodcentered.loclCAT.smcp.case < NEW

**Comment by tphinney** [comment]
I have adjusted anchors for /periodcentered.loclCAT.smcp correctly for current small cap spacing. (If a change is made due to #181 it would likely need adjustment.)

**Comment by tphinney** [comment]
After come experiements ... decided periodcentered.smcp is not needed.

**Comment by servantb** [comment]
Looks good.
