### ISSUE TITLE
Final Latin diacritic combos

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#179]
A/a with breve + additional accents (acute, hook, tilde). 
/uni1EAE
/uni1EB2
/uni1EB4
/uni1EAF
/uni1EB3
/uni1EB5

**Comment by servantb** [comment]
In the /uni1EAE and /uni1EB0, as well as /uni1EAF and /uni1EB1 the grave and acute are at differing heights above the breve in multiple masters.
In those same glyphs the acute is frequently left of where the grave is (if the grave was reflected).

In masters where the acute, grave, or hook can fit down into the bowl of the breve, I think it looks best to do that (:LtEtc, :ExpEtc perhaps, some Ctr, maybe even :Med for the hook—slightly).

**Comment by tphinney** [comment]
Make a separate issue for that? I'll comment on it there....

**Comment by servantb** [comment]
Issue #179:
Rebuilt /uni1EB2 and /uni1EB3 using /brevecomb_hookcomb and /brevecomb_hookcomb.case 
Checked /uni1EB4 /uni1EB5 and they look good.
