### ISSUE TITLE
Switch to 2000 UPM!

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#18]
Google requires 2000 UPM in the final file. 

Should we switch right away, or wait? Impact on existing data? Spreadsheets etc.? Discuss.

**Comment by IgorFreiberger** [comment]
I vote for immediate change. As it is just doubling values, no issues should result.

**Comment by kateliev** [comment]
If that is a requirement, I suggest we switch immediately!

**Comment by tphinney** [comment]
The only reason not to, is that "off by one" errors will be harder to see, given the resolution limitations of our devices. And because they are just half as big, at whatever zoom.

But yes, we could do it sooner rather than later. It will also affect some spreadsheets and data. But nothing too horrible.

This is another "global change" that we should make at the same time as other global changes. All the individual glyphs will get rescaled, so it will touch practically everything.
