### ISSUE TITLE
Weird glitch on /uni049D.smcp :ExpCtr

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#180]
![Screen Shot 2019-10-30 at 8.57.06 PM.png](https://images.zenhubusercontent.com/55f8a29e4f7a08fbb7f4ebd1/71fa9d42-fb17-4f2c-a870-2f5b8d6c986d)
Something going wrong at bottom right, there.

**Comment by kateliev** [comment]
Fixed! Thank you!
