### ISSUE TITLE
exclam.smcp, question.smcp (and their inverted friends) seem a bit light?

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#185]
Next to the alphabetic small caps, in many cases the exclam and question seem lighter. The full-size ones look fine next to both caps and lowercase. Did something go wrong with the smcp process for these glyphs?

**Comment by kateliev** [comment]
@tphinney please see how the /exclam.smcp feels now. If it is up to your taste will proceed with /question.smcp. Have in mind that there is increase in weight of the dot. I do not remember us (together with @servantb) discussing and fixing the smcp punctuation - and what is the policy on that?!

**Comment by tphinney** [comment]
Passing this to @servantb as the full-size ones were his glyphs.

**Comment by servantb** [comment]
I like what you've done with the /excalm.smcp. The weight is much better.

As far as what to do with the dots and punctuation, my first inclination is to make it the same as the regular punctuation. However, if we make the dots in the /exclam.smcp and /question.smcp the same size as the /period etc., then that would become very awkward (or untenable) very quickly.

I imagine these are a special use case, and don't occur alongside other punctuation. My only frame of reference for this is https://typedrawers.com/discussion/1606/small-caps-practice

My proposed solution would be to give the :LtEtc masters dots the same size as their non-smcp counterparts, but leave the rest as is.

I welcome other thoughts/perspectives.

**Comment by tphinney** [comment]
Yes, no need to make smaller periods, commas, etc. The existing ones are fine.
MAYBE one could use small cap quote marks. But I wouldn’t worry about it for now.

One of my considerations is that the Google Fonts API does not even support small caps in web fonts as yet. We are doing them because they are especially traditional for Bank Gothic, and hence should be in Science Gothic. But people using these through Google Fonts won’t even be able to use them (yet).

**Comment by servantb** [comment]
I think we're good here, unless anyone has any more thoughts?
