### ISSUE TITLE
UFO prep is deleting some incompatible glyphs

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#188]
I think the needed solution is to tweak the glyphs so they don’t run afoul of the prep script.

The troubling output line I see is this one:
`Incompatible Glyphs (removed): /uni0402 /uni0473 /uni049B.smcp /uni04A1.smcp /uni04E9`

**Comment by kateliev** [comment]
> I think the needed solution is to tweak the glyphs so they don’t run afoul of the prep script.

There is no way to tweak them - just deleting is the only option. Let's not forget that the script is intended for rapid UFO development - you need badly the UFO - you run the script and get it.

If you need something fixed - you take the list of deleted glyphs and start fixing them for the next iteration :)

**Comment by tphinney** [comment]
I think my “tweaking” and your “fixing” are the same thing.  ;)
These are all Cyrillic, so I was inclined to leave them to you. I have previously fixed some Latin glyphs that were giving us similar trouble.

**Comment by kateliev** [comment]
All fixed but waiting for resolution on #191 to remove overlaps and get rid of the problem entirely as some of those Cyrillic glyphs are composites.
