### ISSUE TITLE
"Copy Layers" script

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#19]
Vassil, how about a script that, for all currently selected glyphs, takes all the existing con-contrast masters, and duplicates their glyph contents to the contrast masters?

Possible refinement (is it needed?): it checks per glyph to make sure the target layers are all empty, and only duplicates a layer in a glyph if it is indeed empty of outlines.

Would everybody find this useful? Does it need any refinements?

**Comment by kateliev** [comment]
Actually it is usable in every situation with any content from any master. Will code it tomorrow. You can actually do this from Typerig layer panel, but i suggest you wait for me to code a new script, as the TR one uses masters cross-linking and you have to expand the shape after copying and i bet that someone will forget to do it thus resulting future complications.

**Comment by kateliev** [comment]
Prototype is ready.

**Comment by tphinney** [comment]
To Do: (? or discuss)
- make work on multiple selected glyphs
- copy bindings (not just raw metrics)
- copy anchors

Discuss:
- does it need to copy guides and links? (I think "nice" but not required)

**Comment by kateliev** [comment]
Script is done!

**Comment by tphinney** [comment]
Looking good! Just one thing:
"Copy to Width Masters" should be "Copy to Width & Weight Masters" (& should also copy to Lt and Blk)

**Comment by tphinney** [comment]
Also, a nice enhancement would be: if the destination layer does not already exist, the script creates it.

**Comment by kateliev** [comment]
Changes added! Done!
