### ISSUE TITLE
Small cap ogonek attachment is broken

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#190]
It's not just bad, but awful
/eogonek.smcp 
/iogonek.smcp 
/oogonek.smcp 
/uogonek.smcp

**Comment by tphinney** [comment]
I fixed this in my check-in a short while ago.

**Comment by kateliev** [comment]
Sorry but I did not see it fixed :(

**Comment by kateliev** [comment]
It is all now fixed!
