### ISSUE TITLE
Revisit /K /k

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#191]
I want to purpose a new revisited form of /K /k placed in the font as /K.new /k.new.
I have been thinking for a while about the original versions and do not find the strong tapering and extreme widths on some masters up to my taste. That is why i am proposing new versions with more subtle thinning of the stroke, revisited weights of arm and leg and some width adjustments - mainly in /k - as i find it too wide compared to /o and /n.

To illustrate some of the changes: Left old - Right New
![image](https://user-images.githubusercontent.com/10247582/68132491-7ac44000-ff27-11e9-817a-b0f1d5f87f9f.png)
![image](https://user-images.githubusercontent.com/10247582/68132527-8b74b600-ff27-11e9-9898-7016da361bc1.png)
![image](https://user-images.githubusercontent.com/10247582/68132548-94fe1e00-ff27-11e9-8081-d573e8f720f9.png)

Width: Old up - New down
![image](https://user-images.githubusercontent.com/10247582/68132744-df7f9a80-ff27-11e9-8e4b-1231b53ba5ee.png)
![image](https://user-images.githubusercontent.com/10247582/68132768-e9a19900-ff27-11e9-80d6-0c01c1e289cf.png)
![image](https://user-images.githubusercontent.com/10247582/68132790-f4f4c480-ff27-11e9-8c60-bb6d6a11453e.png)
![image](https://user-images.githubusercontent.com/10247582/68132808-fcb46900-ff27-11e9-8cea-b063766b86db.png)
and so on...

I would like you to discuss the changes, they are not entirely perfect but give some insight on what i find troubling. If you decide to keep the new form or use some in-between solution, please let me know, so i could change the Cyrillic forms, as they are present in mutiple glyphs.

... and also.. the new form manifests the same interpolation problems =kinks that manifest in the :CtrEtc axes as the old one... thus whatever your decision I think we should address that problem also. Mainly the problem shows up while moving from :CndCtr -> :Ctr - severe tapering of the arm at the joint and :BlkCtr-> :BlkCndCtr - severe thickening at the joint

![image](https://user-images.githubusercontent.com/10247582/68133190-967c1600-ff28-11e9-850c-fac6df9dcac7.png)

**Comment by servantb** [comment]
I like these proposed changes. It goes a lot farther than the tweaks I did earlier to reduce the leg weight and flaring, and it works really well. Thanks, @kateliev!

**Comment by kateliev** [comment]
@servantb thank you! 
Now this leads to the second thing to be discussed - the kink - i am very well interested what @tphinney has to say about it, as he is an expert in these kind of interpolation error. 
![image](https://user-images.githubusercontent.com/10247582/68161353-6485a680-ff5e-11e9-9050-fd1f6baa80c0.png)

I personally have played a bit with the problem and found two solutions - either not perfect but working:
- self-intersect/overlap the K-s at the joint - it works rather well and needs to be done only on the :CndCtr masters - ohers would just have two nodes one over the other (not uncommon in the typeface)
![image](https://user-images.githubusercontent.com/10247582/68161299-428c2400-ff5e-11e9-9b66-b5be6cfd9c1f.png)

- add a node at the "upper" outline part of the arm at the virtual intersection with the outer part of the outline of the leg. Then "synchronizing" this node to be at the exactly same intersection for all masters. This will solve the problem of the arm thinning but will introduce a subtle break along the arm at some interpolation positions.
![image](https://user-images.githubusercontent.com/10247582/68161695-158c4100-ff5f-11e9-8656-b85fcdfa37b3.png)

_Note all images show exactly the same axis position parameters with different solutions applied_

**Comment by tphinney** [comment]
In general, I think the proposed changes are a significant improvement! Nice work. I have a few specific counter-suggestions below, where I think the change you are making is good, but goes a bit too far.  :)

Regarding the interpolation problem, I think the self-intersection is a preferable solution, of the two. Nice job sorting that out.

Now some specific details:

![image](https://user-images.githubusercontent.com/10247582/68132527-8b74b600-ff27-11e9-9898-7016da361bc1.png)
Agree on the /k, but for the /K on top ... I think the ideal is probably right in the middle the previous version and your new one.

![image](https://user-images.githubusercontent.com/10247582/68132548-94fe1e00-ff27-11e9-8081-d573e8f720f9.png)
For the /K, I like the lack of flare, but it could use just a little weight added. Again, maybe in between somewhere.
For the /k, everything else is good, but perhaps the junction has risen a little too high?

![image](https://user-images.githubusercontent.com/10247582/68132790-f4f4c480-ff27-11e9-8c60-bb6d6a11453e.png)
Your version is much better, but seems just a bit over-corrected. If there were an axis between this and the previous version, it would be better if it were just ... 1/3 or 1/4 of the way back towards the previous. Just a *little* flare, a little more weight, and definitely not quite so high-waisted. And same again with this next one below:
![image](https://user-images.githubusercontent.com/10247582/68132808-fcb46900-ff27-11e9-8cea-b063766b86db.png)

**Comment by kateliev** [comment]
Actually @tphinney i have done exactly that - I have interpolated 50% between the old and the proposed designs and placed them under names /K.05 /k.05 in the font. I find the results more than satisfactory.
![image](https://user-images.githubusercontent.com/10247582/68214229-b6254400-ffe5-11e9-82d9-db60c3ae1ad7.png)

_PS: Also there is a new simple script to to exactly that called SG-Font-InterpolateGlyphs.py. It is too simple and requires that you modify the actual code to use it, but the config is pretty simple - just write the names of the source glyphs and interpolation times._

**Comment by servantb** [comment]
I liked how far you went the first time, @kateliev, but after checking the interpolated versions, I think they work very well too. I can see the need for the slight flair, especially in the :CtrEtc masters, and this looks good.

Will you be implementing the self-intersecting solution to the interpolation problem on those glyphs?

Thanks for your eye and all your work on this!

**Comment by tphinney** [comment]
I've played with the (three!) different versions. First, I agree that @kateliev ’s version is much better than the original—if it were just a choice between them I would take his! That said, I think the interpolations are turning out even better.

For /K, sure, 50% is good.
For /k, I would say 75% of the way from “old” to “new” would be great

**Comment by kateliev** [comment]
Done! Replaced /K with 50% version and /k with 75% version. Old glyphs are kept for backup until next iteration with .old suffix.

**Comment by kateliev** [comment]
Fixed /K /k dependent glyphs:
/uni0416 /uni043A /uni0436 /uni0497 /uni049B /uni04A1
