### ISSUE TITLE
Aring doesn’t work right in :BlkEtc - consider unjoined?

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#192]
Two related problems:
1) Perhaps the ring should not be merged with the A in any weight? http://diacritics.typo.cz/index.php?id=16
2) In the :BlkEtc the ring part of /Aring is currently merging badly, it has a partial gap. The ring would need to be heavier/wider to fix this.

Even if we un-merge, perhaps the :BlkEtc ring could be a bit bolder?

**Comment by tphinney** [comment]
Will do both. Thanks to @servantb for pointing out the problems.

**Comment by tphinney** [comment]
/Aring /Aringacute detached the ring
/uni030A /uni030A.case Made the ring slightly heavier in the :BlkEtc weights
fixed a positioning bug for /Aringacute where the acute was misplaced.

**Comment by servantb** [comment]
Much better. I think this works well un-merged.

I think thee are a few other issues with the ring itself, particularly in the .case version, but we'll tackle those in issue #78
