### ISSUE TITLE
Proposed changes to math symbols (/greaterequal /lessequal /plusminus /divide /uni00B5)

### ISSUE THREAD

**Issue by servantb** [tphinney/science-gothic#193]
(Refers to conversations in issues #165 #166)

I think the math symbols are looking good for the most part. After talking with @tphinney, we thought a few tweaks may be necessary.

We like the amount of whitespace in the /greaterequal, /lessequal, and /plusminus, but don't like what it does to those glyphs to make them the same height as the plus. That said, I'm thinking of making the symbols a bit taller so they don't seem as crunched, especially in the extremes of the design space. This is in keeping with plenty of other typeface designs by people who seem to know more about what they're doing than I do.

The dots in the :LtEtc masters of /divide, while using a solution that is not uncommon in other typeface designs, seems a bit out of place in Science Gothic. I'd like to use the :Lt period for the dots in these masters.

Lastly, the joint in the /uni00B5 :CtrEtc masters seems awkward. I'd like to make it curve up into the stem like it does in the :LtEtc masters rather than use the notch.
I also think this glyph requires a vertical stem on the right, like the a. (Which makes me wonder whether we need to reconsider our lowercase /u.)

![image.png](https://images.zenhubusercontent.com/5d4a125675d0cc52188b0d30/060ab602-679c-47db-86b6-cd000ddd4c9e)

I'm planning to go ahead and make these changes, but want to run that by @kateliev since he's invested some time in the math symbols.

**Comment by servantb** [comment]
Here's a proposed /uni00B5 with the stem (:Med and :BlkCndCtr)

![image](https://user-images.githubusercontent.com/50463501/68160680-33c75200-ff09-11e9-97cc-102b2bfa5477.png)![image](https://user-images.githubusercontent.com/50463501/68160699-39249c80-ff09-11e9-891f-fcc1cd376bd4.png)

**Comment by kateliev** [comment]
@servantb I am OK with the changes proposed! Thank you!

**Comment by servantb** [comment]
The treatment @kateliev gave the contrast masters is great. @tphinney and I felt the /lessequal and /plusminus shouldn't be forced to the same height as the /plus, so I've raised the height on those a bit.

I think we are okay to close this if there are no other issues? (I'll leave that to one of you fine gentlemen.)

**Comment by kateliev** [comment]
I am OK! Thank you @servantb!
