### ISSUE TITLE
Science Gothic Y Opaque (contrast) axis slider does not work in Adobe InDesign 2020

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#195]
PROBLEM: The font works fine in InDesign if one selects pre-made instances. It also works fine if one uses the Weight or Width sliders in InDesign 2020. However, the font stops working at all in InDesign 2020, if one tries to use the Y Opaque slider, in any way.

What happens? The displayed text changes to the default instance of Science Gothic, and shows all the indications of a "missing font" (pink highlight on the text, style name in square brackets in the font menu).

Moving sliders around at this point has no effect. However, selecting a predefined instance from the font style menu works fine, and "resets" the font to a non-problem state. The it will again work fine with other style selections, or with the Weight and Width sliders. But if one uses the Y Opaque slider, it breaks again.

Note that there are other issues, common to all Adobe apps that do Variable Fonts.

COMMENTS: 

As far as I know, this is not a bug in the font. **The Y Opaque (contrast) axis behaves normally in Adobe Illustrator, so it appears to be an implementation issue specific to InDesign and its text engine.** However, we can’t be sure until/unless we hear back from Adobe.

UPDATES:

This also affects the Slant (italic) axis.
Other font developers have since reported the same issue. We are not alone in this.  See https://indesign.uservoice.com/forums/601180-adobe-indesign-bugs/suggestions/39014530-variable-font-not-working-in-indesign-2020

Reported to Adobe as: ID-4215972

**Comment by kateliev** [comment]
@tphinney to be honest in my work I usually slant everything, except .notdef, my foundry logo and /estimate. Actually I always felt that this is the _normal thing to do_. After all italics should be derived from cursive writing and when you _write_ you usually keep everything (kind of) at the same angle...

But after you requested that _the python script_ should have exclusion list, containing glyphs that should not be slanted, you made me qestion my methods. I've done a little research and found out that it is _more common_ to have glyphs that are indeed not slanted. I also discovered that it is more practical to do so from type designers perspective - having to balance out a slanted multiply sign can loose you a couple of hours :) . As a conclusion I really do not know what to think - you infected me with the idea :) now i think that the _normal thing to do_ is to leave the math upright!

**Comment by tphinney** [comment]
Could be. That did occur to me, I just need to dig back for an old version. I'll try it.

**Comment by tphinney** [comment]
Yes. An older build works ~ okay, with the same axis, but a different name ("Contrast") and a different scale (0-100 with default zero, instead of 18–122 with default 122).

**Comment by tphinney** [comment]
Shared the older font (as well as the newer one) with the Adobe InDesign team.

**Comment by servantb** [comment]
Just noticed that there is both "Regular" and "Regular1" listed in the dropdown menu for SG. (This is in the last version to have axis named Y-Opaque.) Not sure how relevant that detail is. "Regular" doesn't look right, and "Regular1" looks like our Medium.

**Comment by tphinney** [comment]
When you say "Regular" “doesn’t look right,” what do you mean?

And the pre-defined instances seem to be (mostly? entirely?) working fine. It is getting arbitrary instances with sliders that was the problem. But only in InDesign, not Illustrator or web.

**Comment by tphinney** [comment]
(Created a separate issue for the "Regular1" problem—I think it is unrelated.)

**Comment by tphinney** [comment]
(The other issue is recorded in #216, which is fixed now)

**Comment by tphinney** [comment]
Actually, neither Slant nor Y Opaque works in InDesign.
This is still not fixed in the 15.0.1 update just released. Nor has anyone on the InDesign team even responded to the bug report, so far.
So, I checked the main (non-prerelease) InDesign bug report forum, and there was a report there, so I piled onto it. See https://indesign.uservoice.com/forums/601180-adobe-indesign-bugs/suggestions/39014530-variable-font-not-working-in-indesign-2020

**Comment by tphinney** [comment]
Still doesn’t work in InDesign 15.0.2, just shipped the other day.

**Comment by tphinney** [comment]
Sometimes it locks the app entirely!  :(

**Comment by thlinard** [comment]
Maybe the solution I used for Libre Caslon Text could be useful for you?
https://github.com/google/fonts/issues/2391

**Comment by tphinney** [comment]
The InDesign bug was fixed in the 15.0.3 release; closing this.
