### ISSUE TITLE
Alternate /a.slnt (and accented variants)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#197]
Brandon will make the upright version of the new italic /a.slnt, including placing anchors (equivalent to /a anchors). I have already created a placeholder for it.

We will likely later need ".slnt" variants of a lot of derived glyphs:
/agrave /aacute /acircumflex /atilde /adieresis /aring /amacron /abreve /aogonek /aringacute /uni0201 /uni0203 /uni1EA1 /uni1EA3 /uni1EA5 /uni1EA7 /uni1EA9 /uni1EAB /uni1EAD /uni1EAF /uni1EB1 /uni1EB3 /uni1EB5 /uni1EB7 /uni0430 /uni04D1 /uni04D3

**Comment by tphinney** [comment]
We tested it today as far as how the shape holds up during 10° slant. Seems fine. This is good, also applies to bdpq.

Could make accented variants now.

**Comment by servantb** [comment]
I also need to make the /ae variant.

**Comment by servantb** [comment]
Generated accented variants, including Cyrillic.

**Comment by servantb** [comment]
Added ogonek anchor to /a.slnt, and added /aogonek.slnt
Appended "Recipes for auto layers.txt" to include the latter.
