### ISSUE TITLE
Interpolation problems (kinks)

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#202]
This is to serve as a placeholder and collection bin for problems that we find with the interpolation of the "finished" outlines!

**Comment by kateliev** [comment]
So far we know for sure that /K and /k related shapes suffer from kinks.

**/K**
This is in both directions: CndCtr -> :Ctr 
![SG-K-kink](https://user-images.githubusercontent.com/10247582/68486949-defa4300-024a-11ea-93c0-3a720b63e2ee.gif)

and BlkExpCtr  - > BlkCtr
![SG-K-kink-02](https://user-images.githubusercontent.com/10247582/68487207-59c35e00-024b-11ea-8220-23bc5d01a2e2.gif)

...but not beyond. Also interesting enough the effect is not "that" visible in /k

**/k**
![SG-k-kink-01](https://user-images.githubusercontent.com/10247582/68487500-d6eed300-024b-11ea-9d48-81e342b28e79.gif)

this whole problem will affect more or less the following glyphs:
/K /k /uni0416 /uni0436 /uni043A /uni0496 /uni049A /uni04A0 /uni04C1 /uni0497 /uni049B /uni04A1 /uni04DD /uni0436.smcp /uni043A.smcp /uni0497.smcp /uni049B.smcp /uni04A1.smcp /uni045C.smcp /uni04DD.smcp /uni04C2.smcp (... and more)

**Comment by kateliev** [comment]
Submitting three solutions for /K to explore /K.fix_01, /K.fix_02, /K.fix_03.

For me neither works, so I am now more inclined to leave the /K unfixed - simple and more natural than having to outsmart ourselves....

Every suggestion is welcome!

**Comment by servantb** [comment]
I spent a while trying another fix, editing the form to reduce the difference in deltas between the offending points... and as expected it's horrific. Sacrifices any semblance of decent from for a smooth transition.

So yeah, I'm with @kateliev. We leave it and chock it up to the limitations of the technology. Can't have everything.

**Comment by tphinney** [comment]
I think I am in favor of an alternative: leave overlap in the /K
I think the bad interpolations are bad enough that they are worth leaving overlap in.
The question is, how much overlap is required? I think we could merge *either* the arm or the leg with the vertical and not have any problems. We just can't merge the arm and the leg with each other.

**Comment by tphinney** [comment]
I ended up using internal loops to fix /K
Interestingly, they were not needed as far as we have noticed in /k
Anyway, this is better now. If we spot more issues, can re-activate.
