### ISSUE TITLE
/uni0444.smcp is doing something odd at FL compile time

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#203]
When I export a variable TTF directly from FL, I get this:
`WARNING:fontTools.varLib:Masters have incompatible glyph programs in glyph 'uni0444.smcp', hinting is discarded.`

(Haven't tried FL > UFO > FontMake yet, that will be later today)

Looking at the masters, I am not immediately seeing anything wrong. The contours are in the same order in all masters. Each contour has a consistent number of points across masters. The startpoint of each contour is the same in all masters.

**Comment by kateliev** [comment]
@tphinney - Strange enough i did not find anything that would make the glyph incompatible. Changed start points on the inner contours,... did try a lot of things, but then I realized - this is a hinting problem and the "programs" are actually the "TT hinting programs" so i guess this is an error of the auto-hinter used. Cannot help here.

**Comment by tphinney** [comment]
Ah. And also "hinting is discarded" just means the glyph is being left unhinted. It is not being left out of the font. So, not a huge issue, as this is not our primary route to VF compile anyway.

**Comment by kateliev** [comment]
Fixed!
