### ISSUE TITLE
Check vertical position of /ordfeminine and /ordmasculine and adjust if necessary.

### ISSUE THREAD

**Issue by servantb** [tphinney/science-gothic#204]
The ordinals may be a bit low. Check other fonts for reference and adjust vertical position of /ordfeminine and /ordmasculine as necessary.

**Comment by tphinney** [comment]
I was looking at this. It seems that there is a fair bit of disagreement as to the correct vertical positioning!

I originally went with what I was used to, which I think I inherited from Robert Slimbach. I just checked one of his more recent sans designs, Acumin, and it has very similar positioning and sizing.

However, I see that Linotype's Avenir and Paratype’s PT Sans Caption both go substantially higher. they align the top of the ordfeminine and ordmasculine with the top of the numbers.

Then again, looks like URW goes much lower! At least, in URW Franklin Gothic Book Condensed, it is as much lower than SG, as SG is lower than Avenir and PT Sans. So ...  ¯\_(ツ)_/¯

**Comment by tphinney** [comment]
After further research as described above, I am inclined to leave this, for now. I think it is at least "ok"; @servantb ?

**Comment by servantb** [comment]
I'm inclined to align them with the top of the figures. I've done some research, and it feels like the preference (leyendo en Español) is to have los números ordinales aligned at the top.

Beyond that, there is little to no design relationship between the figures and the ordinals at the current height. Even in the examples above it largely appears haphazard. If the ordinals were aligning to the center of the curve on top of the 2 or 3, or the aperture of 5, but they aren't. Not quite. And they feel off. Not only that, but they can't align vertically centered to the upper curve of one figure without being misaligned to the curve in another.

All this to say, from a layout design perspective, it seems good to align to the top.

**Comment by tphinney** [comment]
OK, sold. I'll take care of that.

Hmmm, I'll have to be sure to move the italic ones along the 10° slope while raising them!

**Comment by tphinney** [comment]
The slope compensation made it a bit time-consuming. Typerig did the verticals super quickly, though.

**Comment by servantb** [comment]
I didn't expect the ascender alignment, as I was thinking align to figure height, but it looks great!
