### ISSUE TITLE
UFO Prepare flags 11 glyphs

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#208]
Before conversion to TT outlines, UFO Prepare script is OK with all glyphs in the font.
After FontLab TT conversion, it complains about these 11 glyphs and removes them:

Incompatible Glyphs (removed): /abreveacute.slnt /grave /hungarumlaut /uni02C7 /uni040C /uni0450.smcp /uni045D.smcp /uni1EAE /uni1EAF.smcp /uni1EB2 /uni1EB3

@kateliev could you investigate? Is there anything we should do pre-conversion that would help? Or something easy to do post-TT-conversion? Why these Auto Glyphs only? Structurally they seem identical to many others that go through without problem.

**Comment by kateliev** [comment]
Working on it - identified some issues, other remain misery. I think the problem stems from cascading references of elements and also auto recipes deactivated (or active without logic) on some layers and missing on others.

**Comment by tphinney** [comment]
I believe this is fully fixed now, as I recall from my build last night.  :)
Will open a new issue if there remains a problem.
