### ISSUE TITLE
Over-slanting, Reverse slanting

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#209]
It seems that slanting errors are inevitable. Mainly there are two kinds of problems:

- **Slanting in reverse**: Affected are glyphs that use reflection. Identified: _/uni042D /uni044D /uni044D.smcp_  and fixed!
-  **Over-slanting**: Affected are glyphs that are composite of others. They get slanted as well as their parents, so slant applied is x2 (sometimes x3). I have written a script to detect those.
![image](https://user-images.githubusercontent.com/10247582/69063725-a82fe400-0a25-11ea-8097-49c8b5cf3331.png)
..and collected them under the tag _overslant__fix_
![image](https://user-images.githubusercontent.com/10247582/69063773-bc73e100-0a25-11ea-9c5e-f1e991ef076c.png)

Identified so far:
_/Ccedilla /D /Eth /brevecomb_acutecomb /brevecomb_acutecomb.case /brevecomb_gravecomb /brevecomb_gravecomb.case /brevecomb_hookcomb /brevecomb_hookcomb.case /brevecomb_tildecomb /brevecomb_tildecomb.case /circumflexcomb_acutecomb /circumflexcomb_acutecomb.case /circumflexcomb_gravecomb /circumflexcomb_gravecomb.case /circumflexcomb_tildecomb /circumflexcomb_tildecomb.case /dcroat /divide /equal /exclamdown.case /franc /gravecomb /gravecomb.case /guillemotleft /lessequal /lira /macron /notequal /ohorn /ohorn.smcp /plusminus /questiondown.case /quoteleft /quoteleft.smcp /quoteright /quoteright.smcp /quotesingle.smcp /sterling /sterling.alt /tbar /tbar.smcp /uhorn /uhorn.smcp /underscore /uni030B /uni030B.case /uni030C /uni030C.case /uni030F /uni030F.case /uni0311 /uni0311.case /uni0312 /uni0312.case /uni0323 /uni0323.case /uni032E /uni032E.case /uni0331 /uni0331.case /uni0335 /uni2033 /uni2052 /uni20A9 /uni20AE /uni2212 /yen_

**Comment by kateliev** [comment]
Most errors also roo in Auto recipes being disconnected/disabled. I am fixing most of these as I write this...

**Comment by kateliev** [comment]
Also a healthy reminder - not all of these are broken!.... but Python can report that much - they need to be examined by human :)

**Comment by tphinney** [comment]
Some (many? most? nearly all?) auto recipes that I both created and disabled, I disabled so as to allow for manual fixes to positioning of components. Sometimes the auto recipe was a good "start" but could not be easily tweaked to allow for proper relationships. Example: the positioning of the double acute, both in absolute x-terms, and the two acutes relative to each other.

So, if you are re-enabling auto recipes, it would be good if we knew which ones so I can check that all is well. In at least some cases, just knowing the glyph, I will remember if it needing manual tweaks.

**Comment by tphinney** [comment]
This has been nearly entirely fixed by @kateliev ! However, there are still a handful of glyphs that have problems with double-slanting in the "S" masters. I have reviewed the glyph complement, and I spotted these:
/quoteright
/quoteright.sc
/uni02BC
/quotedblright.sc

Also, I did found a few guillemot-based Auto Glyphs with internal spacing adjustments, that were messed up by becoming full Auto Glyphs again:

/guillemotleft /guillemotright /guillemotleft.case /guillemotright.case

That's it! Nearly done.  :)

**Comment by kateliev** [comment]
Fixed! Overslant + SBs + recipes (where needed): /quoteleft /quoteright /quoteleft.sc /quoteright.sc /uni02BC /guilsinglleft /guilsinglright /guillemotleft /guillemotright /guilsinglleft.case /guilsinglright.case /guillemotleft.case /guillemotright.case /uni0335 /quotesingle.sc /underscore /uni0331.case /uni0304.case /uni0331.case  /uni0304.case /Eth (rebuild)
