### ISSUE TITLE
Master relationships proportions may need a tweak

### ISSUE THREAD

**Issue by IgorFreiberger** [tphinney/science-gothic#21]
Accordingly to our master relationship guidelines, a condensed glyph should be 51% of a medium. This proportion is not followed in O, for example: medium is 726u, condensed should be 370u but it is 363u. 

The problem gets bigger when we adopt the same proportion in letters like B, P, or R, which counters become too thin:

<img width="542" alt="SG – POH condensed" src="https://user-images.githubusercontent.com/27840848/62839407-d3a17680-bc5f-11e9-8d83-c12d4e6da6bb.png">

To achieve consistency, we need to use a different proportion in order to allow the same counter and stems of O/H.

**Comment by tphinney** [comment]
These are just *guidelines* and not requirements. Do what looks good with the other glyphs!
In the case of O, it has a nice open middle with nothing interfering, so it "looks wider" and can get more condensed than some characters.

I have it in my notes for example (and was going to file an issue) about the Medium Condensed "H" looking just a little too narrow compared to... well, pretty much everything.  :P

**Comment by kateliev** [comment]
Why can't we rely on individual designers good taste. Guidelines should be optional if the result is not aesthetically satisfying?!

**Comment by kateliev** [comment]
Sorry closed by incident!

**Comment by tphinney** [comment]
Well, that is why the width info is “guidelines” rather than “rules”.  ;)

Igor, if you feel this all answers your question, feel free to close.
