### ISSUE TITLE
Some anchors did not get slanted

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#212]
Some glyphs did not get (all) their anchors slanted, because the anchor horizontal position was "width/2" or possibly in some cases "width/2" in some formula. EDIT: Also "width/1.9" and others.

At least some masters of /W and /Z are affected. Doubtless other glyphs. 

@kateliev any ideas about how to automate fixing? Or at least, identifying the problem glyphs? Fix the simple ones and ID the others?

**Comment by tphinney** [comment]
@kateliev Is there any way to search for this globally and get a list?

**Comment by kateliev** [comment]
@tphinney will do!

**Comment by tphinney** [comment]
OK, please do, and maybe give some thought as to the best way to fix?

If it is just a couple of glyphs, we could do it by hand. If it is more ... could script it.

You could script some simple trigonometry math to set the new position. Clear (or evaluate) the expression to get the old X value "XO" and then:

XO = X value (original, old)
XN = X value, new
H = height

I think we will find this algorithm gives the desired value:
XN = H × (tan 10°) +  XO

(Showing this to my kids to demonstrate the utility of trigonometry!)

**Comment by kateliev** [comment]
So gar i could not find a way to find the anchors by recipe. Regretfully Anchor recipes are not accessible from Python API

**Comment by tphinney** [comment]
Rats. Well, I fixed /K while doing other work on it.

**Comment by tphinney** [comment]
I have done a manual check through all slanted masters. I believe the following glyphs need fixing:
/O (incl horn!) /Z 
cap combining caron
cap combining dot below
lowercase combining dot below
lowercase combining caron
cap (only) inverted breve
cap double grave
lowercase double grave
Check multi-accent combos (may be precomposed double accents?) for: /uni1EA4 /uni1EA6 /uni1EA8 /uni1EAA

maybe /gravecomb

**Comment by kateliev** [comment]
/O /W /Z fixed! I prefer to leave the accents to @tphinney

**Comment by tphinney** [comment]
Fixed positioning for my next check-in: /uni030C.case /uni030C /uni030F

**Comment by tphinney** [comment]
I checked those in. Will finish today.

**Comment by tphinney** [comment]
/uni030F.case (double grave) fixed for next check-in. Positioning was off in the upright, sometimes by a lot!

**Comment by tphinney** [comment]
The other “real” issues listed in the bug have already been fixed by @kateliev ; things listed to investigate are all in fact OK. In some cases, both the anchors AND the outlines differ by a couple units from the slant-line, but that means attachment will be unaffected, so it seems fine.
