### ISSUE TITLE
Some small cap glyphs too narrow in: :Cnd :CndCtr :CndS CndCtrS (and possibly others?)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#218]
Brandon notices, and I agree, that the small cap glyphs are oddly a bit narrow in some Condensed masters. At least some of them, arguably a lot of them, in the affected masters.

Black condensed is fine. But at least initially, in some masters, the small cap counters are narrower than the lowercase equivalents, and it just seems ... wrong.

We addressed /c.smcp and /s.smcp in the :Cnd & :CndS masters, manually. But there is more to be done, both more masters (:CndCtr :CndCtrS) and more glyphs. 

At least: /d.smcp /j.smcp /u.smcp in all four masters
+  /c.smcp and /s.smcp in CndCtr and CndCtrS

**Comment by tphinney** [comment]
Let's tackle this together as soon as our schedules permit

**Comment by servantb** [comment]
Widened /d.sc /j.sc /u.sc in :Cnd, :CndCtr, :CndS, & :CndCtrS;
and /c.sc & /s.sc in :CndCtr and :CndCtrS

**Comment by tphinney** [comment]
Looks good!
