### ISSUE TITLE
Script to build italic axis

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#22]
Vassil has delivered an initial version
https://github.com/tphinney/science-gothic/blob/master/scripts/sg-toolbox/SG-BuildItalicAxis.py

**Comment by tphinney** [comment]
Duplicate!

**Comment by tphinney** [comment]
I need to test this, AND have it in place and in use, for the next milestone!

**Comment by kateliev** [comment]
I think we are done here!
