### ISSUE TITLE
`wght` defaults to 459.302001953125

### ISSUE THREAD

**Issue by RoelN** [tphinney/science-gothic#225]
Probably not intended, but in [this version](https://github.com/tphinney/science-gothic/commit/9182174b0feb4d3a0d272dffb1a0de493dbab1d7) I'm getting a rather specific value for the default weight:

![image](https://user-images.githubusercontent.com/4570664/71090073-79cb3300-21a2-11ea-8352-214511fc4fe6.png)

**Comment by tphinney** [comment]
Ouch. Yes, obviously the default weight is off! Thanks. (Everything else is as expected.)

**Comment by tphinney** [comment]
@RoelN what app or tool were you viewing that with, btw?

**Comment by RoelN** [comment]
Why, https://wakamaifondue.com/ of course 😎

**Comment by tphinney** [comment]
Ah, of course!

Anyhow, this was fixed a while back. Default weight is again 400, which resolved several issues. (I am no longer as happy with the progression of weightclass vs actual stroke thickness, but at least a bunch of bugs are fixed.)
<img width="1001" alt="Screen Shot 2020-02-10 at 10 29 30 AM" src="https://user-images.githubusercontent.com/6548266/74178336-40d29c00-4bf0-11ea-93a7-466f9bcc7173.png">
