### ISSUE TITLE
Optical compensation needed to vertical stems in O:Lt Exp

### ISSUE THREAD

**Issue by IgorFreiberger** [tphinney/science-gothic#23]
**Master Lt Exp**: in O, horizontal stems are 20u, the same as vertical ones. In all other uppercase letters, horizontals are 18u.

**Comment by IgorFreiberger** [comment]
I already fixed it in my file.

**Comment by tphinney** [comment]
Somehow Igor's fix got lost? But I fixed it again today.  :P  Should be good.
