### ISSUE TITLE
FontBakery complains about Unicode and MacRoman being non-ASCII

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#238]
* [1;91;107mFAIL[0m: Bad string at [nameID 0, 'mac_roman']: 'b'Copyright &#169; 2019 Font Detective LLC.'' [code: bad-string]
    * [1;91;107mFAIL[0m: Bad string at [nameID 0, 'utf_16_be']: 'b'Copyright &#169; 2019 Font Detective LLC.'' [code: bad-string]
    * [1;91;107mFAIL[0m: There are 2 strings containing non-ASCII characters in the ASCII-only NAME table entries. [code: non-ascii-strings]

**Comment by tphinney** [comment]
Addressing it anyway, as the noted approach is not problematic—even if the complaint does seem bogus.

**Comment by m4rc1e** [comment]
Since the family is ofl, we expect the copyright to follow, https://github.com/googlefonts/gf-docs/tree/master/Spec#font-copyright

**Comment by tphinney** [comment]
@m4rc1e  I don’t really care much in regard to Science Gothic, as it is being produced specifically for Google, so I don’t really mind.

That said, I am not really getting the connection between “OFL” and the spec. I have reviewed the OFL, and it is not particularly explicit about allowing or disallowing different formats of copyright notice. The examples in the OFL include using "(c)" —which is the ASCII equivalent of "©". Then again, I have been told by IP lawyer Donna Kolnes (who was the lawyer for font issues at Adobe for maybe 20 years) that "(c)" has zero legal value, and should never be used.

Also concerned that the FontBakery complaint is not about the specific character, but about _using any non-ASCII character_. This seems horrifically anglocentric, as it means the names of some copyright holders can’t be properly represented, either. It just seems so weird to do this with a text field that is very specifically _not_ ASCII.

**Comment by m4rc1e** [comment]
@tphinney If developers are not making fonts for Google Fonts, they should be using `fontbakery check-universal` instead. This profile accepts non-ascii characters.

@felipesanches Thomas raises a good point here. Even if we stick with our current copyright schema, what happens if a project name includes a non-ascii character? e.g

`Copyright 2020 The Nöma Project Authors (https://www.github.com/googlefonts/noma)`
