### ISSUE TITLE
Left sidebearings in light masters

### ISSUE THREAD

**Issue by IgorFreiberger** [tphinney/science-gothic#24]
As we started building light masters reducing the vertical stems in both directions, the LSB are far larger than they should be. Wouldn't be better to adjust them now, before doing more glyphs?

**Comment by tphinney** [comment]
At least *some* of the Light masters and others are partly OK, because sidebearings were all handled via linking, and the H was deliberately designed from the beginning.

See also #26 about linking sidebearings and doing so consistently.

**Comment by tphinney** [comment]
Actually, at least for current purposes, I am going to call this done (reviewed by Brandon and me).

Spacing will need to be revisited, I'm sure—in Light masters and elsewhere. But it is improved and will work for now.
