### ISSUE TITLE
Any chance of getting versions of the font with specific unicode ranges?

### ISSUE THREAD

**Issue by ryanfiller** [tphinney/science-gothic#256]
I'm trying to set this up on my end to post-process the ttf file, but I would _love_ a Latin only version of this font - https://github.com/doasync/font-ranger#usage

Any chance of this happening and being hosted in this repo? I can help in any way.

**Comment by tphinney** [comment]
So, good news and bad news.

Good News: this project was commissioned for Google Fonts, so eventually one assumes it will be hosted by them, and after that, you will be able to quite automatically get a Latin-only version through the Google Fonts API.

Bad News 1: That will be some time off; currently the Google Fonts API only supports a variable weight axis, not width and certainly not arbitrary axes. There is no public timeline for this.

Bad News 2: Although I am sympathetic to your need, mostly I need to Get The Font Done. We are in the long cold night of 36 Masters of Kerning Hell, with other distractions. I really ought to focus on kerning first, and not get distracted by other cool things.

Bad News 3: Science Gothic being a variable font, and having designspace alternates for that variability, in a universe where this is not yet common, means that most currently-existing subsetting tools either: (A) drop SG’s variations altogether; or (B) keep the variations but drop the designspace alternate glyphs. What are these? In SG, /a and /f get alternate forms when slanted. /Q and /dollar have alternate forms when they get more bold/condensed—in fact, /dollar has three forms altogether. Subsetting tools that are not sufficiently variable-aware are going to lose these.

So for example, the famous Font Squirrel webfont generator does subsetting, but appears to not support variable fonts at all—it dropped all the additional masters and flattened the font when I tried it on the latest Science Gothic ttf.

At the moment, it looks like FontRanger is in the second category—at least from another relatively quick-and-dirty test on my part. It appears to make a valid, working variable font subset, but the designspace alternates functionality is lost. Minor issue for the /a and /f, while glyphs such as /dollar and /Q suffer a bit more, in some parts of the designspace.

Here is the full list of glyphs with designspace variations: 

/Q
/q.smcp
/dollar
/cent
/colonmonetary
/uni20B1 (peso)
/uni20B2 (guarani)
/uni20B5 (cedi)

/f
/a
and all the accented/diacritic variations of /a

**Comment by ryanfiller** [comment]
Thanks for the response!
That's good to know that FontRanger can atleast get close, and a little disappointing about the rest - especially Google only supporting on axis. I might play around with this some more and I'll let you know what I find.

**Comment by tphinney** [comment]
Please do! If you do find something that does a better job of subsetting, it would be handy to know about.

And if we get more automation, up to the point that a subsetted version would be easy to add to our builds, I will consider it, for sure.
