### ISSUE TITLE
Web site: improve overlapping text

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#257]
I am still experiencing viability problems with http://www.sciencegothic.com/ namely the text content not fitting inside the designated boxes.
![picturemessage_2xo3niuh ucg](https://user-images.githubusercontent.com/10247582/77671958-fbe0aa00-6f90-11ea-930d-86a7c3312b52.png)

Discussing the issue with @tphinney we have come to agreement that if this is not technically possible in some way, it will be better that the main title "Science Gothic" be positioned on top of all other page elements, so it all looks like "deliberate" design decision.
![picturemessage_1wodimir gbo](https://user-images.githubusercontent.com/10247582/77672003-0733d580-6f91-11ea-89be-041e4a48ad28.png)

I do also suggest adding a drop shadow of some sort, to avoid further collisions - white-on-white as shown below:
![picturemessage_one53uuf dzl](https://user-images.githubusercontent.com/10247582/77672141-2e8aa280-6f91-11ea-8403-3088d30fc45b.png)

Adding a blurred drop shadow with the same color as the main background would make the effect "subtle" unless "conflict" occurs
![picturemessage_r01krh5m 4r5](https://user-images.githubusercontent.com/10247582/77672272-5da11400-6f91-11ea-9981-e2b89c9fcb4c.png)
![picturemessage_jnwi00sc 2yw](https://user-images.githubusercontent.com/10247582/77672279-609c0480-6f91-11ea-91dd-55ef07c15e4b.png)

**Comment by tphinney** [comment]
Fixed
