### ISSUE TITLE
1 step builds

### ISSUE THREAD

**Issue by m4rc1e** [tphinney/science-gothic#258]
So I've found https://github.com/tphinney/science-gothic/blob/master/documentation/compiling_fonts.md. It would be great to turn this into a shell script (as many steps as possible). I've browsed #91 already and could only find this documentation.

**Comment by tphinney** [comment]
Agreed. Although we do use a UFO + FontMake workflow, we have not automated it.

I don’t think we can quite get to one-step builds, but we could get pretty close. How about two scripts?

1) a FontLab script for the FontLab parts. As well as version bumping, the script will run Font: Check QA script, and only completes successfully if that finds no problems—if it does the script will terminate and manual intervention is required.

2) a shell script for running the rest of the scripts/stages after.

**Comment by tphinney** [comment]
@kateliev is on it. (May be several days before we get an update, though.)

**Comment by tphinney** [comment]
I have done more in this area since, as well. Although the FontLab steps are not automated, everything else is, even copying files from various build locations to the repo staging.
