### ISSUE TITLE
Website: "sciencegothic.com" should redirect to "www.sciencegothic.com"

### ISSUE THREAD

**Issue by arrowtype** [tphinney/science-gothic#259]
Very cool site!

Right now, however, if I visit the site on a cold cache, I get a 403 error:

![image](https://user-images.githubusercontent.com/45946693/80222589-156b2500-8615-11ea-8d63-c5dee61fadd7.png)

Once I visit "www.sciencegothic.com," I reach the site, and subsequently, if I type in "scie..." it autocompletes/resolves to the correct domain.

I'm guessing that the domain DNS isn't quite set up to redirect the non-www URL to the www URL, but usually, that is fairly quick to fix.

**Comment by tphinney** [comment]
I have added a redirect:
“/” on “sciencegothic.com” redirects to “https://www.sciencegothic.com”.
Pretty sure this is all better now. Thanks for pointing out the problem!
