### ISSUE TITLE
Interpolation issue in semicolon

### ISSUE THREAD

**Issue by guidoferreyra** [tphinney/science-gothic#263]
Hi, just found this repo and downloaded and dowloaded the binaries from here https://github.com/tphinney/science-gothic/tree/master/fonts/variable/UFO%20FontMake

I dropped the font on FontGoggles and I saw when using the weight axis the dots in the semicolon are interpolating wrongly due to a different contour order.

Probably you already know, but fill this issue doensn‘t cost me anything :)

**Comment by tphinney** [comment]
Thanks for the bug report! I think we had missed that. I will have to take a look. Might not get fixed right away as I am deep on something else right now, but soon!

**Comment by servantb** [comment]
Thanks for the heads up, @guidoferreyra! I've fixed that in the VFJ, and we'll have the new builds... soonish.

**Comment by kateliev** [comment]
This is now done! You could close the issue after build!
