### ISSUE TITLE
Some kerning tight in ThinCnd (and somewhat in Cnd)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#268]
Thin Condensed: Looks like the AV is *way* too tight. LT, CA AT are all just a little tight:
![Screen Shot 2020-09-02 at 9.25.44 AM.png](https://images.zenhubusercontent.com/55f8a29e4f7a08fbb7f4ebd1/eaef0da6-7e25-463d-938a-d29f99506469)

Regular Condensed: less problematic, but AV is still a bit too tight, LT a bit as well:
![Screen Shot 2020-09-02 at 9.26.14 AM.png](https://images.zenhubusercontent.com/55f8a29e4f7a08fbb7f4ebd1/b10cbc9b-bc43-490d-968c-ccf21272219f)

This presumably affects the corresponding Ctr and Slnt masters as well.

**Comment by kateliev** [comment]
@tphinney hmm this is rather strange... I cannot confirm that
From within **Fontlab**:
![image](https://user-images.githubusercontent.com/10247582/92031221-f2920f80-ed70-11ea-838b-ef90b820086e.png)

From **http://www.sciencegothic.com/** as viewed on Edge (and the same on Chrome) Win10:
![image](https://user-images.githubusercontent.com/10247582/92031330-1bb2a000-ed71-11ea-90d4-c0392354afbd.png)

this looks like the kerning is applied twice or some extreme tracking case...

**Comment by tphinney** [comment]
Oops, forgot to update the bug! As discussed in chat, turned out to be a browser caching issue. So, is OK.
