### ISSUE TITLE
Double 99 quotation marks colide when slanted.

### ISSUE THREAD

**Issue by Lululalu** [tphinney/science-gothic#275]
But the 66 is ok.

![Screenshot 2022-01-15 000844](https://user-images.githubusercontent.com/32398857/149606811-f61751ec-ed64-453e-8d46-c45f4d8d7c2a.png)
![Screenshot 2022-01-15 000907](https://user-images.githubusercontent.com/32398857/149606812-09d74082-059e-4118-8045-f106cbdedca3.png)

**Comment by servantb** [comment]
I have an idea as to what’s going on here. I’ll look into it. Thanks!

**Comment by servantb** [comment]
Looking through the issues list, this appears to be a subset of Issue #229. So we’ll just go ahead and file this as a duplicate.
