### ISSUE TITLE
Check and probably fix order of axes ('slnt' should be second, not last)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#280]
Currently it is: YOPQ,wdth,wght,slnt
I suspect maybe it should be: YOPQ,slnt,wdth,wght

I believe the rule is unregistered axes first, but alphabetical within each group.

**Comment by tphinney** [comment]
Fixed VFC with https://github.com/tphinney/science-gothic/commit/d9e4da2584e3c513de1c3a313564c968146daf22
However, still need to do a new TTF build to pick that up, downstream.

**Comment by tphinney** [comment]
Well, the latest TTF has the filename with the axes in the right order, but the actual axis order in the font is wrong.  :(

**Comment by kateliev** [comment]
@tphinney regretfully i saw this one too late. Fixed in VFC dc41ca2c05970302b7b035b40806e08f98322554, but regretfully did not go into todays build 5c3f7d0b525de056da30cc58d6a3da2d0c3b9c67.

**Comment by tphinney** [comment]
I thought I had fixed it in the VFC myself! but checking a subsequent build, discovered I was mistaken.  :(

**Comment by tphinney** [comment]
Verified that the latest fonts do have this right.  :)
