### ISSUE TITLE
v1.005 Interpolation issues - 0497 04B3 + 04B3.sc

### ISSUE THREAD

**Issue by kenmcd** [tphinney/science-gothic#289]
v1.005 Interpolation issues - 0497 04B3 + 04B3.sc
File: ScienceGothic[YOPQ,slnt,wdth,wght].ttf - v1.005 (2022-04-13)
Glyphs: uni0497, uni04B3, uni04B3.sc 

![2022-04-14_15-19-34](https://user-images.githubusercontent.com/844920/163487034-265cd856-37c1-4e9e-8d90-7e9c58fcf38c.gif)

**Comment by kateliev** [comment]
Thank you @kenmcd for catching this! These bugs are now fixed in our latest build v.1.06 5c3f7d0b525de056da30cc58d6a3da2d0c3b9c67. Please verify and close the issue :)

**Comment by kenmcd** [comment]
All look good now. Closing.
