### ISSUE TITLE
extend x y v (lc) to all masters

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#29]

**Comment by servantb** [comment]
Pushed v y to master.

**Comment by servantb** [comment]
Pushed x to master. Will review.

**Comment by tphinney** [comment]
Some feedback on the 'x' crossover and optical compensation there. First let me say it is coming along well, and this is a hard glyph. About half the masters are already perfect. For the remainder, here are my thoughts....

more offset needed needed in Cnd Ctr
tiniest bit more offset needed in Blk Cntr
tiniest bit too much in Cnd, Blk Exp
too much in Blk, Bk Cnd
WAY too much offset in Blk Cnd Ctr, Blk Exp Ctr

And in the Medium, I think maybe it needs more offset for the stroke from bottom left to top right?
