### ISSUE TITLE
v1.005 Interpolation issue - oslashacute.sc

### ISSUE THREAD

**Issue by kenmcd** [tphinney/science-gothic#290]
v1.005 Interpolation issue - oslashacute.sc
File: ScienceGothic[YOPQ,slnt,wdth,wght].ttf - v1.005 (2022-04-13)
Glyph: oslashacute.sc
Appears the acute is too high in **Thin** and **:yo=18,wd=100,wt=400,sl=0** masters

![2022-04-14_15-34-34](https://user-images.githubusercontent.com/844920/163489028-7b7b6af2-edd7-427b-9244-55f84344ec2b.gif)

**Comment by kateliev** [comment]
Thank you @kenmcd for catching this! The bug is now fixed in our latest build v.1.06 5c3f7d0b525de056da30cc58d6a3da2d0c3b9c67. Please verify and close the issue :)

**Comment by kenmcd** [comment]
Looks good now. Closing.
