### ISSUE TITLE
Latin Small Letter B (0062) is still TrueType curves

### ISSUE THREAD

**Issue by kenmcd** [tphinney/science-gothic#296]
The Latin Small Letter B (0062) is still TrueType curves after the conversion back to PS curves #279.
And appears to be the same in all masters.
It is the only character I have found which is like this.
All others (that I have checked) appear to be PS curves. 
Very odd!
Below is from the VFC file posted 2022-04-19.

![2022-04-30_10-53-41](https://user-images.githubusercontent.com/844920/166117040-ce671efa-7771-4b6b-af2e-ff23e793220e.gif)

**Comment by tphinney** [comment]
Dang. Not sure how that got missed, but we will take care of it in our next go-round.

Unfortunately we are busy again on other projects, also for Google (Material Symbols). But I _hope_ we can finish up Science Gothic some time in the second half of 2022. It is sad to be super close to being done, but not actually finished!

**Comment by kateliev** [comment]
Fixed! Thank you @kenmcd
