### ISSUE TITLE
Some incompatible masters for glyphs in progress

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#297]
The following glyphs are reported by our audit utility as having incompatible masters:

/ulna_radius_alt/ulna_radius/tibia_alt/tibia/skull/skeleton/rib_cage/rheumatology/radiology/orthopedics/humerus_alt/humerus/hand_bones/foot_bones/femur_alt/femur/dentistry/edit_square/edit_document

If you don’t get to this on your Monday, I will look at it on my Monday.

EDIT: Ah, I see most of these are just placeholders for new glyphs not yet done.

**Comment by servantb** [comment]
I think this is the wrong repo for this issue. 😉

**Comment by tphinney** [comment]
LOL. oops.
