### ISSUE TITLE
/question mark ? extend to all masters

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#32]

**Comment by servantb** [comment]
Added /? to master.

**Comment by tphinney** [comment]
Generally, the /question is looking and working great!

I do see one small issue. In the :BlkCnd (and probably :BlkCndEtc) the width of the upper counter goes down to 65 units. This seems too narrow. /n only goes down to 100, /m only to 90. I think 90 or 100 would be a reasonable minimum.

**Comment by servantb** [comment]
It needed more, yes. I only did 85, because of the amount of whitespace opening below the counter.

**Comment by tphinney** [comment]
OK! It looked wrong at 65. I can believe 85 may be just fine, will take a look.

**Comment by servantb** [comment]
We made updates to this the other day, and @tphinney and I called it good.
