### ISSUE TITLE
Revisit 3 5 6 for compatibility with current masters

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#34]
These glyphs were done early on as prototypes. They may need tweaks to match the latest masters, especially (but perhaps not only) in terms of the width variants.

Since Brandon did the originals for 5 and 6, he has first call on this, if he can get to it.

**Comment by kateliev** [comment]
Three (3) needs to be further designed. In its current state, it is not looking good. Middle horizontal stroke needs to be extended for more balanced and aesthetically pleasing look. Also curves connecting to straights have an very obvious "bone" effect.

**Comment by tphinney** [comment]
Vassil, do you mean in all masters? Or if not, which? 

(Reminder: The “Medium” central design is a pretty direct digitization of Benton’s original. Usually I take him to be a better type designer than any of us, especially in his mature later work. Although of course even he could make a mistake.)

**Comment by kateliev** [comment]
The three (3) is not looking good on all of the masters, even in the Medium (original scan). I am not arguing with the skills of the "master" - it is just different people have different intentions in time and we do not know his, when he designed the three for Bank Gothic (BG). Yet we are now here... and we know our intentions... as we are slowly departing from original BG design and diving into new depths, I think it might be better for us to correct it.

**Comment by kateliev** [comment]
Medium is Good as well as Light and Extended, but the Conds, Blacks and Contrasts are not. They need a longer middle horizontal.

**Comment by tphinney** [comment]
I'll fix the 3 right now.

**Comment by tphinney** [comment]
OK, I think the 3 is much better. Will be checked in at my end of day.

**Comment by servantb** [comment]
Igor mentioned a kink in the 5 Blk Cnd Ctr. I've just fixed that. Will push at end of day.

**Comment by tphinney** [comment]
That's done now.

@servantb Care to check the 6?

**Comment by servantb** [comment]
Checked and fixed 5 and 6. There were a lot of things.

**Comment by servantb** [comment]
The width of the /3 in all of the :Cnd and :Exp masters needs adjustment. The /3 also needs corrected overshoots in many of the masters.

I'll get on that.

**Comment by servantb** [comment]
Tweaked a couple of widths in '5' and '6'.

In the '3': adjusted widths in the Cnd and Exp masters, corrected overshoots, and made sure Ctr masters had 36u thin strokes.

(Pushed to master)

**Comment by servantb** [comment]
@kateliev I know you had thoughts on the /3 earlier, and I had to make width changes including the length of the middle stroke. Would you like to take a look before we close?

**Comment by servantb** [comment]
I think we're done with this. Going to close it.
