### ISSUE TITLE
0 1 2 4 7 8 9 need to be extended

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#35]
Originally: 0 1 2 4 7 8 9 only existed in "Medium" master.
People could claim some or all of these numerals.
Remaining: /four /seven

**Comment by IgorFreiberger** [comment]
Let them with me! :-)

**Comment by tphinney** [comment]
Looks like zero, one and nine are ready for review?

**Comment by IgorFreiberger** [comment]
I want to do a last check in proportions of zero, but they are ready. Probably it will better to review with 2 and 7 also ready, which I will conclude tonight.

**Comment by tphinney** [comment]
/two looks lovely. But it seems like it could get the new treatment of :Lt round shapes we are introducing? Also /eight could get that.

**Comment by servantb** [comment]
I've gotten pretty intimate with the /6, so I'll take the /9.

If I can get through some other things, and if you don't mind, @IgorFreiberger, I could take the /8 since I did the /S and /s.

**Comment by servantb** [comment]
Extended /9 and pushed to repo.

**Comment by tphinney** [comment]
/eight is also done.
Just /four and /seven left now.

**Comment by tphinney** [comment]
I finished /four and /seven today.

**Comment by servantb** [comment]
Looks good to me. Thanks, @tphinney.
