### ISSUE TITLE
Inconsistent descender depth for black weights: check /p /q /thorn /g /j

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#40]
Some black weights have a descender of -404, some have -428 (same as other weights).

[EDIT: We are standardizing at -428, same as other weights. Will increase ascenders on the black to make up for the x-height diff.]

The reason for less descender is (indirectly) because the black styles have a higher x-height (1024 instead of 1000). But the ascender value is unchanged. So they have shorter ascenders because of the larger x-height.

If the descender is kept the same in the black, they will have longer descenders than they have ascenders! That would be bad and weird.

But then again, that slight difference is very helpful in keeping the "j" working well in the black. Its horizontal section in the descender would need to be thinner, if it moves up vertically 24 units.

Anybody have any ideas about a better way to solve this?

**Comment by kateliev** [comment]
24 units is nothing in comparison to the 2000UPM we are using. If they look good i vote to keep them. If they don't we should change them. For me it all depends on their overall fit together with the other characters of the face.

**Comment by IgorFreiberger** [comment]
24u become relevant if we are talking about a small counter are, like /g.

**Comment by tphinney** [comment]
Yes, it can be quite visible for /g and /j.

Another option could be to increase the ascenders on the :Blk to compensate for the increased x-height, then the descenders don't need to shorten.

**Comment by servantb** [comment]
Increasing ascenders seems like an easy enough solution, but would it cause problems for glyphs like /hcircumflex or /lacute?

Honestly, I don't think it looks bad. It's only slightly noticeable if you're looking for it, and even then I think it looks fine.
![Screen Shot 2019-09-05 at 10 12 17 AM](https://user-images.githubusercontent.com/50463501/64363498-b42f0c80-cfc5-11e9-9be6-15ef0e4ae9c1.png)

**Comment by tphinney** [comment]
Yes, it would affect some diacritics, but those are being handled via anchor attachment anyway, so... no worries. We  would just have to adjust the anchors at the same time we move the ascenders.

TypeRig will be a great help with this.

@servantb Can you create a new issue for that?

**Comment by tphinney** [comment]
So now, need to make sure all :Blk (etcetera) descenders are at -428. No -404.

**Comment by tphinney** [comment]
Fix checked in. I am reasonably confident this is done.
