### ISSUE TITLE
Masters arrangement and colors

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#41]
I have rearranged the masters in _Layers & Masters panel_ so they follow some common sense logic, to aid the designer. Also have colorized them according to their Axis relations.

![image](https://user-images.githubusercontent.com/10247582/63152069-9e0bdd00-c013-11e9-8d45-4476eaa9b5d9.png)

**Comment by kateliev** [comment]
You can now effective use either Bar or Background in Prefs> Variations > to distinguish easily between masters.

![image](https://user-images.githubusercontent.com/10247582/63152178-dca19780-c013-11e9-8791-01c22264684a.png)

**Comment by tphinney** [comment]
Seems like the order of masters gets out of sync easily, as one creates new glyphs!

It is also interesting to see what different people prefer as work order for masters. Mine may change moving forwards. Happy to try yours. But I think keeping the Ctr masters last is good for me, for sure.

**Comment by IgorFreiberger** [comment]
Two layers are unsorted in the last master VFJ file. I fixed them.

When I create new glyphs, layer order is preserved. But the colors are the original ones, not what we chose. I think this is a quasi-bug and I will file an issue in FontLab repository.

**Comment by tphinney** [comment]
@kateliev Consider this done, can we close it?

**Comment by kateliev** [comment]
Last few repo files i opened had some masters misarranged?!

**Comment by tphinney** [comment]
I have seen masters mysteriously rearrange themselves from one glyph to another. Or even temporarily disappear in one glyph, only to reappear after changing glyphs and switching back. sigh.
