### ISSUE TITLE
/g /r /m

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#42]
g r m (all masters)

**Comment by tphinney** [comment]
Mostly done with "g" and "r"

**Comment by tphinney** [comment]
"g" and "r" are done, except maybe for checking anchors.
"m" is still a bit rough. Some glyphs are not overlapped correctly, need work, especially the contrast and maybe the light? But anchors are all good.

**Comment by tphinney** [comment]
Oops, moving back as I haven't done with "m" yet.

**Comment by tphinney** [comment]
Finished a pass on the "m". Not so sure about my handling of the Contrast masters.

**Comment by servantb** [comment]
I think we're good to go on the /m if you want to remove the overlaps. Either way, the form is solid, so I think we can close this.
