### ISSUE TITLE
Create process for generating variable TTF

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#43]
Placeholder for what may very well become an "epic" (with component tasks).
Basically, although being able to export variable fonts direct from FontLab is fine for some testing/dev purposes, we need to play with an open source final toolchain.

May involve some scripting.

Likely includes:
- export VF as UFO from FontLab, whether directly or indirectly.
- export .designspace files (or write separately)
- other steps...

**Comment by tphinney** [comment]
Dave Crossland says:
“I wonder if Glyphsapp file export and fontmake might be easier, unless you have a DesignSpace file export already”

Which we do from FontLab VI, although I was thinking of writing the DesignSpace file manually, rather than learning the FL interface for the data.

**Comment by tphinney** [comment]
FontLab generates what I assume to be a functioning designspace file. Submitting that to the repo now.

Also, we have a first crude variable TTF, generated directly from FontLab. However, it has issues, just a demo for now.

**Comment by kateliev** [comment]
FontLab 6 was exporting usable VFs about a year and a half ago, far before even Glyphs ever started to produce usable data. This worry is (pardon my English :) ) "utter nonsense". Also we could always go UFO fontmake if we wish or be forced to. So do mot worry FL is great dor the job and we will manage!

**Comment by tphinney** [comment]
As noted in chat, it turned out that my main problems with the VF exported from FontLab were... Illustrator’s VF support is buggy. It worked perfectly in Axis-Praxis!

That said, I think we need to *also* be able to generate a VF from UFO + FontMake, if possible. Google would like that. I will ask how important it is.

**Comment by tphinney** [comment]
However, this issue as originally defined is solved. We can build variable TTF today, and they are working. https://recordit.co/g9KnZq2Dbv

I will open a new issue, with a later deadline, for the rest of it.  :)

**Comment by kateliev** [comment]
@tphinney re-opening for collecting useful tips and tricks in later stages of FontMake based VF generation!

**Comment by kateliev** [comment]
📓❗️ Kerning should be matched across masters!

**Comment by tphinney** [comment]
I don't know if y'all have noticed, but for the last couple of months, I have just been updating @kateliev's post of Sep 18 in this thread, where he outlines the build process. https://github.com/tphinney/science-gothic/issues/91

I should migrate this to a separate doc in the repo, link to it from the main repo readme, and keep it up to date with all the latest developments.

**Comment by tphinney** [comment]
I have done that migration to a separate doc. Linking now.
https://github.com/tphinney/science-gothic/blob/master/documentation/compiling_fonts.md
