### ISSUE TITLE
Normalizing recipes: always use the new syntax

### ISSUE THREAD

**Issue by IgorFreiberger** [tphinney/science-gothic#46]
The auto layers created by FontLab VI automatically (with add glyphs command or a double click on a still-to-be-created) use the old syntax to keep backward compatibility.

I suggest to adopt the new syntax in all auto layers. The recipes available in this repository uses the new syntax and the glyphs colon and semicolon also does. But the Cyrillic letters that are mirrors of Latin ones are all using the old syntax.

**Comment by tphinney** [comment]
I believe we discussed this in chat? Anyway, I agree and have been using the new (Glyph Construction Language) syntax consistently. Also good that this is the cross-app standard, as opposed to the old proprietary FontLab syntax.
