### ISSUE TITLE
Normalizing tags: unnecessary tags and taken strings

### ISSUE THREAD

**Issue by IgorFreiberger** [tphinney/science-gothic#47]
I see we are using two tags that are not necessary: **auto** and **composite**. Both are virtual tags set internally by FontLab VI. Until now, there is no known problem by using a string that is already reserved to virtual tags. But I think it is more secure not to use these reserved strings. And it is also an unnecessary.

We are also using the **cyr** tag. Again, glyphs belonging to Cyrillic script are automatically identified by FontLab VI. The tag is useful only if we plan to add glyphs that are not coded nor are small caps with a coded upper case correspondence. Otherwise, **cyr** could be removed.

**Comment by kateliev** [comment]
Could you please leave my tags alone :) I need those to distinguish between glyph types, as I generally find the current flagging scheme utterly noneffective for design - it might be good for managing, but otherwise useless...

There is nothing wrong with using the hard-coded tags - they even colorize themselves when used - an indicator, that someone tough they might be used in that way. Also as FL6 search is extremely unreliable i prefer searching by user-added tags, so i prefer my "auto" before FL's inbuild search for auto...

And finally... what actual damage do the project could some unnecessary tags do? Don't we have enough glyphs to draw that we are discussing something irrelevant?

**Comment by IgorFreiberger** [comment]
I know all that you wrote as already stated in the opening text. There is no problem **BY NOW**. This is a project open to further development and we don't know how FontLab VI will develop —so my alert.

**Comment by tphinney** [comment]
First, no objection to anybody using any FL tags they like in general. BUT the use of tags with the same names as FL internal auto-tags does seem slightly risky, so I have just inquired of the FL team as to whether allowing this is a feature, a bug or something they didn’t consider.

I would also love to understand what use you have for a tag that _duplicates_ the functionality of an FL internal auto-tag (whether with the same name, or a similar one). My understanding is not required. But I like to understand things. There may be some use the rest of us could be making, among other things.

Aside from that, I would love to have people document their use of tags in a Google doc or spreadsheet. It might be useful to others to make use of the same tags. Or do you see a need to keep tags private, per-user?

**Comment by tphinney** [comment]
OK, so I learned something! I guess all is OK, and this is a feature—which probably all of us could use. Hmmmm.

Adam writes:

> That's definitely a feature and is considered. This is to let you add glyphs to groups created by virtual tags. For example, FontLab tags figures with the `figs` virtual tag and tags glyphs that it believes are uppercase with the `uc` virtual tag. 
> 
> If you turn on both Tags and Virtual Tags in Features panel > Include Classes, then FontLab will convert these virtual tags groups into FEA classes, and you can do contextual stuff such as `sub @figs slash' by fraction` ora series of  `sub @uc acutecomb' by acutecomb.case; sub @uc gravecomb' by gravecomb.case;` etc.
> 
> When you assign a `uc` or `figs` manual tag to any glyphs, those glyphs will also be included in the automatically-created FEA classes @uc and @figs. 
> 
> The same mechanism works of course for tag-based zones and stems. FontLab makes a virtual tag `tos` for "top overshoot" glyphs where it packs some glyphs, but you can tag more glyphs with `tos` and then if you assign `tos` to a zone, it'll only be used in those glyphs with either a virtual or a manual `tos` tag
>
> and if you mix scripts, you may have some stems for `latn` and some for, say, `beng` (Bengali), and then you may have some glyphs where you assign both the `latn` and `beng` tag, and the stems will work in these.
> (for hinting)

**Comment by IgorFreiberger** [comment]
Although useful, Adam's answer focuses on adding virtual tags to glyphs not tagged automatically by FontLab. He did not clarified if there is any issue to adding then to glyphs already auto tagged.

**Comment by tphinney** [comment]
I think it is fine. Adam also writes:

>There isn't any hardcoded functionality that *uses* virtual tags. They're produced as a "side-effect". 
> 
> Right now we don't yet support this, but for some operations done automatically during export, like "Correct contour direction" or "Remove overlap", there will be virtual tags — for example "Decompose" and "Remove overlap" would always be run on the glyphs that have the virtual tag "noncomposite" (or something), and then you’ll be able to use tags to add (and possibly remove) the glyphs from those processes. So you’ll be able to enforce decomposing and removing overlap on some additional glyphs. 
> 
> Maybe those tags would be explicit: "noexport" for glyphs that should be omitted from export, "exportoverlap", "exportdecompose" etc. But this is for the future. 
> 
> But no, AFAIK, there are no problems with using these such virtual tags right now.
