### ISSUE TITLE
Criteria to use overshoots consistently

### ISSUE THREAD

**Issue by IgorFreiberger** [tphinney/science-gothic#49]
I am still not sure about the criterion for overshoots. At this moment, we have:

1. Overshoots in glyphs with curves at both sides, like O, U, and S.
2. No overshoots in glyphs with no curves, like M, T, and K.
3. No overshoots in glyphs with curves just at one side, like D. I used this as the criterion to draw B, P, and R.

Besides the confirmation of the situation 3, I would like to know exactly the amount of overshoot to use. Uppercase values in O, U, and S are consistent. But the overshoot for black masters is greater in lowercases p and q, for example. They use 24u in all black masters, while in uppercase we have 14u for black normal and extended, and 18u for black condensed.

I did not check all glyphs in all masters so other small variations may exist.

**Comment by servantb** [comment]
Points 1, 2, and 3 are all correct.
The amount of overshoot to use for any rounded glyphs or glyphs with a rounded part leading to a joint with a stem (a, n, h, b, d, p, q, r, m) the overshoot values are listed on the SG Measurements spreadsheet.

I just noticed the b, d, p, and q all lack proper (any) overshoots. I'll start a new issue for that.
