### ISSUE TITLE
Validate overshoot values

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#5]
Thomas & Brandon to do visual checks and validate overshoot values.

**Comment by servantb** [comment]
For glyphs ACGHOacenos:
• Fixed thin horz strokes on UC to be 18 units
• Fixed condensed layers for G
• Standardized overshoots for rounded glyphs

**Comment by servantb** [comment]
We will need to update/validate overshoots for d, h, p, and q.
