### ISSUE TITLE
E width needs increased across all Blk masters in proportion to other glyphs

### ISSUE THREAD

**Issue by servantb** [tphinney/science-gothic#50]
The E is too narrow in the Black masters compared to other glyphs. Should be the same or wider than F. Compare across masters (especially Medium).![Screen Shot 2019-08-19 at 7.46.21 AM.png](https://images.zenhubusercontent.com/5d4a125675d0cc52188b0d30/c0369875-09f7-434b-9759-b767373245f8)

**Comment by tphinney** [comment]
+90 Blk Cnd / Blk Cnd Ctr
+120 Blk / Blk Ctr
+200 Blk Exp / Blk Exp Ctr

**Comment by tphinney** [comment]
Brandon, look OK to you now?

**Comment by servantb** [comment]
Beautiful!
