### ISSUE TITLE
Revisions to dot shape in /period /comma, related punctuation

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#53]
Yesterday when preparing review slides for Google, I did a lot more testing of the existing characters in text strings.

I concluded that making the period and comma so _very rectangular_ in the heavier weights just “doesn’t look right.” They (and related characters: colon, semicolon, exclam, question :;!?) need to remain reasonably square. Some rectangularity may be needed, but a lot less than we have now.

Also in the originals, and probably desirable:
- The widths of these punctuation dots are significantly wider than the regular stem width, for the same weight. This is true across weights and widths of Benton’s design
- The size of the “dot” part of the comma is a little smaller than the period

I would be happy to do this, but Brandon is also welcome to do so, since it is his work.

**Comment by servantb** [comment]
Pushed to master on 8-21-2019

**Comment by tphinney** [comment]
I was reviewing these, and they are much improved!

I think the dot size in the Lt weights could be increased. Currently, the dots in those extremes are very hard to even see. When I look at well-made extra-light typefaces, I note that they tend to have _surprisingly_ large dots, and those work remarkably well. Or, in some cases they extend the thing vertically, such as in Helvetica Neue. 

<img width="267" alt="Screen Shot 2019-08-22 at 10 44 19 AM" src="https://user-images.githubusercontent.com/6548266/63537310-4addd280-c4ca-11e9-82b0-cb510b32f024.png">

<img width="271" alt="Screen Shot 2019-08-22 at 10 44 24 AM" src="https://user-images.githubusercontent.com/6548266/63537315-50d3b380-c4ca-11e9-8205-85a39cef9845.png">

<img width="266" alt="Screen Shot 2019-08-22 at 10 45 53 AM" src="https://user-images.githubusercontent.com/6548266/63537323-54ffd100-c4ca-11e9-8689-2d1eb13ee4b2.png">

<img width="452" alt="Screen Shot 2019-08-22 at 10 46 45 AM" src="https://user-images.githubusercontent.com/6548266/63537337-59c48500-c4ca-11e9-9a95-31a4ffaca951.png">

**Comment by servantb** [comment]
Sounds reasonable. I've made them 70u wide, which I think works just fine.

I decided to do some maths to see if my intuition works. Given the ratios of the stem widths of the UC to the widths of the period in their respective masters in Med and Blk, if I did the math right, that should put the width of the period in the light at about 66u, so I think 70 should do it.

Pushed to the repo.

**Comment by servantb** [comment]
Pushed revisions 8-28-19

**Comment by tphinney** [comment]
Looking better! I will do a closer look some time in the next few days, before I close this. But much improved.  :)
