### ISSUE TITLE
Diacritics (including combining)

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#54]
This is an epic; these will be subdivided into chunks. Probably start with the acute, then grave, circumflex and macron, in that order.

TBD, but for each, probably do the lowercase version, immediately followed by the cap (.case) version.

Here are the initial glyphs, lowercase (default) versions:

description — Unicode — glyph name
NON-SPACING GRAVE	0300	gravecomb
NON-SPACING ACUTE	0301	acutecomb
NON-SPACING CIRCUMFLEX	0302	uni0302
NON-SPACING TILDE	0303	tildecomb
NON-SPACING MACRON	0304	uni0304
NON-SPACING BREVE	0306	uni0306
NON-SPACING DOT ABOVE	0307	uni0307
NON-SPACING DIAERESIS	0308	uni0308
NON-SPACING HOOK ABOVE	0309	uni0309
NON-SPACING RING ABOVE	030A	uni030A
NON-SPACING DOUBLE ACUTE	030B	uni030B
NON-SPACING HACEK	030C	uni030C
NON-SPACING DOUBLE GRAVE	030F	uni030F
NON-SPACING INVERTED BREVE	0311	uni0311
NON-SPACING TURNED COMMA ABOVE	0312	uni0312
NON-SPACING HORN	031B	uni031B
NON-SPACING DOT BELOW	0323	uni0323
NON-SPACING DOUBLE DOT BELOW	0324	uni0324
NON-SPACING COMMA BELOW	0326	uni0326
NON-SPACING CEDILLA	0327	uni0327
NON-SPACING OGONEK	0328	uni0328
NON-SPACING BREVE BELOW	032E	uni032E
NON-SPACING MACRON BELOW	0331	uni0331
NON-SPACING SHORT BAR OVERLAY	0335	uni0335

**Comment by tphinney** [comment]
Only uni0309.case is incomplete at this point.

**Comment by servantb** [comment]
Edited /brevecomb_gravecomb.case :BlkCtr, :BlkCndCtr, and :BlkExpCtr

**Comment by servantb** [comment]
Issue #54:
Edited /uni0309 :Ctr, :BlkCtr, :CndCtr, :BlkCndCtr, :ExpCtr, and BlkExpCtr
Edited /uni0309.case to make it more proportional to the uppercase.
Created /brevecomb_hookcomb and /brevecomb_hookcomb.case
