### ISSUE TITLE
Orphan characters? Still need /eng.smcp

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#59]
There were some inconsistencies in the source data for our glyph complement. We have 34 small cap glyphs (currently lines 814–847 in the spreadsheet, highlighted in yellow) that are listed as being needed, but corresponding caps and lowercase are not in the source character sets! Example: e with macron and acute (U+1E17). 

Internal folks, see also: https://docs.google.com/spreadsheets/d/1PqLwYHyqI-ShTIcnX4S-VudQKyOh0_H-K701mVE0sZI/edit#gid=1168005480 

I have a query in with Dave as to whether we: (a) drop them as unneeded? or (b) add the 68 caps and lowercase to go with them?

Full listing:

ccedillaacute.smcp
ddotbelow.smcp
dlinebelow.smcp
emacrongrave.smcp
emacronacute.smcp
ecedillabreve.smcp
gmacron.smcp
hdotbelow.smcp
hbrevebelow.smcp
idieresisacute.smcp
ldotbelow.smcp
llinebelow.smcp
mdotbelow.smcp
ndotaccent.smcp
ndotbelow.smcp
nlinebelow.smcp
otildeacute.smcp
otildedieresis.smcp
omacrongrave.smcp
omacronacute.smcp
rdotbelow.smcp
rlinebelow.smcp
sdotaccent.smcp
sdotbelow.smcp
sacutedotaccent.smcp
scarondotaccent.smcp
sdotbelowdotaccent.smcp
tdotbelow.smcp
tlinebelow.smcp
utildeacute.smcp
umacrondieresis.smcp
ydotaccent.smcp
zdotbelow.smcp
tdieresis.smcp

**Comment by tphinney** [comment]
Also, note: I believe most of those glyph names, while they are in AGL (Adobe Glyph List) are not in AGLFN (Adobe Glyph List for New Fonts), most would properly get "uniXXXX.smcp" names . I doubt Google cares, but all things being equal, I mildly prefer to remain AGLFN-compliant. Less of an issue now than it was 15 years ago, so that part of it could be deferrable, in a pinch.

**Comment by tphinney** [comment]
(Waiting to hear what Google decides to do with the charset definition.)

**Comment by tphinney** [comment]
Although I still have no further news, I can say that all of these involve diacritics we have already made, for the font. So that's good.

The only complication would be, some of these involve _stacked_ diacritics. In some cases, we would need to add more anchors to the diacritics, I think. So for example, for the i with dieresis and acute (U+1E2F), we would need a (top) anchor on the dieresis to attach another diacritic on top of it. (In addition to the "_top" anchor it already has.)

Anyway, I imagine we could support all these combination, and it would be maybe 1 to 3 days of additional work—and probably on the lower end of that, like a day.

**Comment by tphinney** [comment]
Done for macron and caron.

Acute only gets a dot above, and there are some positioning complications for that. I see Brill for example has positioned the dot in the open space on upper left of acute, that seems sensible.

**Comment by tphinney** [comment]
Remaining part of this:
- check that acute + dot above is set up correctly (both standard and cap)

**Comment by tphinney** [comment]
Also, although we have a lowercase /eng, we need the cap /Eng

**Comment by tphinney** [comment]
@servantb checked in the cap /Eng today

Just need /eng.smcp added. @kateliev would you do that?

**Comment by tphinney** [comment]
(Since small caps are not required for initial delivery, removing milestone. All core delivery requirements from this issue are in place AFAIK.)

**Comment by kateliev** [comment]
/eng.sc done!

**Comment by kateliev** [comment]
@tphinney are we finished here? Or we have some more SC glyphs waiting?

**Comment by tphinney** [comment]
That's it! We are good, IMO. Other combos should be handled by combining diacritics.
