### ISSUE TITLE
parentheses (): /parenleft /parenright /parenleft.case /parenright.case

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#61]
Base designs, plus rotated/closing partner, plus their vertically shifted "case" versions. Total of 4 glyphs.
( )

parenleft
parenright
parenleft.case
parenright.case

**Comment by tphinney** [comment]
I am guessing these will need to be genuinely curved to distinguish them from brackets [ ].

**Comment by kateliev** [comment]
> plus their vertically shifted "case" versions

can't we just OT code the Case if it is only shifted?

**Comment by tphinney** [comment]
> > plus their vertically shifted "case" versions
> 
> can't we just OT code the Case if it is only shifted?

Hmmm. Probably, yes!

Long ago, Adobe used to hard-code some dumb assumptions about certain features being handled via GSUB rather than GPOS. So, back then, if you wanted your font to work properly in Adobe apps, you needed to do those features through GSUB. So I have had that habit.

But that was a long time ago. I imagine Adobe has fixed that bug. So, I imagine that as long as current Creative Cloud does it right, we shouldn’t care. And of course, our primary target is web browsers, and I am sure they do not have that (wrong) limitation.

**Comment by IgorFreiberger** [comment]
Parentheses, brackets, and braces are also not equal for lowercase and uppercase because, traditionally, in lowercase they embrace ascender and (partially) descender sizes. In UC they just match the caps measurement. They also need to be different in small caps.

**Comment by servantb** [comment]
I recommend tapering top and bottom to 36u for the Contrast masters.
(Before left, after right)

<img width="195" alt="Screen Shot 2019-09-13 at 10 38 51 AM" src="https://user-images.githubusercontent.com/50463501/64883165-97bd5080-d613-11e9-9db0-2197fb46a39a.png"> 
<img width="231" alt="Screen Shot 2019-09-13 at 10 37 25 AM" src="https://user-images.githubusercontent.com/50463501/64883164-9724ba00-d613-11e9-869b-935c615fbbe6.png">

**Comment by tphinney** [comment]
Ooh, yeah, that would be better. Doing that now. Thanks!

**Comment by tphinney** [comment]
Got distracted by fixing /W. Will get to this soon!

**Comment by tphinney** [comment]
I've done this for my next check-in. It is pretty ungainly in the black weights, but I am not sure I know how best to finesse it. Feel free to do some final edits.

**Comment by tphinney** [comment]
Looks better in :CtrEtc masters, thanks! Closing for now.
