### ISSUE TITLE
/Eth /eth Ð ð

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#64]

**Comment by tphinney** [comment]
Did cap Eth.

**Comment by tphinney** [comment]
Need to tweak ascender on :Blk styles of /eth

**Comment by tphinney** [comment]
fixed

**Comment by servantb** [comment]
I think the :BlkEtc /eth ascenders could still use some tweaking. Perhaps a little thinner at the bend.

Before:
![image](https://user-images.githubusercontent.com/50463501/68062306-e065c180-fcc6-11e9-84ad-ff8f522cc8ea.png)

After:
![image](https://user-images.githubusercontent.com/50463501/68062314-ec518380-fcc6-11e9-961a-a4887ebfa1c9.png)

**Comment by servantb** [comment]
The /Eth looks good to me.
@tphinney I'll leave the /eth for you to review.
