### ISSUE TITLE
New Font Tag: noauto

### ISSUE THREAD

**Issue by kateliev** [tphinney/science-gothic#67]
I would like to propose new Font Wide Tag: **noauto** that we use alongside with the already discussed **auto** (#47 ). The purpose of this **noauto** it to denote glyphs that otherwise would be generated by auto layers (and recipes) but are done by hand or feature minor adjustments to glyphs borrowed form other writing systems. Thus using **noauto** on a glyph will denote the wish of the designer that his particular character should be excluded from the auto glyph generation recipes.

**Comment by kateliev** [comment]
Oh my, Ya is never a clone... I meant some other, but yes that is the general idea.

**Comment by kateliev** [comment]
Actually besides A H O P B T C E M X K a o p e c (and sometimes y) there are no clones in Cyrillic. El is NOT a flipped V (same for lc) as well as Ya is not a flipped R and so on... so if @tphinney marked these as mere clones, or they are present in your (@IgorFreiberger ) recipes, please remove them.

Actually it will be safer for me to generate the auto-layers in Cyrillic block, so if you wish you could exclude those...

**Comment by IgorFreiberger** [comment]
Actually, as I know some Cyrillic (and Thomas too), our recipes are already aligned with what you said:

```
# Cyrillic
uni0400=E+gravecomb.case@top
uni0401=E+uni0308.case@top
uni0403=uni0413+acutecomb.case@top
uni0405=S
uni0406=I
uni0407=dotlessI+uni0308.case@top
uni0408=J
uni040C=uni041A+acutecomb.case@top
uni040D=uni0418+gravecomb.case@top
uni040E=uni0423+uni0306.cy.case@top
uni0410=A
uni0411=uni0182
uni0412=B
uni0415=E
uni0419=uni0418+uni0306.cy.case@top
uni041C=M
uni041D=H
uni041E=O
uni0420=P
uni0421=C
uni0422=T
uni0425=X
uni042B=uni042C&I
uni0430=a
uni0435=e
uni0439=uni0438+uni0306.cy@top
uni043E=o
uni0440=p
uni0441=c
uni0443=y
uni0445=x
uni0450=e+gravecomb@top
uni0451=e+uni0308@top
uni0453=uni0433+acutecomb@top
uni0455=s
uni0456=i
uni0457=dotlessi+uni0308@top
uni0458=j
uni045C=uni043A+acutecomb@top
uni045D=uni0438+gravecomb@top
uni045E=y+uni0306.cy@top
uni04A2=uni2C67
uni04AE=Y
uni04BB=y
uni04C0=I
uni04C1=uni0416+uni0306.cy.case@top
uni04C2=uni0436+uni0306.cy@top
uni04CF=l
uni04D0=A+uni0306.cy.case@top
uni04D1=a+uni0306.cy@top
uni04D2=A+uni0308.case@top
uni04D3=a+uni0308@top
uni04D4=AE
uni04D5=ae
uni04D6=E+uni0306.cy.case@top
uni04D7=e+uni0306.cy@top
uni04D8=uni018F
uni04DC=uni0416+uni0308.case@top
uni04DD=uni0436+uni0308@top
uni04DE=uni0417+uni0308.case@top
uni04DF=uni0437+uni0308@top
uni04E2=uni0418+uni0304.case@top
uni04E3=uni0438+uni0304@top
uni04E4=uni0418+uni0308.case@top
uni04E5=uni0438+uni0308@top
uni04E6=O+uni0308.case@top
uni04E7=o+uni0308@top
uni04E8=uni019F
uni04E9=uni0275
uni04EE=uni0423+uni0304.case@top
uni04EF=y+uni0304@top
uni04F0=uni0423+uni0308.case@top
uni04F1=y+uni0308@top
uni04F2=uni0423+uni030B.case@top
uni04F3=y+uni030B@top
uni04F4=uni0427+uni0308.case@top
uni04F5=uni0447+uni0308@top
uni051A=Q
uni051B=q
uni051C=W
uni051D=w

```
