### ISSUE TITLE
Character set should include Cyrillic alternates for non-Russian support

### ISSUE THREAD

**Issue by IgorFreiberger** [tphinney/science-gothic#7]
![BG Variable – Additions for Cyrillic.png](https://images.zenhubusercontent.com/5909406651aa2c30577d1c36/5d587a0a-00ef-456d-bda7-7161cdfb4bcd)

**Comment by tphinney** [comment]
Highlighted are some alternate forms needed for Bulgarian, Serbian, etc.
Given the character set, I would want to be sure to cover all such forms.

**Comment by IgorFreiberger** [comment]
The list (I use .la for "language alternate" and .sc for "small caps"):
uni0431.la
uni0432.la
uni0433.la
uni0434.la
uni0414.la
uni0414.la.sc
uni0436.la
uni0437.la
uni0418.la
uni0418.la.sc
uni0438.la
uni041B.la
uni041B.la.sc
uni043D.la
uni043F.la
uni0442.la
uni0424.la
uni0424.la.sc
uni0446.la
uni0447.la
uni0448.la
uni0449.la
uni044A.la
uni044B.la
uni044C.la

**Comment by tphinney** [comment]
I prefer to have a suffix that refers to the particular language(s), such as .locl.SRB and .locl.BGR. I think I have seen reference to this usage in Google fonts.

Of course, it isn’t perfect—what about alternates that are used for more than one locale? I suppose one could string those together in the suffix.

**Comment by kateliev** [comment]
I second that. It must be suffixed .locl.SRB and .locl.BGR and etc.

**Comment by kateliev** [comment]
Actually for this particular typeface style, you do not need Bulgarian or Serbian localisation. The given example by Igor is of humanist essence where loclBGR makes sense. In our case it is a matter of personal taste, ambition and publicity and less of practicality. Bank Gothic is nowhere near humanist in style nor is it "written" in nature - it is "drawn".

**Comment by IgorFreiberger** [comment]
Thanks, Vassil. Nice to know this subtle difference. Does the same criterion apply to Serbian and Macedonian variants?

About the suffix, it was not a proposal but the reason why the glyphs have that name (.la is not usual). But, Vassil, why do you add "locl" in the name?

**Comment by tphinney** [comment]
We do 'locl' because it is the OT feature used to access the alternates. So it is part of the general scheme of glyph names for alternates. This makes glyph names a bit more “deterministic”—the naming scheme is clear and there is only one possible name for most alternates. e.g.:
- a.smcp
- parenleft.case

In the case of locale-based alternates, the extra level is needed to specify which locale the glyphs are to be accessed under using the 'locl' feature. It also makes it really obvious which language code each glyph should be accessed by. (Some early Adobe OT fonts had all the right glyphs, but an incorrect locale code for Serbian! sigh.)

**Comment by kateliev** [comment]
Looking at the current state of things, I am starting to reconsider the inclusion of Bulgarian Localisation (.loclBGR) into the font, but only on the basic Cyrillic set - meaning no loclBGR for extended Cyrillic. What is your opinion.

**Comment by IgorFreiberger** [comment]
I'd like to understand what you call the "current state of things".

**Comment by kateliev** [comment]
"current state of things" = the lowercase looking too good to miss the opportunity of making BG Cyrillic Localisation :)

**Comment by tphinney** [comment]
I for one am completely OK with putting Bulgarian Cyrillic back in the spec, if you want to.

That said, I would suggest we consider it optional for now, and wait at least another three weeks or so. If we are on schedule, then great! If we are behind or barely on schedule, then we should put it off until late in the project, or even a post-launch update.

**Comment by kateliev** [comment]
I totally agree with that. This is for later when and if there is time!

**Comment by tphinney** [comment]
I think it is clear that while we are only a little behind schedule, we definitely don’t have extra time in the current cycle. This would make a nice 2.0 enhancement, though.
