### ISSUE TITLE
Check weight of thin strokes on Cap contrast masters

### ISSUE THREAD

**Issue by servantb** [tphinney/science-gothic#72]
Uppercase thin strokes in the contrast masters should be 36u.
Lowercase thin strokes in the contrast masters should be 32u.

Thin strokes in the contrast masters should be equivalent to their counterparts in the Lt master.

**Comment by kateliev** [comment]
@tphinney UC /A has reversed contrast in :Lt numerically as well as perception wise...
![image](https://user-images.githubusercontent.com/10247582/63858466-2f813480-c9ae-11e9-8a8b-2522281748fa.png)

**Comment by servantb** [comment]
Checked latin uppercase and numerals that were done so far. I'll leave the Cyrillic in the capable hands of @kateliev.

**Comment by tphinney** [comment]
I suspect that any Cyrillic that was messed up was only because it inherited from Latin. But it may be that some things started with Latin and were manually edited, so still need fixing (as opposed to using components that just got the fixes from the Latin). 

@kateliev to confirm.

**Comment by servantb** [comment]
I'll do the :Lt masters once we're settled on the curves from issue #103
