### ISSUE TITLE
.case variants of /hyphen /endash /emdash

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#75]
Will make as shifted versions of base chars using Glyph Construction Syntax.

Problem: In using glyph construction syntax, how do I specify that the FIRST (and in this case, only) component is to be shifted vertically relative to its start by a certain amount? I haven't quite been able to figure it out. Using a matrix transformation first resets the lower left glyph coordinate to (0,0), so it is no use.

Wanting to use it for shifting 'case' alternates, such as dashes and  brackets/parens/braces.

Per discussion, Igor suggested this solution:
> "The only way I found is to use a variable. For example: if you want to move the glyph 200u up, define a parameter (let's say case_shift) and use it:
> =dash@0,case_shift
> Otherwise, it always use absolute values from (0,0)."

**Comment by servantb** [comment]
Looks good to me.
