### ISSUE TITLE
/ring /uni030A (combining ring) /uni030A.case

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#78]

**Comment by tphinney** [comment]
Done. Will be checked in today.

**Comment by servantb** [comment]
@tphinney We'll see what you think of the latest edits.

**Comment by servantb** [comment]
I widened the ring (/uni030A and /uni030A.case) in :Exp, :ExpCtr, :BlkExp and :BlkExpCtr masters. @tphinney What say you?

**Comment by tphinney** [comment]
I looked at this, and it was good!
