### ISSUE TITLE
/breve /uni0306 (combining breve) /uni0306.case

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#79]

**Comment by tphinney** [comment]
Came back to this, working on /uni0306.case , the cap version. (The others are long done)

**Comment by servantb** [comment]
I think the /breve and /uni0306 look great.
Wondering if the /uni0306.case might be better served with higher "sides" to the bowl?

Before:

![image](https://user-images.githubusercontent.com/50463501/68049658-b3061d00-fca0-11e9-9cb3-fc9d27e6ca33.png)

After (with sides raised 40u):

![image](https://user-images.githubusercontent.com/50463501/68049701-cb763780-fca0-11e9-83f7-25a4ef3ee59e.png)

**Comment by servantb** [comment]
Actually, could even go 50u.

**Comment by tphinney** [comment]
Yeah, looks better. I was trying to keep within a very limited height, but ... yeah, that is better.

**Comment by servantb** [comment]
I think we're good here.
