### ISSUE TITLE
/ogonek /uni0328 /uni0328.case

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#82]

**Comment by tphinney** [comment]
Did some more on this the other day, but not quite finished fine tuning yet, I don’t think.

**Comment by tphinney** [comment]
Time permitting, I could revisit the ogonek and cap alt of it. I'm not happy with the terminal, and the whole treatment in the high contrast versions seems poor.

**Comment by kateliev** [comment]
I am also not in favor for the current Contrast solutions. Also please not that the current attachment points are wrong...
![image](https://user-images.githubusercontent.com/10247582/67948813-2d766480-fbef-11e9-84d4-d530c05f2650.png)

Attachment should be on the inner side as stated:
![image](https://user-images.githubusercontent.com/10247582/67948913-5d256c80-fbef-11e9-8eb1-bebb08ab0f1e.png)

Further reading: http://www.twardoch.com/download/polishhowto/ogonek.html

**Comment by servantb** [comment]
I love these solutions, @kateliev.

**Comment by tphinney** [comment]
Oops! Discussed in chat, but not in the bug. My bad!
For the record, I totally approved of @kateliev 's revisions and fixes here. I think the new design works MUCH better in the high-contrast masters in particular. Nice stuff.
