### ISSUE TITLE
Cyrillic :Cntr cap horizontals should be 36, not 40

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#89]
In the various :Cntr masters, the cap horizontals are supposed to be 36. But in the Cyrillic caps, they are (mostly? all?) 40.

**Comment by kateliev** [comment]
> But in the Cyrillic caps, they are (mostly? all?) 40.
Nope... only on :Cntr Expanded masters in /Pe /Be /Te and maybe one more...but nevertheless - my bad :) Will fix them Monday!

**Comment by kateliev** [comment]
Done!
