### ISSUE TITLE
Use 'votf' to reduce filesize by making small caps from the regular caps design space

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#9]
Dave Crossland
11:59 AM Jul 9
Also the 'votf' thing DB proposed (what he later has called "the parametric origin of glyphs") would significantly reduce filesize because the small caps could be located in the design space of the regular caps

Thomas Phinney
3:07 PM Jul 10
That is interesting, but seems more like something for a 2.0 release, no? Would it be in place in time for this project?

**Comment by kateliev** [comment]
Not sure if FL can handle those?

**Comment by davelab6** [comment]
Until ot1.9+, this is a scripting exercise, similar to ScaleEdit RoboFont plugin

**Comment by IgorFreiberger** [comment]
How votf would work? Small caps needs not only x/y scale factors, but also a small amount of boldness to achieve proper color. And, once scaled, some adjust to produce overshoots with an even effect to upper and lowercase.

Will this feature be able to produce that through parametric extrapolation? If yes, why not use the same tool to create superscript, subscript, denominators, numerators, scientific superiors and inferiors?

Until now, all automatic tools to create weights are imperfect, but maybe the voft will take data from the other weight masters to add boldness to OT features. It would be quite complex, but revolutionary.

**Comment by tphinney** [comment]
We made our initial pass at small caps via scripting, plus a bit of manual tweaking. It has worked fairly well.  :)

**Comment by tphinney** [comment]
Also, given the contrast (Y Opaque) axis, I doubt that small caps could ever be fully automated for Science Gothic. Or at least, not easily. We have always had to manually tweak/fix things, but _especially_ the high contrast masters, after stuff gets spit out of the scripted process. A less “sensitive” design would probably fair better, but because this goes to the limits....
