### ISSUE TITLE
Get 'mark' and 'mkmk' features working in variable font builds.

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#92]
Discovered that FontLab can't do 'mark' and 'mkmk' features in while exporting Science Gothic as VF. One must turn that feature off, to export the variable TTF from FontLab VI. If we need those, we will have to do the UFO+FontMake workflow for final VF generation.

**Comment by kateliev** [comment]
No we do not - we have all glyphs "hard-coded" (in outlines), why would we need 'mark' and 'mkmk' features. You either go with one or the other option - not with both...

**Comment by tphinney** [comment]
'mark' and 'mkmk' allow the font to support other combinations that were not considered. But you are right that in modern apps/OSes you shouldn’t need both. (We were hoping to get them “for free”!)

**Comment by IgorFreiberger** [comment]
I missed something here. Why a font should use one or another feature, but not both? And why modern apps and OSes wouldn't not need both?

Without them, there is no proper support for anything beyond the composites included in the font, which is quite limited. If FontLab VI does not allow mark and mkmk in final VF, I vote for additional workflow with FontMake.

**Comment by kateliev** [comment]
@IgorFreiberger I presume you are aware that the project has deadline.... 'mark' and 'mkmk' might seem as small benign features to add, but it is the small pebble that turns the cart. Those small things start piling up until we end up with avalanche of work.

>Without them, there is no proper support for anything beyond the composites included in the font, which is quite limited.

I personally find the included set sufficient enough... I cannot think of a language outside the scope that will benefit from 'mark' and 'mkmk', but I can be sure that if they are poorly executed or problematic to the font build "the world" will not look favorably upon us...

FontMake or not... for me it does not matter - I vote for not complicating the project any further without being forced by circumstances to do so...

**Comment by IgorFreiberger** [comment]
> I presume you are aware that the project has deadline.... 

Firstly, please avoid this tone. It appears you are talking to a child. Second, AFAIK, mark and mkmk were designed to work together and mkmk is not even possible without mark. But of course I may not know something —so my question.

I thought that adding proper top and bottom anchors in base letters and diacritics was part of the work. With these anchors, FontLab VI can generate mark and mkmk features automatically, with no impact in our deadline. Obviously, if we are not going to include all anchors, it’s a different scenario.

**Comment by tphinney** [comment]
> I missed something here. Why a font should use one or another feature, but not both? And why modern apps and OSes wouldn't not need both?

I worded that poorly! By “both” I meant “both” (1) 'mark' + 'mkmk' AND (2) precomposed glyphs for everything required by Google. 

> With these anchors, FontLab VI can generate mark and mkmk features automatically,

Actually, FontLab VI is (currently) unable to process 'mark' and 'mkmk' when directly generating a variable font from our sources. I have to turn off that option and use a custom VF export profile in FontLab.

HOWEVER, since we do need to get UFO + FontMake up and running, and transition to a UFO environment for variable font builds, as long as FontLab has no problems generating 'mark' and 'mkmk' during UFO export, we should be fine.

**Comment by tphinney** [comment]
UPDATE:

Although using composites in variable TTF from FontLab is reasonably compact, and more so than regular glyphs, it still has a not-negligible impact on file size. That was a concern Dave expressed on behalf of Google. So, ultimately, we really want to move to 'mark' and 'mkmk' rather than precomposed glyphs for many of these. (Which also questions our glyph list in the end!)

That said, in the interim, for now, _also_ having precomposed accented characters is handy for testing and debugging anchors and diacritics right in the font editor.

So, we need to get this working.

**Comment by kateliev** [comment]
> Actually, FontLab VI is (currently) unable to process 'mark' and 'mkmk' when directly generating a variable font from our sources. I have to turn off that option and use a custom VF export profile in FontLab.

This is bad. If I were you, I would press FL team to fix the issue! They might have it done before we finish the project. Yes we would explore the alternative approaches, but for me this is clearly a thing to be fixed - if you offer a VF export as an feature of your app, you should support it... or drop it,... not just half-support it ... as there is no such think as half-working font :)

**Comment by tphinney** [comment]
Update: AFAIK 'mark' and 'mkmk' are working in our UFO + FontMake builds of the TTF, so not a big problem for us. @kateliev : that is correct, yes?

**Comment by tphinney** [comment]
Needs to be tested with recent TTFs

**Comment by tphinney** [comment]
Appears to be working in the UFO + FontMake builds.
