### ISSUE TITLE
/slash /backslash /slash.case /backslash.case

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#93]

**Comment by kateliev** [comment]
Why do we keep having case sensitive forms in a display typeface?

**Comment by tphinney** [comment]
We have uppercase and lowercase. Being a display typeface doesn’t change that at all.
The /slash, guillemots, /questiondown and quite a few other glyphs benefit from having 'case' forms.

Only the diacritics get weight and shape adjustments, but most of these other glyphs get a height adjustment, easily done as an Auto Glyph. Plus often slightly different kerning.

**Comment by servantb** [comment]
These look good to me.
