### ISSUE TITLE
Tabular numbers?

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#96]
Do the default numbers need to be tabular?
Do we need tabular numbers, at all?

Interested in team opinion, as well as hearing back from Google.
(Even if Google says tabular numbers are not required, we could still do them.)

**Comment by kateliev** [comment]
> Do we need tabular numbers, at all?

SG is clearly a display typeface, so tabular figures do not fit at all with the intended usage. Nobody will ever need to make a table with SG, as having it on more than three lines of text will be a total overkill for the reader. So my opinion - NO we clearly do not need them!

> Do the default numbers need to be tabular?

No they do not... but in my experience if you make proportional figure as close to tabular as possible without loosing the intended aesthetic is actually very welcome feature - makes the figures more usable and "calm". You could easily fit 0,2,3,5,8,6,9 into almost the same width...

and finally to quote myself 

> SG is clearly a display typeface,...

We also do not need tabular, old-style, old-style tabular, subscript, superscript, scientific, numerator, denominator and fractional figures. Nobody will ever need nor use them in headlines and section headers.

**Comment by tphinney** [comment]
I am definitely hoping to avoid tabular numbers.
Oldstyle numbers are simply inappropriate to the design.

I *have* been planning to do fractions, but I admit that it doesn't seem the most important. I will at least raise the question with Google.

Fractions, superscript/subscript, numerator/denominator all go together: same set of glyphs, just shifted differently. We should either do them all, or none.

**Comment by tphinney** [comment]
On the other hand, 1-2-3-4 are needed for pre-built fractions and superiors that are part of the basic WinANSI character set. So, @kateliev , do you suggest we not cover all of WinANSI?

**Comment by kateliev** [comment]
Of course we cover it. My point was not to get carried away with features that would not be needed, but required if offered...

**Comment by kateliev** [comment]
> Oldstyle numbers are simply inappropriate...

Theoretically speaking I have to disagree here. Yes the intended usage of onum is beyond the intended scope of the face, but... as the essence of every display face is expressiveness not practicality... thus every expressive alternate form, especially if beutifully done, is welcome, as old style numbers... for example on a wine label of some sort. But something practical and not that aesthetically pleasing as tabular figures is total overkill... 

Nevertheless I am also against making onum in this font, but only because there is a lot to do already...

**Comment by IgorFreiberger** [comment]
**Tabular numbers** are not used only in tables. They are useful in lists:
1. With tabular numbers,
2. The text in a list like this
3. Stands aligned
4. With no further formatting

and also in dates. But I agree this is something to be considered if there is enough time.

**Old style numbers** seems inappropriate, but after Vassil's rationale I became less sure. Do you know other squarish fonts with old style figures? It would be nice to see a sample.

**Comment by kateliev** [comment]
> Tabular numbers are not used only in tables. They are useful in lists

A very nice example!... but then again as I stated before for me this is clearly a display typeface. I cannot imagine the face being used in that manner... on the other hand that is why I was advocating

>  ...if you make proportional figures as close to tabular as possible...

**Comment by tphinney** [comment]
Agreed.
Igor, other than /one, how far off are the existing figures from being tabular?

**Comment by tphinney** [comment]
Confirmed with @davelab6 that we do not need to make the default numbers tabular. Plus, the Google Fonts API does not currently support OpenType layout features, so at least for now, there is no added value from making tabular figures and currency.

Although tabular figures would be easy enough, some of the currency symbols would be insanely difficult—nigh impossible—to do in the more extreme condensed styles.

**Comment by tphinney** [comment]
One thing I might do, is to design an alternate tabular (or less-proportional) /one for future use, even if not currently useful.

BUT, that can wait, as it is not currently accessible in the Google Fonts API.

**Comment by davelab6** [comment]
@dberlow may have thoughts on tabular figures in large variation spaces :)

**Comment by dberlow** [comment]
Sketched and specimens here;
https://github.com/TypeNetwork/Robots-Extremo/issues/50

Effects monospaced fonts as well, starting with “m”.

**Comment by tphinney** [comment]
I think that pretty well describes the issue (though I am waiting on access to the video).

If we discount “giving up entirely” as a solution... it seems to me that all the solutions involve (1) and/or (2):
1) giving up on tabularity for some portions of the design space (for Science Gothic, :BlkCndEtc in particular, and maybe also :BlkEtc and :CndEtc), and/or 
2) give up on tabularity for certain characters, particularly among the currencies. The worst is the obscure and probably unneeded peseta sign (Pts ligature), U+20A7. But there are other troublesome ones.

Of course, if one chooses an option that involves some of both, there are questions about how to balance those two options. 

And no matter what one chooses, it raises questions about how to communicate the issue concisely but clearly to one’s users, to deal with the inevitable questions around “hey, I turned on tabular figures but it didn’t do everything I expected, your font is defective!” (or “TEH BROKEN”)

**Comment by tphinney** [comment]
Ah, saw the video now. Nice work! But it just shows the numerals, which (for me) are not so much The Real Problem. I am thinking especially of Euro (U+20AC), **naira** (20A6), **peseta** (20A7), dong (20AB), **rupee** (20B9), and **hryvnia** (20B4).

**Comment by dberlow** [comment]
Good point on the monetary.

But, I think the numerals alone are an issue. As you see, a single width can be impossible, there is no way to signal a partially tabular weight or width axis to a user, and no way to coordinate tabularity over a range of those axes or over sizes. 

If this is more intelligently handled with interoperable axes, there is a solution. Then, IMO, when one gets to tabular glyphs that go beyond the issue of numerals, there are solutions, even for manat, Won, 3/4 and Per thousand.

I don’t know if you are planning pnums, but there is an additional constraint that tnums and pnums May need to work together on a page and can’t be too different in a single style, no matter how the tab width may pull on things.

Happy varying.
David

On Oct 6, 2019, at 2:59 PM, Thomas Phinney <notifications@github.com> wrote:

Ah, saw the video now. Nice work! But it just shows the numerals, which (for me) are not so much The Real Problem. I am thinking especially of Euro (U+20AC), naira (20A6), peseta (20A7), dong (20AB), rupee (20B9), and hryvnia (20B4).

**Comment by tphinney** [comment]
So: yes, if we added tabular figures, we would also keep the proportional ones.

I designed a more-tabular alternate /one for potential later use.

Other than that, we are shelving this for now. Thanks for the input and ideas!
