### ISSUE TITLE
Decide on small cap height & adjust 'shgt' parameter on all masters

### ISSUE THREAD

**Issue by tphinney** [tphinney/science-gothic#97]
Need to decide on small cap height, and set 'shgt' parameter to match, in all masters.

Currently, 'shgt' parameter is set = 1200, which is almost certainly too high.
Probably something in the 1060–1100 range will be correct.

**Comment by IgorFreiberger** [comment]
The 'shgt' parameter is just a mock up.

**Comment by tphinney** [comment]
Brandon and I worked on this together. There is some info in this doc: https://docs.google.com/document/d/10PCpLwAJARauD_fLfSsdtAwzNGjijtJvYqTRA1-8x6g/edit#

**Comment by tphinney** [comment]
The numbers in the doc were used for a first trial build today, and it looks good!
